### ISSUE TITLE
Configure license header plugin 

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger-client-java#121]
The current configuration for the license header plugin updates the license header on build and doesn't seem to test the presence of a header when code without a header is checked in.

Read the documentation here https://github.com/hierynomus/license-gradle-plugin and configure the plugin to fail the build if a license header isn't applied. Do not apply the license header as part of the build. (Doing so unnecessarily applies the header to all the thrift generated files which is potentially slowing down the build).

**Comment by jpkrohling** [comment]
> doesn't seem to test the presence of a header when code without a header is checked in.

This doesn't seem to be the case anymore, as I do get build failures when I forget to add the header for a new class. I'm closing this, but if you think this is still the case, feel free to reopen it.

```
Missing header in: jaeger-core/src/main/java/io/jaegertracing/senders/NoopSender.java

> Task :jaeger-core:licenseMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jaeger-core:licenseMain'.
> License violations were found: /mnt/storage/jpkroehling/Projects/src/github.com/jaegertracing/jaeger-client-java/jaeger-core/src/main/java/io/jaegertracing/senders/NoopSender.java}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
9 actionable tasks: 7 executed, 2 up-to-date
```
