### ISSUE TITLE
Allow setting baggage headers on requests without a trace context

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#146]
It is useful
  * for debugging purposes, e.g. when you curl an endpoint and cannot start a trace from client side, 
  * in production scenarios, e.g. we have an auth plugin to haproxy that's written in Lua, for which we don't have a jaeger client lib yet, so they cannot do the normal tracing operations, but they do want to store the auth token in the baggage.

In other clients (e.g. [Go](https://github.com/uber/jaeger-client-go/blob/master/propagation.go#L144)) we allow using `jaeger-baggage: k1=v1,k2=v2` header for this purpose, as well as the normal `uberctx-`-prefixed headers.

**Comment by dray92** [comment]
Connecting #315
