### ISSUE TITLE
Support a Prometheus metrics endpoint

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-client-java#172]
Enable metrics collected from the Jaeger client, and the service (application) being instrumented, to be reported to a prometheus compatible metrics system.

Initial suggestion is to record some generic metrics related to any Spans of certain `span.kind`, such as `client`, `server`, `producer`, `consumer`.

Metrics names could be based on `service`, `operation` and `span.kind`.

A counter could be reported for the invocation of the service\operation\spankind. A counter could also be recorded for any span that has an `error` tag of `true`.

Protocol specific scenarios should also be considered - for example with HTTP we may want to record counters regarding the status code categories, e.g. 4xx, 5xx.

**Comment by yurishkuro** [comment]
Is the goal to observe the behavior of the tracer, or behavior of the application? We already have internal metrics for the tracer, and in Go we have a model for reporting (inbound) RPC metrics that we were planning to extend to other languages (but we need to make it less HTTP specific).

As for Prometheus, I think it's a different issue of implementing [StatsFactory](https://github.com/uber/jaeger-client-java/blob/master/jaeger-core/src/main/java/com/uber/jaeger/metrics/StatsFactory.java).

**Comment by objectiser** [comment]
> Is the goal to observe the behavior of the tracer, or behavior of the application? 

I think having both would be useful, as you have demonstrated in the Go client.

Would be great if a consistent approach can be used across all languages to record app metrics for inbound and outbound communications in a protocol independent way, although as mentioned, we may want some protocol specific metrics.

**Comment by yurishkuro** [comment]
I agree, we need to get all clients to use the same metrics naming scheme, which is not the case today.

For RPC metrics, the latest discussion we had internally was to use the following scheme (first is the metric name, the rest are tags):
```
name:       jaeger-rpc.{requests, request_latency}
service:    myservice 
endpoint:   fooendpoint 
result:     {ok,err}
error:      {4xx,5xx,app-error,sys-error,rate-limit,timeout,...}
transport:  {http,tchannel,...}
direction:  {inbound,outbound}
```
Some of these tags require additional help from instrumentation

The actual tracer behavior is, I think, already well captured in the metrics, but they do differ in the naming scheme between languages (in some languages we did not use tagged metrics)

**Comment by objectiser** [comment]
Looks a good start. Some suggestions:

* `name` - possibly just `jaeger` rather than `jaeger-rpc` - to avoid RPC specific
* name value - just `latency`, and maybe something more generic other than `requests` to cater for messaging as well
* `endpoint` - could this be `operation` to more directly relate to the span data
* `transport` - is this because the same endpoint may use multiple protocols?
* what about adding a location based tag - either hostname or ipaddr - so when multiple instances of the service it would be possible to isolate the metrics related to a particular instance that may be having problems?

**Comment by yurishkuro** [comment]
> name - possibly just jaeger rather than jaeger-rpc - to avoid RPC specific

Can do.

> endpoint - could this be operation to more directly relate to the span data

Also can do.

> transport - is this because the same endpoint may use multiple protocols?

Technically, yes. However, there is currently no standard tag that identifies the transport, so the only one we can reliably detect is HTTP, by the presence of other tags like http.url and http.status_code

> what about adding a location based tag - either hostname or ipaddr

Our practice has been to leave these to the application itself. I.e. when initializing the tracer with metrics factory, the factory can already be created with some tags like the hostname. This way the tracer does not need to worry about it. Attaching the host name by default is not a great behavior, because it multiplies the number of all time series by the number of hosts, putting a lot of extra pressure on the metrics backend.

**Comment by yurishkuro** [comment]
Question directly related to the issue title - is there some Java framework similar to go-kit that provides abstraction over different metrics implementations?

**Comment by objectiser** [comment]
We are not aware of one.

**Comment by burmanm** [comment]
Wouldn't dropWizard metrics be the "standard" ?

**Comment by burmanm** [comment]
Not to mention I don't personally understand the Prometheus part at all, given that Java has a standard way of exposing metrics already (JMX). But DropWizard metrics allows exporting to multiple different formats by just dropping a different library to the classpath (without any need for modifications to the original library)

**Comment by mabn** [comment]
Dropwizard metrics are popular, but they are not an abstraction but rather a specific opinionated implementation.
Microprofile has a proposal (https://github.com/eclipse/microprofile-evolution-process/pull/26) but it wasn't approved yet.

**Comment by objectiser** [comment]
One reason for the Prometheus suggestion is it is polyglot so can provide a consistent solution across all the supported clients.

**Comment by yurishkuro** [comment]
Prometheus is still a lock-in to a specific metrics format. Our current approach is to write metrics to an internal API, and implement adapters from that API to other metrics APIs, like Dropwizard and Prometheus Java client.

**Comment by objectiser** [comment]
Agree need an abstraction to support other formats. But this issue is specifically about providing a Prometheus impl. So not suggesting it should be the one and only impl.

**Comment by objectiser** [comment]
Have created an issue https://github.com/opentracing-contrib/java-metrics/issues/1 to discuss a possible naming scheme.

The proposal defines a small set of standard labels with the ability to add/override where necessary, which I believe should meet Jaeger's requirements.

**Comment by objectiser** [comment]
Wondering whether there could be further naming alignment with opentracing terms, e.g.

* `result` and `error` - possibly either `error` as a boolean field (as in OT) with `error_type` to represent more specific value - or just collapse into single field `error` with value `false` or `no` for no error, and other values representing the error type

* `direction` - use span kind instead where `inbound` is effectively represented now by `server`/`consumer`, and `outbound` is `client`/`producer`

**Comment by mabn** [comment]
http://micrometer.io/ this seems promising. Part of spring boot 2.0 so it will be widely used.

**Comment by yurishkuro** [comment]
@mabn - lgtm. The documentation is a bit weird, considering that the lib claims to provide abstraction over different metrics implementation, but all documentation is actually _split_ by implementation. But it looks like the CompositeMeterRegistry is what we'd need.

The Jaeger libraries are always defining their own metrics API anyway, but we can have a module that binds that API to micrometer API.

**Comment by jpkrohling** [comment]
Done as part of #335.
