### ISSUE TITLE
add wrapper for ScheduledExecutorService

### ISSUE THREAD

**Issue by ccl0326** [jaegertracing/jaeger-client-java#222]
as title.

**Comment by yurishkuro** [comment]
Now that context propagation via ActiveSpan is part of the OT API, we're moving away from Jaeger's custom instrumentation of frameworks in favor of respective opentracing-contrib libs. You can already use those libs with Jaeger today, and there is https://github.com/opentracing-contrib/java-concurrent

**Comment by ccl0326** [comment]
According to my understanding ActiveSpan is a good abstract for context propagation, I can implement wrapper of ScheduledExecutorService with ActiveSpan more easily. But i think whether wrapper of ExecutorService or ScheduledExecutorService are should be exists for low invasive.

**Comment by pavolloffay** [comment]
Closing please use opentracing instrumentations from opentraicng-contrib
