### ISSUE TITLE
Classpath issues with the new Jaeger Core shadow jar

### ISSUE THREAD

**Issue by maranellored** [jaegertracing/jaeger-client-java#232]
We've been using the Jaeger core library for tracing in our Dropwizard/JAXRS application. 
We have a dependency on the `jaeger-core` library in order to support the tracing feature. 

Ever since the upgrade to version `0.20.6`, it looks like the Jaeger core library is published as a standalone jar and also a shadow jar using the shadow plugin to include OkHttp, for the same POM in maven central. 
This has been causing us issues since our Gradle packaging automatically adds both the jars to our runtime dependency tree. 
The shadow jar now includes dependencies that we cannot override (for e.g. it includes some of the `org.apache.httpcomponent.*` packages, which are pulled in by OkHttp, that cause conflicts in our classpath with some other dependencies that we directly depend on). 

Would it be possible for you guys to deploy the shadow jar using different maven co-ordinates? 
My looking around for a solution to exclude the fat jar from gradle has turned up nothing, so it seems to me like the best way is to separate the jars during publish time.

**Comment by vprithvi** [comment]
>Would it be possible for you guys to deploy the shadow jar using different maven co-ordinates?

The shadow jar is already using different coordinates (I'm not sure how one would upload two jars to the same coordinates and have both coexist)

The coordinates for the shadow jar include the optional [classifier](https://maven.apache.org/pom.html#Dependencies), while the normal jar uses the existing coordinates.

The shadow jar is at 
``` xml
<dependency>
  <groupId>com.uber.jaeger</groupId>
  <artifactId>jaeger-core</artifactId>
  <version>0.20.6</version>
  <classifier>okhttp381</classifier>
</dependency>
```

I don't think gradle should be automatically adding all classifiers for a given dependency into the runtime path. Could you post a minimal gradle build that reproduces this issue?

**Comment by maranellored** [comment]
Ok, I have an example Dropwizard application setup at https://github.com/maranellored/jaeger-dependency-conflict 
You can clone it and run the application using `java -jar build/libs/jaeger-dependency-conflict-all.jar server` 
The issue seems to be actually related to the jaeger-zipkin library and not the jaeger-core package. 
Commenting out the jaeger-zipkin dependency seems to cause the application to work.

**Comment by vprithvi** [comment]
Thanks for the example. Do you need the `jaeger-zipkin` in your classpath? It is a thin wrapper over the official `zipkin-reporter` and `zipkin-sender-urlconnection` to allow jaeger spans to be reported to Zipkin servers.

**Comment by maranellored** [comment]
At the moment, we do need the Zipkin reporter since we're in the process of migrating some of our old Zipkin tracing infrastructure to Jaeger. We are reporting spans to Zipkin at the moment and are still using the B3 headers for communicating trace information between services.

**Comment by jpkrohling** [comment]
If the `jaeger-zipkin` module can work with your version of OkHttp/Apache HTTP Components, you can workaround this issue by setting Gradle/Maven to exclude the dependency. See this: https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

In any case, we'd ideally relocate our dependencies on shadowed jars, to avoid this kind of problem: https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html

**Comment by maranellored** [comment]
Thanks, I think we might have a workaround for now. I'll close this issue for now.
