### ISSUE TITLE
Migrate to github.com/jaegertracing org

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#238]
Per https://github.com/jaegertracing/jaeger/issues/409
  * [x] Doing the repo move
  * [x] Re-registering the repo with Travis
  * [x] Re-registering the repo with Coveralls/CodeCov
  * [x] Updating the links to badges in the README
  * [x] Adding DCO file
  * [x] Adding sign-off checker bot
  * [x] Updating CONTRIBUTING instructions to require sign-off
  * [x] If not done yet, updating to Apache license #239
    * [x] Replacing LICENSE file
    * [x] Updating CONTRIBUTING instructions and references to license in the README
    * [x] Updating the check-license script

**Comment by jpkrohling** [comment]
The new Maven coordinates are ready to accept artifacts: https://issues.sonatype.org/browse/OSSRH-34706

**Comment by yurishkuro** [comment]
Parent task https://github.com/jaegertracing/jaeger/issues/409

**Comment by yurishkuro** [comment]
@vprithvi I updated the description with the tasks.

The change in the published artifact can be done separately, not as part of the move.
