### ISSUE TITLE
[Discussion] When should we release v1.0?

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger-client-java#253]

**Comment by yurishkuro** [comment]
I think when OT for Java 1.0 is released. What are the other considerations?

**Comment by objectiser** [comment]
Would that be a good time to change the maven group id? Or should that been done earlier.

**Comment by pavolloffay** [comment]
I wanted to raise an issue about tracer-builder/Configuration API. it's not very intuitive we should consider changing that before 1.0.

**Comment by yurishkuro** [comment]
I created a milestone instead

**Comment by yurishkuro** [comment]
Actually let's keep open if we need to discuss anything else, since can't comment on the milestone.

Does everyone agree with the current items in the milestone? Any of them that do not need to be blockers for 1.0?

https://github.com/jaegertracing/jaeger-client-java/milestone/1

**Comment by yurishkuro** [comment]
Reopen to have place for comments

**Comment by pavolloffay** [comment]
The last thing we could do is to check whether we can remove (if any) deprecated APIs.

**Comment by yurishkuro** [comment]
I think removing deprecated APIs is quite important for 1.0. Also cleaning the APIs, i.e. to make sure all construction patterns are consistent, etc.

**Comment by jpkrohling** [comment]
> Also cleaning the APIs

And clearly marking what is part of the public API, and what's "internal" API. Most of the things in the `core` module will probably be public API, but everything else is probably internal and should not be used directly.
