### ISSUE TITLE
NPE if null passed to asChildOf

### ISSUE THREAD

**Issue by mihbor** [jaegertracing/jaeger-client-java#254]
com.uber.jaeger.Tracer$SpanBuilder implements io.opentracing.Tracer$SpanBuilder but violates its contract.
javadoc for io.opentracing.Tracer$SpanBuilder.asChildOf says:
```
         * If parent==null, this is a noop.
         */
        SpanBuilder asChildOf(BaseSpan<?> parent);
```
However, the jaeger Tracer instead throws a NullPointerException:
```
java.lang.NullPointerException
	at com.uber.jaeger.Tracer$SpanBuilder.asChildOf(Tracer.java:218)
```

using version 0.21.0

**Comment by vprithvi** [comment]
Thanks for the issue. This was recently fixed in https://github.com/jaegertracing/jaeger-client-java/pull/243
