### ISSUE TITLE
Null baggage item causes NPE

### ISSUE THREAD

**Issue by bmozaffa** [jaegertracing/jaeger-client-java#256]
Adding a baggage item with a null value throws an exception during serialization:

Caused by: java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:204)
	at com.uber.jaeger.propagation.TextMapCodec.encodedValue(TextMapCodec.java:124)
	at com.uber.jaeger.propagation.TextMapCodec.inject(TextMapCodec.java:67)
	at com.uber.jaeger.propagation.TextMapCodec.inject(TextMapCodec.java:34)
	at com.uber.jaeger.Tracer.inject(Tracer.java:159)
	at io.opentracing.util.GlobalTracer.inject(GlobalTracer.java:118)
	at io.opentracing.contrib.jaxrs2.client.ClientTracingFilter.filter(ClientTracingFilter.java:76)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:413)

Ideally, the baggage items would appear for the recipient with a null value, but FWIW, at least the RESTEasy implementation appears to drop any request headers with a null value so this may be difficult and/or inconsistent. Ignoring a null value may not be ideal, but the current behavior can be very problematic.

**Comment by yurishkuro** [comment]
Thanks for raising this.

> Ideally, the baggage items would appear for the recipient with a null value

given the API `span.getBaggageItem(key)`, there is no way to distinguish null value actually stored against the key vs. the key itself missing.

I agree that the NPE is not a desirable behavior, I think we should put a protection that either ignores the null value or if the key is already present in the map it removes the key.

Would you like to submit a PR?

**Comment by bmozaffa** [comment]
I set up a local environment to fix it, but could not reproduce and it actually appears that this change has resolved the issue: https://github.com/jaegertracing/jaeger-client-java/commit/a44f07f696ba85e7d2a8a9584869d5aa165d084d#diff-3d3d7da07ba0eaec180b3716f68601b6

Specifically: https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/com/uber/jaeger/Span.java#L125-L127

I'm not sure if this was incidental, part of a refactor, or to address a related issue, so let me know how you want to mark/close this issue.

**Comment by yurishkuro** [comment]
The lines you pointed are not exactly the same, because they completely ignore null values. In case of a key already being present, it makes more sense that re-setting it to null would remove the key from baggage.

**Comment by bmozaffa** [comment]
True, the change that had been made resolves my particular problem but leaves a new bug in that old baggage values will not be updated or removed when replaced with a null value. See PR 260 above.
