### ISSUE TITLE
Revisit construction API for all core public components

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger-client-java#258]

**Comment by jpkrohling** [comment]
I just changed the title of this issue based on @pavolloffay 's comment. If it's not appropriate, feel free to revert.

**Comment by jpkrohling** [comment]
@vprithvi, @pavolloffay: based on the discussion on gitter, I'm about to close the PR related to this issue, as it seems the actual need is something else.

@yurishkuro, @vprithvi: would you please amend this issue, describing what is the problem and, if possible, what's the proposed solution? 

It would also be nice to reassess whether this should be included in the milestone for 1.0.
