### ISSUE TITLE
Check style is failing

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#263]
E.g. this build https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/285212390

```
:jaeger-core:checkstyleMain[ant:checkstyle] [ERROR] /home/travis/build/jaegertracing/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/SpanContext.java:179: Abbreviation in name 'getTraceID' must contain no more than '2' consecutive capital letters. [AbbreviationAsWordInName]
[ant:checkstyle] [ERROR] /home/travis/build/jaegertracing/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/SpanContext.java:187: Abbreviation in name 'getSpanID' must contain no more than '2' consecutive capital letters. [AbbreviationAsWordInName]
[ant:checkstyle] [ERROR] /home/travis/build/jaegertracing/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/SpanContext.java:195: Abbreviation in name 'getParentID' must contain no more than '2' consecutive capital letters. [AbbreviationAsWordInName]
```

We keep the methods like `getSpanID` as deprecated for legacy reasons. We also don't specify the checkstyle config directly, iirc it's imported from one of the google jars.  Can we still suppress the checks on these 3 methods?

cc @pavolloffay @objectiser @vprithvi

**Comment by objectiser** [comment]
You just need to update the line numbers in https://github.com/jaegertracing/jaeger-client-java/blob/master/config/checkstyle/suppressions.xml#L9 - they have been shifted by a couple of lines due to the new license header.

**Comment by pavolloffay** [comment]
+1 on Gary's response. 

> We also don't specify the checkstyle config directly, iirc it's imported from one of the google jars

checkstyle is defined directly in the repository  https://github.com/jaegertracing/jaeger-client-java/blob/master/config/checkstyle/checkstyle.xml

**Comment by yurishkuro** [comment]
Thanks for the pointers, I fixed it. Once I merge #262 we should update CONTRIBUTING, because I don't think its description is correct (it refers to https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)
