### ISSUE TITLE
Update instructions for IntelliJ code style plugin

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#265]
Since we switched to explicit checkstyle config, the previous comment about IntelliJ plugin was removed.

**Comment by fzakaria** [comment]
I've had very good success using: https://github.com/diffplug/spotless as part of a gradle build specifically google-java-format.
Since working on a golang codebase I've preferred auto formatting much more than enforcing a style through "errors" (checkstyle)

**Comment by yurishkuro** [comment]
+1, I also prefer auto-format, but in most Go IDEs it's done by running the exact same std tool, whereas in Java the plugins behavior seems to be different, and running gradle on save does not seem to be feasible.

**Comment by fzakaria** [comment]
The workflow I've used:

1. Developer edits their code however they want on their IDE (using whatever style they choose)
2. Have Coveralls fail if spotless fails the format check
3. Have a section in CONTRIBUTING to just run `apply spotless` prior to checkin.

I don't think people need to have their style updated as they type ? (i.e. hitting save on their IDE for it to be effective).
Anyways -- my 2cents.

**Comment by yurishkuro** [comment]
Personally I find it very annoying when the auto-format is not incorporated into the dev process and you only find out about it once you submit the PR and it fails much later on simple formatting issues. Because go fmt is pretty much instant, I often find myself hitting Cmd-S just to see formatting applied. Back in the days when I used Java/Scala a lot, we had the same setup for Eclipse across the team.

**Comment by fzakaria** [comment]
Isn't that's the same workflow with checkstyle ?
You only see your failure when you build ?

looks like the checkstyle is for google-format so that should be a an easy way to have people fixup their code. 
Looks like their repo has eclipse/intelliJ plugins or style formats (native)

https://github.com/google/google-java-format 
or
https://github.com/google/styleguide

Anyways -- just bike shedding cause its the day before Thanksgiving.

**Comment by vprithvi** [comment]
I prefer go's autoformatter too.

Spotless defers to google-auto-format for formatting, which doesn't allow much customization. At the time we tried it, it was quite buggy around import formatting, and wouldn't split long lines in aesthetically pleasing ways. 

Further, the output of google-auto-format would often fail the [google checkstyle](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml). 

Another approach is to provide an IDE config which applies the editors code formatter on save.  

See #149 and #53 for related discussion.
