### ISSUE TITLE
old httpcore dependency

### ISSUE THREAD

**Issue by rbtcollins** [jaegertracing/jaeger-client-java#272]
The transitive dependencies through libthrift are getting to be quite old and conflicting with other common APIs - e.g. S3's client lib needs a newer httpcore.

I'm not sure whats involved with upgrading thrift for Jaeger, but perhaps the shaded thrift could be built with newer httpcore or something?

For now we're working around it with 

```
<!-- Jaeger - OpenTracing -->
<dependency>
  <groupId>com.uber.jaeger</groupId>
  <artifactId>jaeger-core</artifactId>
  <version>${jaeger.version}</version>
  <exclusions>
  <!-- Current Jaeger transitively depends on httpcore 4.2.4, we want 4.4.4 -->
    <exclusion>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpcore</artifactId>
    </exclusion>
  </exclusions>
</dependency>
 ```

Note that Java is a second language for me and its possible this is self-inflicted, in which case please close :)

**Comment by jpkrohling** [comment]
@rbtcollins could you check if the PR #326 solves your issue?

**Comment by jpkrohling** [comment]
@rbtcollins , a best practice, in this case, is to specify the HC dependency directly in your project's pom file so that you manage it at that level. It should then override any transitive HC dependency.

Updating libthrift sounds like a good idea anyway, so, we might end up doing that.

**Comment by rbtcollins** [comment]
I'm not sure if we can pickup the new build easily - I'll need to make a timeslice to look into that, so can't check for a bit - sorry.

**Comment by jpkrohling** [comment]
I'm closing this issue, but feel free to reopen in case this can't be worked around.
