### ISSUE TITLE
NPE when getCurrentSpan() called on empty trace context

### ISSUE THREAD

**Issue by debosmit** [jaegertracing/jaeger-client-java#278]
Call to `TracingUtils.getTraceContext().getCurrentSpan()` when span stack is empty results in a NPE.

Method contract in [`TracingUtils.getCurrentSpan()`](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-context/src/main/java/com/uber/jaeger/context/TraceContext.java#L44) or [`ActiveSpanSourceTraceContext .getCurrentSpan()`](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-context/src/main/java/com/uber/jaeger/context/ActiveSpanSourceTraceContext.java#L71) does not specify this.

**Comment by debosmit** [comment]
Might be cleaner to actually check to see if trace context is empty and then return null if nothing is there on the stack

**Comment by yurishkuro** [comment]
it's a bug, should be checking for null before calling getSpan(activeSpan)

**Comment by jackychee** [comment]
Before calling to TracingUtils.getTraceContext().getCurrentSpan(), you shoud call TracingUtils.getTraceContext().isEmpty() first.

**Comment by debosmit** [comment]
@jackychee Well, now I have to, to get around this.

But, your argument is akin to:
```
- I want to peek at the top of the stack
- first check if stack is empty
- then peek
```

That is the expected behavior for when you are trying to `pop()` -- something like an `EmptyStackException`, not `NullPointerException`. Being penalized for peeking on an empty stack is just bad experience!
Moreover, stack trace has very little info, due to the reflection happening to get the current span from `ActiveSpan`.

**Comment by jackychee** [comment]
Hi @debosmit , you are right.  I use jaeger-client-java with version of 0.22.0,   there are not this problem.
