### ISSUE TITLE
question about using shadow dependency in jaeger-b3

### ISSUE THREAD

**Issue by fandan-nyc** [jaegertracing/jaeger-client-java#279]
Hi there
I have a quick question about the jaeger-b3 dependency. I saw that in this line 
https://github.com/jaegertracing/jaeger-client-java/blob/e2c6d1ac081e613c55cc8c935705aeaaa10c2de2/jaeger-b3/build.gradle#L4

**Question:
We have the jaeger-core as the dependency. May I ask the reason why it has to be a shadow ?
Is there a way that we can manage the version of the dependencies ourselves ? 
** 
The following are more details of why we ask 
The reason why I ask is that, the jaeger-core depends on jaeger-thrift which in turn depends on  the old 4.2.X apache httpcore version. 
```
org.apache.httpcomponents:httpcore:4.2.4 -> 4.3.3
\--- org.apache.thrift:libthrift:0.9.2
     \--- com.uber.jaeger:jaeger-thrift:0.21.0
          \--- com.uber.jaeger:jaeger-core:0.21.0
               +--- com.uber.jaeger:jaeger-jaxrs2:0.21.0
               |    \--- runtime
               \--- com.uber.jaeger:jaeger-b3:0.21.0
                    \--- runtime
```

We have some code which needs the 4.3.X apache httpcore version. There is a transitive dependency conflict in our case and there is no way we can override the transitive dependency in gradle. (I could be wrong. If there is a walkaround, please let me know. ) 
we tried 
```
configurations.all {
    resolutionStrategy { 
        force 'org.apache.httpcomponents:httpcore:4.3.3'
    }
}
``` 
but it does not work since the dependency is transitive. 

this is the related ticket we filed sometime ago, in which we have a sample code to reproduce this issue. 
https://github.com/jaegertracing/jaeger-client-java/issues/232

Thanks a lot !

**Comment by felixbarny** [comment]
Some stagemonitor users also reported this issue. What is the reason that `jaeger-b3` depends on `jaeger-core:okhttp381` and not `jaeger-core`?

I guess the quick fix is to remove the dependency to `jaeger-core` so that there is only `jaeger-core:okhttp381` left. But as in this case okhttp is not needed I'd much rather have `jaeger-b3` just depend on the normal `jaeger-core`.

**Comment by vprithvi** [comment]
> What is the reason that jaeger-b3 depends on jaeger-core:okhttp381 and not jaeger-core?

I don't think there is a good reason for it. At the time of writing, I believe there was in incompatibility between the version of `okhttp` bought in by `io.zipkin.brave:brave-http` and `jaeger-core`. I'll have a commit out shortly.

**Comment by objectiser** [comment]
One thing to consider with this issue is that the B3 propagation is now part of the jaeger-core artifact so the jaeger-b3 is only providing backward compatibility support and tests (with their dependency on brave).
