### ISSUE TITLE
Newly build span is not set as active span on tracer

### ISSUE THREAD

**Issue by debosmit** [jaegertracing/jaeger-client-java#288]
When a span is newly created, the tracer does not mark it as the Active Span. Given the recent changes, I think this is the intended direction (correct me if I am wrong). In the present state, thread local (TraceContext) seems to be the only way to retrieve the current span - which seems a bit odd to me, if I already have access to the tracer object.
Might just have been oversight - since change is extremely unobtrusive and simple.

Will update with PR shortly.

**Comment by debosmit** [comment]
Or am I missing something here? Cause `TraceContext.push` does seem to make a span active - but I am not seeing that to be the case in actual usage. Will need further investigation

**Comment by yurishkuro** [comment]
TraceContext is the legacy mechanism that's superseded by the "active span" concept. Its new implementation is supposed to delegate to the active span, so I would expect `push` to make the span active.

**Comment by debosmit** [comment]
I have a suspicion about what is happening, that is surfacing for me in dev/test environment. 
This line 
[`private static TraceContext traceContext = new ActiveSpanSourceTraceContext(GlobalTracer.get());`](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-context/src/main/java/com/uber/jaeger/context/TracingUtils.java#L22)
can cause thread local to use some NoopTracer as the tracer reference. If my understanding is correct, it should have very low/no impact in production environment.
I think its time to make our Uber code not rely on this legacy mechanism any longer, and just use active span concepts.

**Comment by yurishkuro** [comment]
Sure, but the problem it's that the active span concept is being replaced by Scope in the next OT release due at the end of the month. I didn't even want to support active span in the TraceContext, but people jumped on the newer version.

**Comment by debosmit** [comment]
No problem -- let me close this issue out, since you have existing plans, that sound much nicer. Thanks, Yuri :)
