### ISSUE TITLE
ClientFilter has no way to skip/ignore tracing certain client calls

### ISSUE THREAD

**Issue by justfill22** [jaegertracing/jaeger-client-java#289]
The ClientFilter traces every client call made.  It would be very beneficial if certain client calls were ignored / skipped.  

This could be done in a manner similar to how io.opentracing.contrib.web.servlet.filter.TracingFilter (io.opentracing.contrib : opentracing-web-servlet-filter) can be constructed with a skip pattern to allow certain incoming requests to not be traced.

**Comment by yurishkuro** [comment]
@justfill22 any reason why you cannot use instrumentation from opentracing-contrib?  Now that OpenTracing has an API for in-process context propagation there is no need for Jaeger to implement its own instrumentations, we're planning to decommission them in the future.

**Comment by pavolloffay** [comment]
https://github.com/jaegertracing/legacy-client-java/issues/15
