### ISSUE TITLE
Make tracer metrics consistent with Go client

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#298]
https://github.com/jaegertracing/jaeger/issues/572

**Comment by jpkrohling** [comment]
Once #333 (or https://github.com/jpkrohling/jaeger-client-java/tree/333-NormalizedTags) is merged, the branch https://github.com/jpkrohling/jaeger-client-java/tree/298-MetricsConsistentWithGo can be used for this issue here.

**Comment by yurishkuro** [comment]
@jpkrohling I'm confused which PR you want to merge. #333 is adding the reporter to the core package, which we didn't want.

**Comment by jpkrohling** [comment]
I hadn't opened my PR yet, I was waiting for a confirmation that new PRs should be opened, instead of reuse #333. I'm closing #333 and will open a new PRs with the fixes.
