### ISSUE TITLE
When to release 0.22

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#311]
As discussed on the call:
 * Do not release 0.22 based on ActiveSpan, keep it as RC, to discourage adoption
 * Once OpenTracing 0.31 is released, jaeger-0.22 should be based on it

**Comment by daschl** [comment]
0.31 just got released! So one blocker out of the way 👍

**Comment by yurishkuro** [comment]
Support for OpenTracing 0.31 has been released in Jaeger 0.23

**Comment by daschl** [comment]
Awesome!
