### ISSUE TITLE
Support 128bit IDs

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#318]
Meta-issue to track everything that needs to happen

**Comment by jpkrohling** [comment]
How about we follow the RFC 4122 (UUID) for this? Are there good Go libraries for it?

**Comment by yurishkuro** [comment]
@jpkrohling which aspect of that RFC are you referring to, the serialization format or the way the bits are generated?

Incidentally, one of our engineers at Uber told us that we should revisit all the RNG libs we are currently using for ID generation (his recommendation was PCG).

**Comment by jpkrohling** [comment]
Both, but especially the generation.
