### ISSUE TITLE
Unit tests often stall in Travis

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#321]
like this
```
:jaeger-core:license UP-TO-DATE
:jaeger-core:test
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by vprithvi** [comment]
Could we enable debug mode?

https://docs.travis-ci.com/user/running-build-in-debug-mode/

@yurishkuro you might have to do it because they require push access (not sure why)

**Comment by yurishkuro** [comment]
You are assuming it's a travis issue, I think it is much more likely java/gradle issue.

**Comment by vprithvi** [comment]
How do you propose we get visibility into the stalled build?

Are you able to reproduce this locally?

**Comment by yurishkuro** [comment]
I was not able to reproduce locally. Best we can do is to crank verbosity of Gradle logs.

**Comment by jpkrohling** [comment]
This should have been fixed by #341

**Comment by yurishkuro** [comment]
Hm, #340 and #341 just disabled the test rather than fixing it. I think we should close this issue but reopen #340, because disabling is not fixing.

**Comment by jpkrohling** [comment]
Right, sorry, shouldn't have said "fixed". Reopened #340, as a proper fix is still wanted. And as suggested, I'm closing this one.
