### ISSUE TITLE
`testSenderWithAgentDataFromEnv` fails locally

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger-client-java#325]
This [test](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/test/java/com/uber/jaeger/ConfigurationTest.java#L173) fails locally on: 
```
OS X 10.12.6
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode) 
```

It seems that the behavior of `InetSocketAddress` relied on by test differs on my machine. The following test also fails consistently (even with other arbitrary host/ports) for me: 

```java
  @Test
  public void testInetSocket() throws Exception {
    InetSocketAddress inetSocketAddress = new InetSocketAddress("jaeger-agent", 6832);
    assertTrue(inetSocketAddress.isUnresolved());
  }
```

**Comment by yurishkuro** [comment]
I assume the whole purpose of that test was to provide test coverage for exception, it's not a big deal if we remove it, or maybe use powermock to force the exception from the networking layer regardless of the host name.

**Comment by quaff** [comment]
Confirmed, some dns server will hijack unknown hosts.

**Comment by esukram** [comment]
This test doesn't exist anymore in this repo.

I was thinking to fix this one in course of `hacktoberfest`. Can you please clarify?

-Markus

**Comment by yurishkuro** [comment]
indeed. closing.

**Comment by objectiser** [comment]
The test does still exist, and just tried - and it fails locally for me: https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-thrift/src/test/java/io/jaegertracing/thrift/internal/senders/ThriftSenderFactoryTest.java#L46

So @esukram is still available if you wanted to look at it.

**Comment by esukram** [comment]
Ah, different test class then.

Sure, as I am currently in a test spring, I'll have a look.

**Comment by esukram** [comment]
I am pretty sure, this is related to the way network interfaces are listed in Mac OS X. I found a similar problem here: [Bazel - GrpcServerImpl](https://source.bazel.build/bazel/+/6b8c7ca48e9e48a9906c031346dc4a924b7ef559:src/main/java/com/google/devtools/build/lib/server/GrpcServerImpl.java;l=691)

Unless @objectiser is providing more details, as I have no Mac, this is hard to tackle. Most likely needs change in the production area of the code to detect proper NIC.

Thoughts?

**Comment by objectiser** [comment]
I'm not on a mac - let me know if there is any information I can provide to help diagnose.

**Comment by esukram** [comment]
@objectiser thanks for providing your input.

I modified the test files to use Hamcrest, so we see more context in case of test failures:
https://github.com/esukram/jaeger-client-java/blob/9c8b53b0ac8615057ba0c4a516ab3f03a06f64bb/jaeger-thrift/src/test/java/io/jaegertracing/thrift/internal/senders/ThriftSenderFactoryTest.java#L71

Would you mind running the tests based on above mentioned refactorings?

Thanks Markus

**Comment by objectiser** [comment]
@esukram
```
> Task :jaeger-thrift:test

io.jaegertracing.thrift.internal.senders.ThriftSenderFactoryTest > testSenderWithAgentDataFromEnv FAILED
    java.lang.AssertionError: 
    Expected: is type < io.jaegertracing.internal.senders.NoopSender
         but: "io.jaegertracing.thrift.internal.senders.UdpSender"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at io.jaegertracing.thrift.internal.senders.ThriftSenderFactoryTest.testSenderWithAgentDataFromEnv(ThriftSenderFactoryTest.java:71)
```

**Comment by aschugunov** [comment]
Hello,
it seems this problem is no longer reproducible
