### ISSUE TITLE
Enable Micrometer StatsReporter via env var

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#339]
As suggested by @objectiser, the Micrometer StatsReporter could be configured via an env var. This should probably be done after #338

**Comment by yurishkuro** [comment]
Wouldn't it create a dependency from core module?

**Comment by jpkrohling** [comment]
Not necessarily. If we use a service loader, the core module can just try to load the provider from the classpath.

**Comment by jpkrohling** [comment]
The latest commit on this branch has an example on how this would look like:

https://github.com/jpkrohling/jaeger-client-java/tree/339-EnableMicrometerViaEnvVar

It's based on another commit which has not been merged yet, so, I'll open a PR only once that PR gets merged.
