### ISSUE TITLE
Test `testCloseWhenQueueFull` causes Travis instability

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#340]
The test `testCloseWhenQueueFull` triggers, possibly, a race condition. On Travis, this seems to be relatively frequent, but I couldn't get this to happen even a single time on my machine.

I suggest disabling this test until the root cause is found, as this is affecting every PR.

Job executed with the test:
https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/340904551

Job executed without the test: 
https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/340913133

When it fails, this is the test order that is executed:

```
com.uber.jaeger.reporters.RemoteReporterTest > testAppendWhenQueueFull PASSED
com.uber.jaeger.reporters.RemoteReporterTest > testReportDoesntThrowWhenQueueFull PASSED
com.uber.jaeger.reporters.RemoteReporterTest > testRemoteReporterReport PASSED
```

And this is the test order on a successful build (with the test removed):

```
com.uber.jaeger.reporters.RemoteReporterTest > testAppendWhenQueueFull PASSED
com.uber.jaeger.reporters.RemoteReporterTest > testReportDoesntThrowWhenQueueFull PASSED
com.uber.jaeger.reporters.RemoteReporterTest > testRemoteReporterReport PASSED
com.uber.jaeger.reporters.RemoteReporterTest > testFlushWhenQueueFull PASSED
com.uber.jaeger.reporters.RemoteReporterTest > testRemoteReporterFlushesOnClose PASSED
com.uber.jaeger.reporters.RemoteReporterTest > testRemoteReporterFlushTimerThread PASSED
com.uber.jaeger.reporters.RemoteReporterTest > testFlushUpdatesQueueLength PASSED
```

This order is similar to the order seen when the tests are executed from within an IDE:
![image](https://user-images.githubusercontent.com/13387/36151484-a54bda9a-10c7-11e8-8768-48feef55caf4.png)

**Comment by jpkrohling** [comment]
Funny, this should have been closed when #341 got merged.

**Comment by yurishkuro** [comment]
it didn't have the right comment

**Comment by jpkrohling** [comment]
I'm closing this, as I haven't seen this for a while... Please, reopen if this ever happens again.
