### ISSUE TITLE
Intermittent failure for UdpSenderTest#testFlushSendsSpan

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#342]
The test `UdpSenderTest#testFlushSendsSpan` is intermittently failing on Travis. Unfortunately, I can't find any more on Travis where the assertion fails, so I can't dig deeper into the issue. Will log more details here once it happens again.

**Comment by milenkovicm** [comment]
can it be related to #328 ? actually, test does not cover `send()` method at all

**Comment by chandresh-pancholi** [comment]
Still happening?

**Comment by jpkrohling** [comment]
I haven't seen failures about this recently, so, something might have fixed this. How about you,  @pavolloffay?
