### ISSUE TITLE
Using jaeger-client with a provided CA bundle

### ISSUE THREAD

**Issue by mojsha** [jaegertracing/jaeger-client-java#345]
We have a Jaeger instance exposed using OpenShift secured routes. We have "internal" and "external" routes. 

For the "internal" routes, we are using Service Serving Certificates (https://docs.openshift.org/latest/dev_guide/secrets.html#service-serving-certificate-secrets) which have the CA certs injected into the running containers at /run/secrets/kubernetes.io/serviceaccount/service-ca.crt. 

For the external routes, we use another certificate issuer. 

The main request here is the ability to specify a CA-bundle and have the jaeger-client use that to access the collector. 

The ideal would be that it would be able to both handle the injected CA cert format as well as JKS (since the "external" clients, meaning applications hosted outside of OpenShift, wouldn't have access to the container-injected CA certs and use the certificates from the other issuer in the form of a traditional JKS). 

@jpkrohling

**Comment by mojsha** [comment]
@jpkrohling Any time if you can get this prioritized/scoped somehow?

**Comment by jpkrohling** [comment]
I'll try to get a PR for it this week. If you have a draft solution, feel free to submit a PR as well :)

**Comment by mojsha** [comment]
@jpkrohling Much appreciated.  I don't have a solution draft unfortunately, but I just wanted to mention a small point:

In our OpenShift instance we have multiple (two to be precise) certificates in /run/secrets/kubernetes.io/serviceaccount/service-ca.crt and this happened due to an upgrade at some point where OpenShift changed the issuer and the new one was added on top of the old one. 

Could you make it support the /run/secrets/kubernetes.io/serviceaccount/service-ca.crt having multiple certificates?

They look like this:

```
-----BEGIN CERTIFICATE-----
(...) Old 
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
(...) New
-----END CERTIFICATE-----
```

**Comment by jpkrohling** [comment]
I just did a quick look at what we have and what would be needed. As we are using OkHttp, we'd need something like this:

https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java

@pavolloffay can correct me if I'm wrong, but there's currently no way to specify a custom `OkHttpClient` (or even a custom `Sender`), so, we have to change the configuration builders to either:

* add an option to specify the JKS and/or a CA bundle and let Jaeger internals to deal with the OkHttp client (my preference for this specific use case)

or 

* add an option to specify the OkHttpClient to use (or even just a `Sender`, as the HttpSender has a builder that accepts `OkHttpClient` and let the consumer code to handle the JKS/cert bundle configuration (which is better for cases we can't predict yet)

cc @objectiser , @vprithvi , @pavolloffay

**Comment by pavolloffay** [comment]
`Tracer.Builder()` accepts `Reporter` where you can pass any sender implementation. 

There is `Configuration.SenderConfiguration(Sender)` but it was deprecated. The purpose of configuration is to keep only primitive types and create itself from env/system props. It shouldn't be duplicating `Tracer.Builder()` which holds instances of tracer components.

**Comment by objectiser** [comment]
It should probably be implemented in the same way as the auth properties which can be captured in the configuration and passed into the `HttpSender` (builder) and internally used to config OkHttp.

**Comment by mojsha** [comment]
@jpkrohling Any conclusions based on the suggestions above.. ?

**Comment by jpkrohling** [comment]
@mojsha not yet, sorry, but I think @objectiser's suggestion is how we'll end up implementing.

**Comment by IamMujuziMoses** [comment]
Hello am Moses, am an Outreachy applicant and am going to try this issue out and i'll need help some times.

**Comment by IamMujuziMoses** [comment]
am requesting to be assigned to this issue

**Comment by jpkrohling** [comment]
@IamMujuziMoses it's yours!
