### ISSUE TITLE
Document Jaeger java client metrics

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#350]
Document the metrics exposed via Prometheus from the internal Jaeger Java client.

**Comment by jpkrohling** [comment]
This is done here: https://github.com/jpkrohling/jaeger-client-java/tree/350-DocumentMicrometerIntegration

It's based on #349, so, once that is merged, I'll open a PR for this.

**Comment by jpkrohling** [comment]
@kevinearls, would you be able to check the instructions?

**Comment by kevinearls** [comment]
@jpkrohling I'll take a look shortly
