### ISSUE TITLE
B3TextMapCodec & incorrect input.

### ISSUE THREAD

**Issue by tmszdmsk** [jaegertracing/jaeger-client-java#354]
How should codecs, in general, behave when incorrect (or even malicious) input is provided? 

For example: `B3TextMapCodec` fails with an exception when incorrect header values are used.

Shouldn't it be handled gracefully?

Here is example PR with tests: https://github.com/jaegertracing/jaeger-client-java/pull/353

**Comment by tmszdmsk** [comment]
processing power consumption isn't my concern at all. The question I wanted to ask is:
Should instrumentation code (i.e. opentracing libs) make your application e.g. fail a request in case of some bug/incorrect input. I assume the answer is no.

In that case who should be responsible for catching all the exceptions? filters/decorators or like in this case `B3TextMapCodec` itself? Is there any guide or best practice for such situations?

**Comment by pavolloffay** [comment]
> processing power consumption isn't my concern at all. The question I wanted to ask is:
Should instrumentation code (i.e. opentracing libs) make your application e.g. fail a request in case of some bug/incorrect input. I assume the answer is no.

Probably no, but it depends on the implementation. For example I think that `extract` in Brave (Zipkin) also fails on this exception.

**Comment by adriancole** [comment]
If brave fails a production request (might well do that) it is a bug.

**Comment by pavolloffay** [comment]
It seems that it can throw `NumberFormatException` or maybe I am missing something. https://github.com/pavolloffay/brave/blob/08ee906077a8ec662c26aab1909c0e6265154839/brave/src/main/java/brave/propagation/B3Propagation.java#L139-L143

**Comment by adriancole** [comment]
yep. fyi I will plan to fix this in brave by making a special parser which
doesn't allocate an exception. When log debug is not on, it uses that.

basically we parse into an object returning boolean false if parsing was
invalid, skipping out on false.

something like that.. not sure yet. At any rate this is a bug worth fixing

**Comment by pavolloffay** [comment]
Good to know that it is not intentional :). We should fix it here too, might be good also to look at jaeger codec whether it fails on corrupted context.

**Comment by adriancole** [comment]
>
> Good to know that it is not intentional :). We should fix it here too,
> might be good also to look at jaeger codec whether it fails on corrupted
> context.
>
also look out for baggage or debug validation, too. good luck!

**Comment by tmszdmsk** [comment]
I didn't manage to leave comments on PR before merging, I will copy the most important for me part:
> It covers test cases I've prepared but I am still concerned about bugs we didn't detect yet. I would sleep better if there would be some try-catch-all block that fallbacks to "no context" in case of failure.

**Comment by jpkrohling** [comment]
@kevinearls could you add to your test plan a case for this? Basically, we want to make sure we don't throw any exceptions, especially based on malformed input from users/adversaries.

**Comment by jpkrohling** [comment]
> if there would be some try-catch-all block that fallbacks to "no context" in case of failure

For the propagation header parsing? Or a more generic one, acting on a higher level?
