### ISSUE TITLE
Add @jpkrohling as a maintainer to jaeger-client-java

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-client-java#361]
Juca (@jpkrohling) works with us on tracing at Red Hat, he has a broad knowledge in Java. He has done several contributions to this client. I propose to add him as maintainer.

@yurishkuro  @vprithvi @black-adder please vote

**Comment by black-adder** [comment]
+1

**Comment by vprithvi** [comment]
+1

**Comment by yurishkuro** [comment]
+1

**Comment by yurishkuro** [comment]
Looks like he's already a maintainer

![image](https://user-images.githubusercontent.com/3523016/36810627-40b6db56-1c99-11e8-9d7a-cfb94e9edfb2.png)

**Comment by pavolloffay** [comment]
@jpkrohling mentioned that he cannot merge PRs, therefore, I raised this. Oh I remember that he was probably added when doing work around release.

Thanks for votes I will close this.

I am going to add a discussion about adding codeowners to the agenda.

**Comment by jpkrohling** [comment]
Sorry for reopening this, but I can't seem to be able to merge from the command line: https://github.com/jaegertracing/jaeger-client-java/pull/365#issuecomment-371067809 .

**Comment by yurishkuro** [comment]
how about now?

![image](https://user-images.githubusercontent.com/3523016/37101274-26edf5c4-21f3-11e8-85a2-c35d577384de.png)

**Comment by jpkrohling** [comment]
Looks like I can now :)
