### ISSUE TITLE
Flaky test affecting code coverage

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#380]
PR #379 was a change in the README but showed a drop in [code coverage][1] due to exception clauses not being hit:

![image](https://user-images.githubusercontent.com/3523016/38470532-2551475e-3b32-11e8-8d4a-930161414710.png)

[1]: https://codecov.io/gh/jaegertracing/jaeger-client-java/compare/6d822c3471896c7c3c4ced14c969b51bacaf3994...c6a597fb5bd1da9afbb2f8f85b3dd389d21d8bea/changes

**Comment by piyushmor** [comment]
Hi, just raised a PR for the first coverage issue!

**Comment by adnxn** [comment]
#658 and #692 addresses the two coverage gaps. i think we're good to close this issue.

**Comment by yurishkuro** [comment]
Thanks!
