### ISSUE TITLE
Zipkin v2 JSON Sender

### ISSUE THREAD

**Issue by keitwb** [jaegertracing/jaeger-client-java#383]
I would like to be able to send spans to Zipkin's v2 JSON API. 
 
I've started on a new sender in the `com.uber.jaeger.senders.zipkin` package which I intend to contribute, but wanted to make sure I didn't overlook anything that already enables this or get any feedback on how I should do it.  Unfortunately Zipkin 1/2 use a different interface for zipkin Sender so I will have to either have some duplicated code or write adapters to make them interchangeable.

**Comment by adriancole** [comment]
The zipkin v2 reporter can also send in v1 format. Other libraries switch
to this for both variants

https://github.com/openzipkin/zipkin-reporter-java/blob/master/README.md#legacy-encoding
