### ISSUE TITLE
Revisit Configuration API

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-client-java#394]
There are a couple of inconsistencies in the configuration API.

The API should comply with this
* after creating the configuration from env it should be possible to override any value via programmatic API
* Configurations can be created via programmatic API - via constructor not only via `fromEnv`

* programmatic api does not allow to override set service name
* codec configuration can be created only via `.fromEnv()`
* most of the configurations provide getters but not for all properties

**Comment by aaronkorver** [comment]
I just ran into the codec thing yesterday.  I was wanting to define my own codec and realized that, although the codec has a Builder, it seems that if I am using `fromEnv()` I don't have options to override this.  Had to fall back to the adapter pattern and TextMap

**Comment by pavolloffay** [comment]
I will submit a PR shortly. 

@aaronkorver more suggestions are appreciated.

**Comment by pavolloffay** [comment]
@aaronkorver if you want to look I have created https://github.com/jaegertracing/jaeger-client-java/pull/411
