### ISSUE TITLE
HttpSender errors are not logged

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger-client-java#406]
If the http sender fails due to unauthorized access, we throw an exception: https://github.com/jaegertracing/jaeger-client-java/blob/2fa8f3ed17e88114f6cd7114747ed298933dabd8/jaeger-core/src/main/java/io/jaegertracing/senders/HttpSender.java#L120

However, this exception doesn't seem to be logged anywhere although we do emit a metric:
https://github.com/jaegertracing/jaeger-client-java/blob/2fa8f3ed17e88114f6cd7114747ed298933dabd8/jaeger-core/src/main/java/io/jaegertracing/reporters/RemoteReporter.java#L184

Either making the metric more explicit or logging the error will be apt here.

**Comment by chandresh-pancholi** [comment]
Let me know what log statement you want me to add. 
I will include in the HttpSender.java

**Comment by chandresh-pancholi** [comment]
@black-adder  Below code is throwing SenderException. It is not specific to unauthorized access though.
`

      String exceptionMessage = String.format("Could not send %d spans, response %d: %s",
          spans.size(), response.code(), responseBody);
      throw new SenderException(exceptionMessage, null, spans.size());

`

**Comment by black-adder** [comment]
That's fine, we should log any exception. In line https://github.com/jaegertracing/jaeger-client-java/blob/2fa8f3ed17e88114f6cd7114747ed298933dabd8/jaeger-core/src/main/java/io/jaegertracing/reporters/RemoteReporter.java#L184 once we get the exception, we should log it, `log.error("QueueProcessor sender error:", e);`

**Comment by chandresh-pancholi** [comment]
Is it right to log complete stack trace? Just the log message won't work?

**Comment by jpkrohling** [comment]
Do pass the exception to `log.error`. The end user can configure the logger to suppress the stack trace if needed. Also, it would probably better to wait for #449 before doing this one, otherwise you might get a merge conflict.

**Comment by chandresh-pancholi** [comment]
@jpkrohling  Sure, I will wait for #449 to close.

**Comment by esukram** [comment]
Hi @jpkrohling 
As there has been some work already, do still qualify that to be done?

**Comment by jpkrohling** [comment]
@chandresh-pancholi, are you still interested in working on this one? 

@esukram feel free to take it in a couple of days, in case @chandresh-pancholi isn't available or isn't interested. You might even be able to get two issues in one, as #653 is somewhat related to this one here.

**Comment by chandresh-pancholi** [comment]
I will be picking it up.

**Comment by chandresh-pancholi** [comment]
Go ahead sir.

**Comment by chandresh-pancholi** [comment]
@esukram has made the changes already. logging the error in RemoteReporter. 
It's better to close this issue as well.

**Comment by yurishkuro** [comment]
Fixed by #662
