### ISSUE TITLE
Split the notion of a "sender" into transport and encoder

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#407]
We're currently using inheritance in the senders, but composition would be a better pattern since encoding a batch is orthogonal to how the batch is sent.

One caveat is that UDP transport uses different batching strategy based on the total packet size, whereas other transports can be more relaxed on the total size and instead be based on the number of spans, which is a lot simpler to implement and actually solves the problem with extra-large spans.

**Comment by adnxn** [comment]
id like to dig into this and was discussing some details with @jpkrohling.

so it looks like `ThriftSender` and `ThriftSenderBase` are responsible for most of the "encoder" work and the `HttpSender`/`UdpSender` handle the "transport" responsibilities.

when we talk about using composition as a pattern - do we see something like a `ThriftSender` (and potentially other senders) that hold a `ThriftEncoder` and a `HttpTransport`/`UdpTransport` depending on the transport required? Where encoders can handle the Thrift conversion and the transports handle the communication with the backend or agent?

this is roughly my high level understanding of what we're trying to do here. am I missing something obvious? or overlooking things wrt existing design?

**Comment by jpkrohling** [comment]
That's also how I think it should work.
