### ISSUE TITLE
Do not deprecate Tracer.Builder(name, reporter, sampler)

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-client-java#413]
We have deprecated `Tracer.Builder(name, reporter, sampler)`, but I think that constructor is useful and for the folks who would like to instantiated the tracer in a one-liner.

Related to #395 

cc @yurishkuro @jpkrohling @black-adder @vprithvi

**Comment by jpkrohling** [comment]
I don't have a strong opinion on this, although I prefer we'd have one way of doing things. In the end, `new Tracer.Builder(serviceName, reporter, sampler)` isn't _that_ different from `Tracer.Builder(serviceName).withReporter(reporter).withSampler(sampler)`

**Comment by pavolloffay** [comment]
I agree.., the main reason I have opened this is that we use that constructor internally a lot.

**Comment by pavolloffay** [comment]
The constructor was removed in #414
