### ISSUE TITLE
How can I send zipkin/compact data to jeager-agent port 5775 via UDP?

### ISSUE THREAD

**Issue by ryphnyuan** [jaegertracing/jaeger-client-java#423]
For jeager-agent, the port 5775 is described as to receive zipkin/compact data via UDP. 
And for zipkin, its data are always sent to the collectors with endpoint address like "http://localhost:9411". 
I can send zipkin data to jeager-collector using http://localhost:9411 too.
But how can I send zipkin data to jeager-agent port 5775 via UDP?

**Comment by yurishkuro** [comment]
It's a legacy port. Some Jaeger clients used to send data in zipkin format. They don't do that anymore.

**Comment by ryphnyuan** [comment]
All right. Thanks for that.
