### ISSUE TITLE
Metrics Factory Service Provider Interface

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#436]
As a follow-up to #433, we need to assess whether it makes sense to implement a fully featured SPI loading mechanism for the metrics factory. While it's not much code, it's still code that will be executed and need to be maintained, documented and tested.

As such, we'll leave this issue open for a couple of months, to see if it's something the community needs/wants. If you want/need this feature, make sure to add your feedback in form of "+1" or "-1" to this issue.

**Comment by jpkrohling** [comment]
cc @pavolloffay

**Comment by pavolloffay** [comment]
Bindings to service provider should be in a separate package `spi` and ideally contain separate classes to core interfaces  - e.g. 
```java
public class MetricsFactoryProvider {
   io.jaegertracing.MetcisFactory create();
}
`
see https://stackoverflow.com/questions/2954372/difference-between-spi-and-api/2956981#2956981

`spi` package directly indicates what it is and how it is used makes it easier to understand how the software works.
