### ISSUE TITLE
Release 0.29.0

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-client-java#437]
When shall we cut 0.29.0? 

At the moment it would include https://github.com/jaegertracing/jaeger-client-java/pull/431 and https://github.com/jaegertracing/jaeger-client-java/pull/433

I am fine with cutting new release so people can adapt quickly.

**Comment by jpkrohling** [comment]
If you need it somewhere, sure. But note that it would probably be a good idea to have a release right before #396 and one after.

**Comment by pavolloffay** [comment]
I think it's better to release often we have something to ship. 

Once #438 is in I would like to release.
