### ISSUE TITLE
Should we use Sonarcloud for code quality analysis?

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger-client-java#439]
Sonarcloud provides continuous code quality analysis and the ability to look at historical trends. 

I ran a build locally and uploaded it to show what this looks like (note that the thrift module wasn't excluded so the numbers are a bit off)

https://sonarcloud.io/project/issues?id=io.jaegertracing%3Ajaeger-client&moduleUuids=AWPWXE7K4427HkKVyzHU&resolved=false

Do we think that having this analysis adds value?

**Comment by black-adder** [comment]
Looks like a great tool to have. Could be a good source of beginner tasks for people who want to get their hallux wet in open source.

**Comment by objectiser** [comment]
This [one](https://sonarcloud.io/project/issues?id=io.jaegertracing%3Ajaeger-client&moduleUuids=AWPWXE7K4427HkKVyzHU&open=AWPWXFDX4427HkKVyzQ0&resolved=false) is interesting, given @jpkrohling  recent PR to rename the jaegertracing Span.

The client needs to be Java 1.6 currently (how long??) - so is it possible to set this tool to only show issues relevant to that version (e.g. not show diamond operator issues)?

If so, then would be good to use.

**Comment by pavolloffay** [comment]
Abit off topic but I am using Sonarlint plugin in idea https://plugins.jetbrains.com/plugin/7973-sonarlint. But it would be better to have it as a standard part during CI.

**Comment by jpkrohling** [comment]
I'm a bit outdated: is it possible to integrate it with GitHub directly? If so, I think it's a great idea.

**Comment by jpkrohling** [comment]
Replying to myself: 

> SonarCloud currently does not trigger analyses automatically - this feature will come in a near future. Currently, it's up to you to launch them inside your existing CI scripts.

Source: https://sonarcloud.io/documentation/analyze-a-project

**Comment by jpkrohling** [comment]
Just to document it somewhere: to get a local run done, the following change is needed:

```diff
diff --git a/build.gradle b/build.gradle
index a9aa00e..13c3b42 100644
--- a/build.gradle
+++ b/build.gradle
@@ -13,6 +13,7 @@ plugins {
     id 'ru.vyarus.animalsniffer' version '1.4.3'
     id 'io.codearte.nexus-staging' version '0.11.0'
     id 'com.github.ben-manes.versions' version '0.17.0'
+    id "org.sonarqube" version "2.6"
 }
 
 ext.developmentVersion = getProperty('developmentVersion','0.29.1-SNAPSHOT')
diff --git a/jaeger-thrift/build.gradle b/jaeger-thrift/build.gradle
index 06cb77f..e957312 100644
--- a/jaeger-thrift/build.gradle
+++ b/jaeger-thrift/build.gradle
@@ -75,3 +75,9 @@ artifacts {
     }
     tests testJar
 }
+
+sonarqube {
+    properties {
+        property "sonar.exclusions", "**/gen-java/**"
+    }
+}
\ No newline at end of file
```

Then, register with https://sonarcloud.io, go to `Analyze a new project` and follow the instructions. The actual command to execute has to include `-Dsonar.projectKey=...` , like:

```
./gradlew sonarqube
   -Dsonar.organization=jpkrohling-github
   -Dsonar.host.url=https://sonarcloud.io
   -Dsonar.login=...
   -Dsonar.projectKey=jaeger-client-java-jpkroehling
```
