### ISSUE TITLE
Isn't possible to override the Reporter or inject/extract using com.uber.jaeger.Configuration

### ISSUE THREAD

**Issue by adriancole** [jaegertracing/jaeger-client-java#44]
I'm having to do a lot of hacking to make it possible to use an alternate Reporter (or at least an alternate Sender) with the current com.uber.jaeger.Configuration.

**Comment by adriancole** [comment]
good news is that with a workaround to #45 and the below, I've got tracing working with jaeger receiving a request and sending to a non-jaeger zipkin service.

```
final class ZipkinConfiguration extends Configuration {
  private final String serviceName;
  io.opentracing.Tracer tracer;

  public ZipkinConfiguration(String serviceName) {
    super(serviceName, false, null, null);
    this.serviceName = serviceName;
  }

  @Override public io.opentracing.Tracer getTracer() {
    if (this.tracer != null) {
      return this.tracer;
    } else {
      StatsFactoryImpl statsFactory = new StatsFactoryImpl(new NullStatsReporter());
      Metrics metrics = new Metrics(statsFactory);

      RemoteReporter reporter = new RemoteReporter(
          ZipkinSender.create("http://localhost:9411/api/v1/spans"),
          1000,
          100,
          metrics
      );
      B3TextMapCodec b3Codec = new B3TextMapCodec();
      Sampler sampler = new ConstSampler(true);
      return this.tracer = new Tracer.Builder(serviceName, reporter, sampler)
          .registerInjector(Format.Builtin.HTTP_HEADERS, b3Codec)
          .registerExtractor(Format.Builtin.HTTP_HEADERS, b3Codec)
          .build();
    }
  }
}
```

**Comment by yurishkuro** [comment]
The subclassing solution doesn't look too bad. We could open a couple interceptors in the main config class for creating a sender and adding stuff to the Builder before calling `build()`. The alternative is a normal DI route.

**Comment by adriancole** [comment]
DI route works if you can access constructors etc, so as long as the trace filters can accept objects like trace directly, that could indeed work.

**Comment by jpkrohling** [comment]
Is this still a problem? If so, this could be done as part of #346

**Comment by pavolloffay** [comment]
Done in #346
