### ISSUE TITLE
InMemoryMetricsFactory.createGauge considers amount as delta

### ISSUE THREAD

**Issue by mdouaihy** [jaegertracing/jaeger-client-java#459]
Hello,

I am using the Java Jaeger client in my project. I stumbled upon `InMemoryMetricsFactory` and noticed a bug in the `createGauge` method.

In fact `createGauge` considers the amount as a delta whereas it's an absolute amount.

**Current Behavior**
```
return new Gauge() {
      @Override
      public void update(long amount) {
        value.addAndGet(amount);
      }
    };
```
**Suggested Behavior**
```
return new Gauge() {
      @Override
      public void update(long amount) {
        value.getAndSet(amount);
      }
    };
```

**Comment by jpkrohling** [comment]
Would you like to contribute a fix? If you need help in submitting your first contribution, let me know.

**Comment by mdouaihy** [comment]
Pull request #463 was added for that purpose.
