### ISSUE TITLE
Log a warning in case JaegerTracer.SpanBuilder#addReference(String, SpanContext) isn't a JaegerSpanContext

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#466]
## Requirement - what kind of business use case are you trying to solve?
- As seen on https://github.com/jaegertracing/jaeger-client-java/pull/454#discussion_r198192186 , we need to add a warning log entry before silently returning on the method `JaegerTracer.SpanBuilder#addReference(String, SpanContext)`, in case `SpanContext` isn't a `JaegerSpanContext`.

**Comment by chandresh-pancholi** [comment]
Currently, SpanContext is not a JaegerSpanContext.

**Comment by jpkrohling** [comment]
There wasn't, but now there is :)

**Comment by smieras** [comment]
@jpkrohling 
Wanted to pick this up as a good first issue, but the addReference method already has:
`log.warn("Expected to have a JaegerSpanContext but got " + reference.getClass().getName());`
Perhaps close the issue?

**Comment by jpkrohling** [comment]
Thanks! We have other good first issues, in case you are interested :-)
