### ISSUE TITLE
Does it support PlayFramework by using scala ?

### ISSUE THREAD

**Issue by JaryZhen** [jaegertracing/jaeger-client-java#472]
Or if there is some link about it?

**Comment by jpkrohling** [comment]
Good question. I don't think we have positive feedback about it yet, so, if you have experience with Play! and want to share your findings, we would be really grateful!

**Comment by JaryZhen** [comment]
I‘m new user for Tracing  System such as Zipkin, Jeager, Skywalking. I'd like to try.

**Comment by jpkrohling** [comment]
That would be awesome! You can learn more about OpenTracing and Jaeger by following this tutorial: 

https://github.com/yurishkuro/opentracing-tutorial

Or this Katacoda scenario, based on the tutorial above: https://www.katacoda.com/courses/opentracing

**Comment by JaryZhen** [comment]
That's very helpful, thanks a lot  , I'll let you know if there's any progress.

**Comment by yurishkuro** [comment]
These talk about OT with Play:
* https://developer.lightbend.com/docs/cinnamon/current/extensions/opentracing.html
* https://github.com/lucidsoftware/opentracing-playframework
