### ISSUE TITLE
Define public constants

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#473]
## Requirement - what kind of business use case are you trying to solve?

- While working on #470, some constants were found that would probably belong to the public API, like:
  - https://github.com/jaegertracing/jaeger-client-java/pull/470#discussion_r199954859
  - @pavolloffay mentioned privately also the constants that define a sampler name, like `ConstSampler.TYPE`.

## Any open questions to address

Which constants should be part of this new constants class? Candidates:
- [ ] ConstSampler.TYPE
- [ ] GuaranteedThroughputSampler.TYPE
- [ ] ProbabilisticSampler.TYPE
- [ ] RateLimitingSampler.TYPE
- [ ] RemoteControlledSampler.TYPE
- [ ] Constants.SAMPLER_TYPE_TAG_KEY
- [ ] Constants.SAMPLER_PARAM_TAG_KEY
- [ ] Constants.DEBUG_ID_HEADER_KEY
- [ ] Constants.TRACER_IP_TAG_KEY

**Comment by quaff** [comment]
DEBUG_ID_HEADER_KEY should be public

**Comment by jpkrohling** [comment]
> DEBUG_ID_HEADER_KEY should be public

An use case and/or reasoning would be appreciated ;-)

**Comment by quaff** [comment]
I have implemented TextMap for extraction from HttpServletRequest, I need ensure DEBUG_ID_HEADER_KEY can be extracted from header or request parameter.
```
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import io.jaegertracing.internal.Constants;
import io.opentracing.propagation.TextMap;

public final class HttpServletRequestTextMap implements TextMap {

	public final static String SPAN_CONTEXT_KEY = "x-trace-id";

	public final static String BAGGAG_EPREFIX = "x-trace-ctx-";

	private final Map<String, String> map;

	public HttpServletRequestTextMap(HttpServletRequest request) {
		map = new HashMap<>();
		Enumeration<String> en = request.getHeaderNames();
		while (en.hasMoreElements()) {
			String name = en.nextElement();
			String lowerCaseName = name.toLowerCase(); // Jetty return X-Trace-Id
			if (lowerCaseName.equals(SPAN_CONTEXT_KEY) || lowerCaseName.startsWith(BAGGAG_EPREFIX)
					|| lowerCaseName.equals(Constants.DEBUG_ID_HEADER_KEY))
				map.put(name, request.getHeader(name));
		}
		String debugId = request.getParameter(Constants.DEBUG_ID_HEADER_KEY);
		if (debugId != null)
			map.put(Constants.DEBUG_ID_HEADER_KEY, debugId);
	}

	public boolean isEmpty() {
		return map.isEmpty();
	}

	public Iterator<Map.Entry<String, String>> iterator() {
		return map.entrySet().iterator();
	}

	public void put(String key, String value) {
		throw new UnsupportedOperationException("Should only be used with Tracer.extract()");
	}
}
```

**Comment by quaff** [comment]
TRACER_IP_TAG_KEY and TRACER_HOSTNAME_TAG_KEY should be public to let application pass in accurate tag value.
