### ISSUE TITLE
Misleading documention for jaeger-client in maven.

### ISSUE THREAD

**Issue by paulseddon** [jaegertracing/jaeger-client-java#484]
## Requirement - what kind of business use case are you trying to solve?

Misleading documentation regarding maven artefact.

## Problem - what in Jaeger blocks you from solving the requirement?

Readme indicates that jaeger client is in maven (0.30.0) but cannot be found in maven central.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Either add artefact to maven repo or change document to refer to correct artefact to use for configuring client.

**Comment by jpkrohling** [comment]
I'm truly sorry, you caught this module on the next day we created it :-) This is a new module and it will be there starting from v0.30.1.

If you still can't find it there after we release v0.30.1 (we should do it today or tomorrow), feel free to reopen this.
