### ISSUE TITLE
jaeger-thrift JAR has bundled dependencies, breaking builds

### ISSUE THREAD

**Issue by mdvorak** [jaegertracing/jaeger-client-java#494]
If you look into 0.30.x JARs of jaeger-thrift (see here http://central.maven.org/maven2/io/jaegertracing/jaeger-thrift/0.30.2/jaeger-thrift-0.30.2.jar), you will see a lot of stuff that does not belong there. I guess this is done by `com.github.johnrengelman.shadow` gradle plugin.

Bundling dependencies in this jar breaks dependency management (it is transitive dependency of jaeger-client), and even java compiler - project, compiled with JDK 10, breaks with 0.30.2 version, because it uses old lombok - which i don't reference and don't have on my drive.

I'm using Maven 3.5.3, Spring Boot 2.0.3.RELEASE as parent, io.opentracing.contrib:opentracing-spring-jaeger-starter:0.2.0, which uses jaeger-client:0.30.2.

**Comment by mdvorak** [comment]
@jpkrohling Sure, but if you open the JAR, you will see the problem - lombok is not repackaged into jaeger, but left at root, also with few other classes, e.g. slf4j (probably its dependency). Even its AUTHORS file is there..
I guess this is shadow plugin bug actually, but someone will have to look into that more closely before making that conclusion.

**Comment by mdvorak** [comment]
This is pure sample from Spring Boot Initializr, with just added single jaeger-thrift dependency.
[jaeger494.zip](https://github.com/jaegertracing/jaeger-client-java/files/2202131/jaeger494.zip)
Run `./mvnw compile -e` with `JAVA_HOME` pointing to Oracle JDK 10.0.1. 
You will see `java.lang.ClassNotFoundException: com.sun.tools.javac.code.TypeTags` exception, with lombok in stack trace.

**Comment by jpkrohling** [comment]
Got it, there are indeed more things in the shadowed JAR than needed. I'll add this to my queue, but feel free to contribute a fix if you want this done "soon" (I might have time only in a week or so).

**Comment by mdvorak** [comment]
Ok, problem is here:
https://github.com/jaegertracing/jaeger-client-java/blob/a16cd8b8fe669fefcff4abcb46abb3174c06ac8f/build.gradle#L145
There are compileOnly dependencies for all subprojects, while
https://github.com/jaegertracing/jaeger-client-java/blob/a16cd8b8fe669fefcff4abcb46abb3174c06ac8f/jaeger-thrift/build.gradle#L60
references everything in scope compileOnly for relocation. Lombok is not there (as well as animalsniffer), so there is the problem.

Solution is probably not to include these at all, because they are really not needed. However, I don't use Gradle, I'm not sure best about approach.

Easiest to exclude these, something like this:
http://imperceptiblethoughts.com/shadow/#filtering_dependencies
```
shadowJar {
    baseName = 'jaeger-thrift'
    relocate 'com.google.gson'  , 'jaeger.com.google.gson'
    relocate 'com.twitter'      , 'jaeger.com.twitter'
    relocate 'okhttp'           , 'jaeger.okhttp'
    relocate 'okio'             , 'jaeger.okio'
    relocate 'org.apache'       , 'jaeger.org.apache'
    classifier null
    configurations = [project.configurations.compileOnly]
    exclude(dependency('org.projectlombok:lombok'))
}
```
Not sure whether dependency works without version. Also, all (even transitive) dependencies have to be excluded.

Another option would be to change scope of lombok, or here listed configurations.

**Comment by jpkrohling** [comment]
How about something like this:

```diff
diff --git a/jaeger-crossdock/build.gradle b/jaeger-crossdock/build.gradle
index 6dc922a..3bcb77e 100644
--- a/jaeger-crossdock/build.gradle
+++ b/jaeger-crossdock/build.gradle
@@ -1,6 +1,5 @@
 apply plugin: 'com.github.johnrengelman.shadow'
 
-
 description = 'A jaeger instrumented java server meant for testing interoperability with different Jaeger clients through the use of crossdock (https://github.com/crossdock/crossdock)'
 ext.jacksonVersion = '2.8.10'
 shadowJar.archiveName = 'jaeger-crossdock.jar'
@@ -13,9 +12,6 @@ compileJava {
 dependencies {
     compile project(':jaeger-client')
 
-    compile group: 'org.apache.thrift', name: 'libthrift', version: apacheThriftVersion
-    compile group: 'com.squareup.okhttp3', name: 'okhttp', version: okhttpVersion
-
     compile group: 'io.opentracing.contrib', name: 'opentracing-jaxrs2', version: '0.1.4'
     compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: jacksonVersion
     compile group: 'org.glassfish.jersey.containers', name: 'jersey-container-grizzly2-http', version: jerseyVersion
diff --git a/jaeger-thrift/build.gradle b/jaeger-thrift/build.gradle
index 06cb77f..f76d53f 100644
--- a/jaeger-thrift/build.gradle
+++ b/jaeger-thrift/build.gradle
@@ -56,8 +56,13 @@ shadowJar {
     relocate 'okhttp'           , 'jaeger.okhttp'
     relocate 'okio'             , 'jaeger.okio'
     relocate 'org.apache'       , 'jaeger.org.apache'
+    relocate 'org.slf4j'        , 'jaeger.org.slf4j'
     classifier null
     configurations = [project.configurations.compileOnly]
+    dependencies {
+        exclude(dependency('org.projectlombok:lombok'))
+        exclude(dependency('org.codehaus.mojo:animal-sniffer-annotations'))
+    }
 }
 
 task testJar(type: Jar, dependsOn: testClasses) {
```

Would you be interested in trying this out and sending a PR, in case it fixes your issue?

**Comment by mdvorak** [comment]
@jpkrohling I have suggestion to relocate classes to `io.jaeger` instead of `jaeger`, or even nest it deeper, to avoid any conflicts with other parts of the library. Note that those bundled classes are publicly on the classpath, and can be used by anyone (but should not).

Also, I suggest not to rebundle Slf4j, but really have it as dependency. It will be cleaner.

**Comment by yurishkuro** [comment]
> I have suggestion to relocate classes to io.jaeger instead of jaeger

io.jaegertracing.vendor.***

**Comment by jpkrohling** [comment]
Sounds good to me!

**Comment by mdvorak** [comment]
There are more questions about it - will those dependencies be private for jaeger-thrift, or used in other jaeger libraries as well? Will some of the bundled dependency be also relocated in another library? If so, shouldn't they be shared? Is it worth it to share them?
Otherwise good idea, but still, target package depends on answers for above.

**Comment by mdvorak** [comment]
@jpkrohling Question was whether classes, that are bundled (shadowed), should be used from another library. But when I consider how it works, it is not a good idea.

For zipkin, I'm opening another issue.
