### ISSUE TITLE
JaegerTracer and other core classes should not be in internal package

### ISSUE THREAD

**Issue by mdvorak** [jaegertracing/jaeger-client-java#503]
I don't agree with latest project restructuring - while its great classes no longer share name with their parents, I don't believe `JaegerTracer`, `JaegerSpan` etc should be in package `io.jaegertracing.internal`. It forces any user of the library to use "internal" classes for completely valid use-cases.
The only really "public" class `io.jaegertracing.Configuration` does not provide api to properly configure the tracer (e.g. provide custom Reporter etc). Only way to achieve that is its `getTracerBuilder()` method, but then we are back to internal classes.

I think Jaeger* classes are the public API of this library, and should be available. OpenTracing API is the abstraction, and if someone needs to use jaeger specifically, they should be able to.

If it was deliberate choice, then more advanced API for configuration should be provided - e.g. moving whole `JaegerTracer.Builder` out of internal somewhere public.

Use case:
https://github.com/opentracing-contrib/java-spring-jaeger/tree/master/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter

**Comment by jpkrohling** [comment]
> If it was deliberate choice

Previously, everything was part of the public API. We then decided to make everything internal and wait for feedback (such as yours!) before making things public again.

Specifically to the reporters, I remember @yurishkuro mentioning that concrete reporters/samplers would be decided based on the configuration used. For instance, if a JAEGER_COLLECTOR_ENDPOINT env var is provided, then the `RemoteReporter` with `HttpSender` should be used. The reasoning being that how to select a reporter/sender is internal knowledge of the library.

We also discussed loading custom reporters/senders via the Service Loader, like we are doing with the [metrics](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/Configuration.java#L239), but decided to wait for concrete use cases before doing that.

That all said: what's the use case you have in mind for a custom reporter?

**Comment by Sharpie** [comment]
I agree with the concern @mdvorak raised: the current Configuration API is not sufficient for all usecases. Specifically, you _will always_ get a RemoteReporter and possibly an additional LoggingReporter. There is no option to configure anything different via the Configuration class even if configuration is happening in Java code that is not bound by the constraints of environment variables.

My use cases would be:

  - Easy selection of the InMemoryReporter via the Configuration class, for use in tests.

  - Easy selection of a custom reporter, say a logger that dumped spans as newline-delimited Zipkin JSON. This sort of format could be easily exported from an on-premise customer installation and would enable remote post-mortem performance debugging.
