### ISSUE TITLE
Consider google-java-format for auto-formatting diffs

### ISSUE THREAD

**Issue by isaachier** [jaegertracing/jaeger-client-java#515]
## Requirement - what kind of business use case are you trying to solve?

Formatting code is tedious and time-consuming. It leads to unnecessary debate in pull requests. I know Google's formatter is opinionated and ultimately not a good choice for this project.

## Problem - what in Jaeger blocks you from solving the requirement?

No automatic formatting tool is used to standardize the style across classes.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

[clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) can format Java code. It is highly configurable as well. clang-format-diff.py can alleviate concerns about large style changes by limiting the scope to lines that appear in the diff.

## Any open questions to address

Make sure the changes conform with checkstyle's rules.

**Comment by yurishkuro** [comment]
I am not clear on the objective here.

> Google's formatter is opinionated and ultimately not a good choice for this project.

This is exactly what we want from the formatter - to be opinionated and definitive, just like `go fmt`, so that we don't have any formatting debates.

The problem I do see is that we don't seem to actually apply the formatting automatically, hence your other PR keeps getting formatting changes in the unrelated code. I am 100% in favor of the strictest rules for this, i.e. if we have an agreed upon formatter (which must run from command line, not the IDE), then it must break the build if the code is not formatted with it.

**Comment by isaachier** [comment]
Here is an example where you did not agree with the Google style algorithm: https://github.com/jaegertracing/jaeger-client-java/pull/509#discussion_r210028597. The Google tool cannot be configured to use that style. clang-format allows you to configure penalty values, style choices, etc. to be consistent and "pretty" at the same time.

**Comment by yurishkuro** [comment]
My comment was just a question. If that's how auto-formatter does it, it is acceptable. I don't want to be in the business of configuring the formatter with something specific to our project alone.

**Comment by isaachier** [comment]
Wtvr I want to give it a shot on my own, but I understand your point. I find Google tooling to be incredibly opinionated, which is probably perfect internally at Google, but doesn't work well in open source.

**Comment by isaachier** [comment]
If you are okay with the Google formatter, we can just apply the style everywhere after landing this batch of PRs. This should be accompanied by an auto-formatting enforcer to guarantee all future changes are formatted properly. Then this whole thing will no longer be an issue.

**Comment by isaachier** [comment]
For the record, in C/C++, clang-format is the de-facto formatting tool. In fact, I am almost certain the Google plugin is a knock-off, which is why the naming (clang-format vs. google-java-format) and scripts (`clang-format-diff.py` vs. `google-java-format-diff.py`) are so similar. I haven't hand-formatted a C/C++ file in ages, and jaeger-client-cpp never has any formatting issues unless a PR tries to introduce them, in which case I refer them to the formatting script. Uber's [h3](https://github.com/uber/h3) is stricter and formats the files for every build. Once you have an established convention, no one will really care to complain about the config.

**Comment by isaachier** [comment]
I think the Java support is limited in clang-format. Changing issue to be about google-java-format.
