### ISSUE TITLE
Exceptions on JaegerTracer::inject/extract

### ISSUE THREAD

**Issue by sergeyklay** [jaegertracing/jaeger-client-java#524]
Hello,

I have a principal question that started in https://github.com/opentracing/opentracing-php/pull/81.

As I can see here:
https://github.com/jaegertracing/jaeger-client-java/blob/b6a824d0f6e54f246a1c5583e45536a1143c4c30/jaeger-core/src/main/java/io/jaegertracing/spi/Extractor.java#L33-L50

and here:

https://github.com/jaegertracing/jaeger-client-java/blob/b6a824d0f6e54f246a1c5583e45536a1143c4c30/jaeger-core/src/main/java/io/jaegertracing/spi/Injector.java#L34-L48

All exceptions thrown in `JaegerTracer::inject`, `JaegerTracer::extract` should be caught and logged. 

However, this rule is not complied with:

https://github.com/jaegertracing/jaeger-client-java/blob/b6a824d0f6e54f246a1c5583e45536a1143c4c30/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java#L190-L197

I'm pretty sure that tracing shouldn't stop application. I don't know why putting the opentracing into the project should increase risks expressed in the form of UnsupportedFormatException exception or any other domain specific exception. However, I am not a specialist in this field and would like to hear the reasoned arguments.  Could you please elaborate on that.

Thank you

**Comment by yurishkuro** [comment]
To clarify, the "no exception" policy applies to runtime during the normal app flow, i.e. a tracer should not throw exceptions on, say, malformed HTTP headers carrying bad tracing context.

However, the exception you pointed out is of structural (almost configuration) nature - the instrumentation code is sending a format the tracer does not understand. Format is not something that changes at runtime, it's hardcoded in the instrumentation code, so in this case it's better to throw exception than to mask it and make it hard to diagnose.

**Comment by sergeyklay** [comment]
@yurishkuro What do you think about updating the documentation in such a way as to reflect this idea? I mean "all exceptions" here is not all actually.

**Comment by yurishkuro** [comment]
Please propose a PR.
