### ISSUE TITLE
Use clear messages about non-standard usage of the sender factory

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#532]
See https://github.com/jaegertracing/jaeger-client-java/pull/531#discussion_r212220915

**Comment by smieras** [comment]
I was looking into this good first issue and was wondering what the difference is between a JAEGER_SENDER_FACTORY not specified to select and a JEAGER_SENDER_FACTORY value not found as describer by @objectiser in [#531 (comment)](https://github.com/jaegertracing/jaeger-client-java/pull/531#discussion_r212220915) ?

I think the following code solves the first scenario (factory not specified to select, based on the unit test testMultipleImplementationsAmbiguous).

```
public static Sender resolve(Configuration.SenderConfiguration senderConfiguration) {
    Sender sender = null;
    ServiceLoader<SenderFactory> senderFactoryServiceLoader = ServiceLoader.load(SenderFactory.class,
        SenderFactory.class.getClassLoader());
    Iterator<SenderFactory> senderFactoryIterator = senderFactoryServiceLoader.iterator();

    boolean hasMultipleFactories = false;
    boolean isJaegerSenderFactorySelected = false;
    while (senderFactoryIterator.hasNext()) {
      SenderFactory senderFactory = senderFactoryIterator.next();

      if (senderFactoryIterator.hasNext()) {
        log.debug("There are multiple factories available via the service loader.");
        hasMultipleFactories = true;
      }

      if (hasMultipleFactories) {
        // we compare the factory name with JAEGER_SENDER_FACTORY, as a way to know which
        // factory the user wants:
        String requestedFactory = System.getProperty(Configuration.JAEGER_SENDER_FACTORY);
        if (senderFactory.getType().equals(requestedFactory)) {
          isJaegerSenderFactorySelected = true;
          log.debug(
              String.format("Found the requested (%s) sender factory: %s",
                  requestedFactory,
                  senderFactory)
          );

          sender = getSenderFromFactory(senderFactory, senderConfiguration);
        }
      } else {
        sender = getSenderFromFactory(senderFactory, senderConfiguration);
      }
    }

    if (null != sender) {
      log.debug(String.format("Using sender %s", sender));
      return sender;
    } else if (hasMultipleFactories && !isJaegerSenderFactorySelected) {
      log.warn("Found multiple factories but {} was not specified to be selected. "
          + "Using NoopSender, meaning that data will not be sent anywhere!", Configuration.JAEGER_SENDER_FACTORY);
      return new NoopSender();
    } else {
      log.warn("No suitable sender found. Using NoopSender, meaning that data will not be sent anywhere!");
      return new NoopSender();
    }
  }
```

**Comment by jpkrohling** [comment]
The code that selects a factory is within a loop, so, when a user specifies a factory that does not exist, it will be treated as if the value hasn't been specified. When someone explicitly gives a factory name to use, we expect to find it and the user needs to get a `WARN` level message when this is not found.

**Comment by vpbhargav** [comment]
@jpkrohling I would like to work on this.

**Comment by jpkrohling** [comment]
It's yours. The tricky part is coming up with a concise, yet clear message for each case :)

**Comment by vpbhargav** [comment]
Just to make sure I understand things correctly, quoting from [#531 (comment) ](https://github.com/jaegertracing/jaeger-client-java/pull/531#discussion_r212220915)

1. "multiple factories but JAEGER_SENDER_FACTORY not specified to select" 
refers to 
`String requestedFactory = System.getProperty(Configuration.JAEGER_SENDER_FACTORY);`
where requestedFactory would be null and hasMultipleFactories would be true. 

2. "multiple factories found, but JAEGER_SENDER_FACTORY value not found in the list"
refers to case when hasMultipleFactories is true but after the selection loop there is no match to the specified Sender and hence sender== null.

3. "no sender factories found" refers to senderFactoryIterator.hasNext() returning false the very first time.

**Comment by jpkrohling** [comment]
That's absolutely correct.
