### ISSUE TITLE
Move to bintray

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#536]
## Problem - what in Jaeger blocks you from solving the requirement?

I've been doing the releases for some time now and it's always a pain... Not only because of the automation aspects (#58), but because it takes a really long time to upload the artifacts to Sonatype.
Examples from today:

```
$ ./gradlew upload
<========-----> 68% EXECUTING [25m 52s]
> :jaeger-micrometer:uploadArchives
^C
$ ./gradlew upload
<============-> 94% EXECUTING [16m 5s]
> :jaeger-zipkin:uploadArchives
^C 
$ ./gradlew upload
<============-> 94% EXECUTING [20m 12s]
> :jaeger-zipkin:uploadArchives
^C
```

The last two runs got stuck on `jaeger-zipkin` alone for more than 5 minutes, even though these artifacts are really small:
```
$ ls -lah jaeger-zipkin/build/libs/
total 88K
drwxr-xr-x. 2 jpkroehling wheel 4,0K 23. Aug 16:09 .
drwxr-xr-x. 7 jpkroehling wheel 4,0K 23. Aug 17:17 ..
-rw-r--r--. 1 jpkroehling wheel  15K 23. Aug 16:09 jaeger-zipkin-0.30.6.jar
-rw-r--r--. 1 jpkroehling wheel  475 23. Aug 16:09 jaeger-zipkin-0.30.6.jar.asc
-rw-r--r--. 1 jpkroehling wheel  40K 23. Aug 16:09 jaeger-zipkin-0.30.6-javadoc.jar
-rw-r--r--. 1 jpkroehling wheel  475 23. Aug 16:09 jaeger-zipkin-0.30.6-javadoc.jar.asc
-rw-r--r--. 1 jpkroehling wheel  11K 23. Aug 16:09 jaeger-zipkin-0.30.6-sources.jar
-rw-r--r--. 1 jpkroehling wheel  475 23. Aug 16:09 jaeger-zipkin-0.30.6-sources.jar.asc
```

I'm not sure what's wrong: perhaps it's the Sonatype Gradle plugin we are using, or Sonatype itself. I'd like to give bintray a try, both because it's a different plugin and because it's a different provider. 

This would mean doing quite a few "useless" (patch) releases.

**Comment by jpkrohling** [comment]
>  I'd like to give bintray a try, both because it's a different plugin and because it's a different provider.

Or ShipKit, mentioned by @vprithvi on #58

**Comment by yurishkuro** [comment]
@jpkrohling how were you doing releases recently? I followed the procedure in the doc, but the [Travis job][1] keeps failing.

If you were doing them manually, do you mind doing it for 0.31?  My PK expired, I need to re-register with the key servers, but didn't have time.

[1]: https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/421783949

**Comment by jpkrohling** [comment]
>  you were doing them manually, do you mind doing it for 0.31?

Done!

**Comment by yurishkuro** [comment]
Thanks!

**Comment by vprithvi** [comment]
I second trying out Bintray, ShipKit supports Bintray by default, and configuration seems straightforward

**Comment by jpkrohling** [comment]
I've been reading about ShipKit and I'm about to start an experiment in a pet project. It looks like ShipKit works best in a continuous delivery mode, where every change becomes a release and versioning happens automatically, unless explicitly in a commit via a `version.properties`. I think it makes a lot of sense, especially for a library like ours.

It *also* works in a non-continuous delivery way, so, deciding one way or another won't block us from using it.

**Comment by jpkrohling** [comment]
So, I got the plugin working locally and here are some results:

- Jaeger v0.31.1 and v0.31.2 got released to bintray (not to Maven Central yet, I'll setup the sync to central only as one of the final steps of this issue here)
- Changelog: https://github.com/jpkrohling/jaeger-client-java/blob/release/536-Move-to-bintray/CHANGELOG.md
- Look at the commits on this branch as well, especially the latest one (release of 0.31.2). For a continuous delivery setup, I think we'll end up having tons of such commits. So, I'm backing from this idea now. Instead, we could just do something like we do for OpenTracing repositories, were we'd tag something with "release/..." and a release would happen.

All in all, I think it looks good and I'd proceed with this setup.

**Comment by jpkrohling** [comment]
Two items that would be nice to have in Shipkit are:

https://github.com/mockito/shipkit/issues/194
https://github.com/mockito/shipkit/issues/75

I don't think they are blockers, but the second is something we'll probably forget to do quite often...

**Comment by yurishkuro** [comment]
+1 for releasing only on a release tag.
-1 on fully automated changelog (but +1 to have a tool that creates a draft from commits, right now it's awfully manual, especially with all the links to PRs / users).

**Comment by jpkrohling** [comment]
I'm closing this, as I'm not sure we'll ever move to bintray.
