### ISSUE TITLE
Jaeger client does not report baggage item

### ISSUE THREAD

**Issue by ghostPM** [jaegertracing/jaeger-client-java#543]
It seems that jaeger client does not report baggage item because the thrift span does not include a baggage item field, which means that my span data storage system will loss the baggage item info.

I'm not sure if it is the problem of jaeger's design or some other reason? Thanks.

**Comment by pavolloffay** [comment]
hi @ghostPM the baggage should be stored in span logs. There is no separate property for baggage as it's main purpose is to be propagated to downstream services as distributed context.
