### ISSUE TITLE
conflict between withStartTimestamp and computeDurationViaNanoTicks

### ISSUE THREAD

**Issue by jerryldh** [jaegertracing/jaeger-client-java#545]
if withStartTimestamp was set, then computeDurationViaNanoTicks will be set false,
so that spans’s finish time is set by default SystemClock，
finish time accuracy is set to ms.
if starttimestamp accuracy is set to μs and span duration is less than 1ms,
ecxeption occurs!
![image](https://user-images.githubusercontent.com/8142461/45144388-8798b700-b1f0-11e8-8393-6e88e0c4ab3c.png)
Actually duration is less than 1ms

**Comment by black-adder** [comment]
Would you be able to contribute a fix?
