### ISSUE TITLE
Debug flag does not lead to sampling (reporting of spans) by itself.

### ISSUE THREAD

**Issue by kazie** [jaegertracing/jaeger-client-java#556]
## Requirement - what kind of business use case are you trying to solve?

Following the specification/documentation.

## Problem - what in Jaeger blocks you from solving the requirement?

Not creating spans as specified in the specification.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Change the code so spans are reported on debug, as that seems to be what the specification says.

# Ticket

According to documentation
> Bit 2 is “debug” flag
>   * Debug flag **implies sampled flag**
>    * Instructs the backend to try really hard not to drop this trace

Whilst in the code we can see that that is not the case:
```java
  private void finishWithDuration(long durationMicros) {
    synchronized (this) {
      if (finished) {
        log.warn("Span has already been finished; will not be reported again.");
        return;
      }
      finished = true;

      this.durationMicroseconds = durationMicros;
    }

    if (context.isSampled()) {
      tracer.reportSpan(this);
    }
  }
```

Specifically:
```java
    if (context.isSampled()) {
      tracer.reportSpan(this);
    }
```

As `isSampled()` has no relation to `isDebug()`

```java
  public boolean isSampled() {
    return (flags & flagSampled) == flagSampled;
  }
```

While maybe one could have had something like this:
```java
  public boolean isSampled() {
    return isDebug() || (flags & flagSampled) == flagSampled;
  }
```

----

So in short, if one has a request that sent with the tag of `2`, then it gets:
* `Sampled: 0`
* `Debug: 1`

Which will not get "reportSpan()` and thus not reported.
At least that seemed to be the case for me!

---

I am not sure if I read it wrong, so maybe the documentation is what needs to be clarified? :)

---

Example testcode I woudl expect would be something like this:
```java
  @Test
  public void testDebugCreatesSampled() {
    Map<String, String> headers = Collections.singletonMap("uber-trace-id", "38df96cb5d6e0a38:38df96cb5d6e0a38:0:2");
    TextMap carrier = new TextMapExtractAdapter(headers);

    JaegerSpanContext inboundSpanContext = tracer.extract(Format.Builtin.HTTP_HEADERS, carrier);
    assertNotNull(inboundSpanContext);
    assertTrue(inboundSpanContext.hasTrace());

    JaegerSpan span = tracer.buildSpan("span").asChildOf(inboundSpanContext).start();
    JaegerSpanContext serverSpanContext = span.context();
    assertTrue(serverSpanContext.isSampled());
    assertTrue(serverSpanContext.isDebug());
  }

---> FAILS ON:    assertTrue(serverSpanContext.isSampled());
```

to return `isSampled` but it doesnt - or the logic around reporting traces not be fully bound to `isSampled()` but also consider `isDebug()`.

**Comment by yurishkuro** [comment]
Debug flag is not intended to be set manually, at least not without other restrictions. The only officially supported way is either setting `sampling.priority` span tag or passing `jaeger-debug-id` http header. In both cases the debug flag will be accompanies by the sampling flag simultaneously. What your code example is doing is bypassing these supported ways and hacking the flag to be "debug but not sampled", which never happens with the official paths.

**Comment by kazie** [comment]
So I guess the issue is the documentation then, as it is not clear from documentation that:



>    Bit 2 is “debug” flag
>    *    Debug flag implies sampled flag
>    *    Instructs the backend to try really hard not to drop this trace


Actually means something like:

> Bit 2 is “debug” flag
> **do not use this manually** as there is no guarantee that the sampling will be ensured. Sampling is only ensured if `1` (bit) is set.

---

But thanks for your answer, it explains a lot about it. :)

**Comment by yurishkuro** [comment]
Updated docs

**Comment by kazie** [comment]
Thanks, that's much clearer :+1:
