### ISSUE TITLE
Migrate from travis to circleci

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-client-java#562]
It should fix the release problem with changing public IP. https://github.com/gradle/gradle/issues/5711

See https://github.com/jaegertracing/jaeger-client-java/pull/549#issuecomment-429898974

**Comment by yurishkuro** [comment]
I prefer not to move to circleci, we have almost 100% (except for c#)  of projects built on travis.

**Comment by pavolloffay** [comment]
I see your point, on the other hand circleci is widely adopted in many OSS projects and the syntax si very similar to travis. If it solves the problem I don't mind migrating this repo there.

**Comment by pavolloffay** [comment]
Travis builds are sometimes flaky. It might be even good to experiment with circleci if the builds are more stable.

**Comment by yurishkuro** [comment]
Well, I've seen enough disparaging comments about circleci as well, don't think either solution is superior to the other.

Flaky builds can be probably improved with retries. I just rather not learn another build DSL, our travis files are already pretty complicated (although maybe not so much in the client repos).
