### ISSUE TITLE
Make the whole URL for remoteSampler / Service name configurable

### ISSUE THREAD

**Issue by lff0305** [jaegertracing/jaeger-client-java#565]
Currently the service name is hard coded, as in HttpSamplingManager.java

` jsonString =
          makeGetRequest(
              "http://" + hostPort + "/?service=" + URLEncoder.encode(serviceName, "UTF-8"));`

In my project, I found that it would be greate helpful if the whole endpoint can be configured, instead of just hostPort. 

For example,

I can config it as a RESTFUL service:
**remoteURL=http://xxx.com/${serviceName}**
or , 
as a query parameter
**remoteURL=http://xxx.com/?q=${serviceName}**
or, as HTTPS:
**remoteURL=https://xxx.com/${serviceName}**

Thanks.

**Comment by yurishkuro** [comment]
At this time only agent exposes this configuration API, and the agent is supposed to run as a sidecar or host agent on the same host as the application.

I think there were PRs somewhere to introduce `JAEGER_CONFIG_ENDPOINT` config, iirc.

**Comment by lff0305** [comment]
Thanks, I checked the PR but the URL is still hard coded 
   serverUrl + "?service=" + URLEncoder.encode(serviceName, "UTF-8"));
Another thing missed is that this PR only deals with get config from ENV, the load for springboot  / springcloud is not updated.

**Comment by pavolloffay** [comment]
> load for springboot / springcloud is not updated.

That is handled by a different project - https://github.com/opentracing-contrib/java-spring-jaeger

**Comment by pavolloffay** [comment]
Why do you need to have the service name configured separately?  Do you want to use sampling strategies for different service name than one used to report spans?

**Comment by lff0305** [comment]
> Why do you need to have the service name configured separately? Do you want to use sampling strategies for different service name than one used to report spans?

That's correct. I am doing a project with springcloud (serveral microservices), and I'd like to control the tracing behavior of the microservices (config-service, api-gateway, etc) separately.

Currently the service name is passed as a parameter ( ?service=....), it is fine but I have to build another web service.

If it can be configurable ( remoteURL=http://xxx.com/${serviceName} ) Then I can re-use the spring cloud config server, which is better to me.

**Comment by yurishkuro** [comment]
Sorry, I don't follow the use case.

> I have to build another web service to provide the tracing config json.

jaeger agent + collector already provide the ability to control sampling per-service via configuration. Why do you need another service?

> If it can be configurable ( remoteURL=http://xxx.com/${serviceName} )

A given tracer represents a single service, so when it calls for sampling configuration it asks for sampling for that service (and you pass the name of the service to the tracer when creating it). With your suggestion you can force the tracer to ask for sampling strategy under a different service name - I don't understand that use case.

**Comment by lff0305** [comment]
Hi Thanks for you message.

> Sorry, I don't follow the use case.
> 
> > I have to build another web service to provide the tracing config json.
> 
> jaeger agent + collector already provide the ability to control sampling per-service via configuration. Why do you need another service?

This is mostly for enable / disable tracing for a specific micro service at runtime without restarting. And due to some firewall limit, the HTTP pulling of sampling configuration is blocked. That's why I have to build a web service internally to provide the configs.

> > If it can be configurable ( remoteURL=[http://xxx.com/${serviceName}](http://xxx.com/$%7BserviceName%7D) )
> 
> A given tracer represents a single service, so when it calls for sampling configuration it asks for sampling for that service (and you pass the name of the service to the tracer when creating it). With your suggestion you can force the tracer to ask for sampling strategy under a different service name - I don't understand that use case.

Sorry, I did not want to ask for a different service name. All I need is to set the serviceName as part of the URL (Restful style), not as a parameter.

The following is my code for test:

`@Override
  public SamplingStrategyResponse getSamplingStrategy(String serviceName)
      throws SamplingStrategyErrorException {
    String jsonString;
    String urlConfig = "https://192.168.1.200/config/${service}";
    urlConfig = urlConfig.replaceAll("\\$\\{serviceName\\}", serviceName);
      try {
        jsonString =
                makeGetRequest(urlConfig);
      } catch (IOException e) {
        throw new SamplingStrategyErrorException(
                "http call to get sampling strategy from local agent failed.", e);
      }
    } 
    return parseJson(jsonString);
  }
}`

**Comment by jpkrohling** [comment]
> That's why I have to build a web service internally to provide the configs.

I think this is the crucial aspect and it would make easier the life of people replacing specific parts of Jaeger with their implementations.

**Comment by yurishkuro** [comment]
Fair enough, I can see the value there. But I still think we must keep the existing simpler way of pointing to the agent with just the `host:port`, since it is the default recommended architecture, and I don't want every user to have to know about the exact URL with variable substitution syntax.

**Comment by yurishkuro** [comment]
Actually, I still don't see why the independent service cannot provide the same API as provided by the agent, with the same URL structure?

**Comment by houstonheat** [comment]
> At this time only agent exposes this configuration API, and the agent is supposed to run as a sidecar or host agent on the same host as the application.

A Jaeger-collector is now exposing sampling API endpoint, so we can throw spans directly to it and get sampler configuration too (without jaeger-agent) https://github.com/jaegertracing/jaeger/pull/1990
