### ISSUE TITLE
Update to opentracing-java 0.32.0

### ISSUE THREAD

**Issue by dougEfresh** [jaegertracing/jaeger-client-java#566]
I like to add support for the upcoming release of opentracing-java 0.32.
I would like to help make these changes. Can some provide guidance?

There are three files which require updating:

-  jaeger-core/src/main/java/io/jaegertracing/internal/JaegerSpan.java
-  jaeger-core/src/main/java/io/jaegertracing/internal/JaegerSpanContext.java
-  jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java 

PR: 
#567

**Comment by yurishkuro** [comment]
Thanks for the initiative. 

Why don't you create a pull request instead?

**Comment by dougEfresh** [comment]
@yurishkuro 
#567
