### ISSUE TITLE
jaeger-client is missing in release 0.33.0

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-client-java#577]
The `jaeger-client` artifact has not been published in release 0.33.0 https://repo.maven.apache.org/maven2/io/jaegertracing/jaeger-client/. Maybe we have changed something in gradle conf or just the release went wrong. 

If I remember correctly the release process finished successfully.

**Comment by mpetazzoni** [comment]
@pavolloffay any updates on this? We'd really like to be able to use 0.33 to benefit from the HTTPSender fix from #571.

**Comment by pavolloffay** [comment]
I am looking into this, I will try to release it ass 0.33.1

**Comment by pavolloffay** [comment]
0.33.1 is out, but I still do not see it in https://repo.maven.apache.org/maven2/io/jaegertracing/jaeger-client/. In jaeger-core it is present.

**Comment by pavolloffay** [comment]
Awesome jaeger-client seems to be there! https://repo.maven.apache.org/maven2/io/jaegertracing/jaeger-client/0.33.1/
