### ISSUE TITLE
Update libthrift to 0.12.0

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#581]
## Requirement - what kind of business use case are you trying to solve?

A security vulnerability was found on 0.11 and fixed on 0.12

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Once https://github.com/ahawkins/docker-thrift/pull/18 is merged and a new Docker image is available, just bump the version in the Gradle configuration. These changes were tested locally, with a self-built Docker image based on the mentioned PR.

**Comment by yurishkuro** [comment]
do we bundle thrift as shaded dep?

**Comment by jpkrohling** [comment]
We provide a shadow artifact with it:

> The Jaeger Java Client uses org.apache.thrift:libthrift:0.11.0. By default, declaring a dependency on the jaeger-thrift module will bring a non-shaded version of Thrift (and others). A shaded version of the dependency is available with the classifier shadow.

**Comment by jpkrohling** [comment]
I'm currently blocked on https://github.com/ahawkins/docker-thrift/pull/16 . Do we have a reason to use the thrift compiler via Docker image? Would it be OK to just document in the CONTRIBUTING.md which version we expect people to use and provide links to download it?

**Comment by yurishkuro** [comment]
> Do we have a reason to use the thrift compiler via Docker image?

Yes: repeatable builds, especially in local dev where you cannot install different versions easily.

**Comment by jpkrohling** [comment]
Repeatable builds isn't really the argument, as Travis would be configured to use the same version (0.12) for all the builds, no matter if via Docker or via binary.

But I can see how developers who need different versions would find it a PITA. Let's wait a few more days then and see if a Docker image is published for 0.12. In the worst case, I'll fork it and publish 0.12 under the `jaegertracing` namespace in DockerHub.

**Comment by yurishkuro** [comment]
Travis is not the only place where repeatable build is needed. The build env in Travis is much easier to control than in local dev setups.
