### ISSUE TITLE
Orders of span tags are not consistent.

### ISSUE THREAD

**Issue by vtdat** [jaegertracing/jaeger-client-java#582]
## Order of span tags is not preserved

In our projects, we would like to put several additional tags to span. As the number of tags grows, it becomes irritating to search through tags in data storage as well as JaegerUI. Plus, orders of tags among spans are not consistent.
![](https://user-images.githubusercontent.com/14995336/51738765-834b3880-20c2-11e9-82a3-1f7af9300d3a.png)
Ref: [jaeger-ui/#218](https://github.com/jaegertracing/jaeger-ui/issues/218)

## Proposal

Use `LinkedHashMap` or `TreeMap` for span tags instead of `HashMap`.

`LinkedHashMap`: similar to `HashMap` in most aspect. However, it preserved *insertion order*. Memory consumption is slightly affected due to `LinkedHashMap` uses double linked list in it.

`TreeMap`: implements `SortedMap` interface so tags will be in *natural order*. Its put/get operations take O(log n) time while `HashMap` and `LinkedHashMap`'s take O(1). 

Ref: [https://stackoverflow.com/questions/2889777](https://stackoverflow.com/questions/2889777/difference-between-hashmap-linkedhashmap-and-treemap)

**Comment by jpkrohling** [comment]
I don't think using a LinkedHashMap in the Java Client will make a difference in the UI, given that the data goes to the Jaeger backend in a data structure that doesn't contain the order index. Given that the use-case doesn't seem to be that common, adding such an index would cause a cost on all other use-cases.

What would make sense, IMO, is to implement a "highlight" feature in the UI, where you could enter the tag name and have it shown first (or highlighted).

**Comment by vtdat** [comment]
Thanks. Got it!
