### ISSUE TITLE
Offer manual shutdown of JaegerTracer

### ISSUE THREAD

**Issue by supersven** [jaegertracing/jaeger-client-java#585]
## Requirement - what kind of business use case are you trying to solve?

The automatic closing mechanism introduced with #544 doesn't work well with Payara's shutdown lifecycle.

It leads to exception logs like:
```
Completed shutdown of GlassFish runtime
Exception in thread "Thread-31" java.lang.IllegalStateException: This web container has not yet been started
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1544)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
	at io.jaegertracing.internal.reporters.RemoteReporter.close(RemoteReporter.java:91)
	at io.jaegertracing.internal.JaegerTracer.close(JaegerTracer.java:216)
	at io.jaegertracing.internal.JaegerTracer$1.run(JaegerTracer.java:130)
```

## Problem - what in Jaeger blocks you from solving the requirement?

Once the shutdown hook is registered at the JVM, it's not possible to remove it.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I propose to make the registration of the shutdown hook optional - configurable in `JaegerTracer.Builder`. As many people aren't using Payara, I would leave the current behaviour as default, that can be turned of by `withManualShutdown()`.

Please see https://github.com/supersven/jaeger-client-java/commit/fb34f243842c361976babdec93eaf220ec80593b  - This commit captures this proposal in code 😃 

## Any open questions to address

What do you think about this? Should I open a merge request?

**Comment by yurishkuro** [comment]
+1

**Comment by jpkrohling** [comment]
Looks good to me as well, but I'm wondering if there's a way to automatically detect this case? People will be aware of this manual shutdown only when they hit the same scenario as you. They will eventually find the workaround (hopefully), but it would be awesome if we could activate it automatically *and* add a log entry with a request to manually flush/close during the application's shutdown?

**Comment by supersven** [comment]
@jpkrohling This idea sounds great, but unfortunately I'm not aware of a simple way to detect if some java code is executed in an application server context or not. Any hints?

**Comment by jpkrohling** [comment]
I'm really outdated regarding GlassFish and I'm sure there are better ways, but one dirty hack is to check for the presence of well-known classes.

**Comment by supersven** [comment]
A colleague (@larslorenzen) suggests to query for the system property `com.sun.aas.instanceRoot`.
It should be defined for all running Glassfish/Payara instances.

Please see https://github.com/supersven/jaeger-client-java/commit/ccacb54c1f9a3fa3d196671e07f87c5ff38f9796

**Comment by jpkrohling** [comment]
Sorry, I think I should have expressed myself better: I think the original idea of having a configuration switch to disable to hook is a valid one for people running into *similar* cases as you did. 

In addition to that, we could be proactive in disabling the hook for scenarios where we *know* that it causes problems, like in Glassfish/Payara.

> A colleague (@larslorenzen) suggests to query for the system property `com.sun.aas.instanceRoot`.
It should be defined for all running Glassfish/Payara instances.

Is this system property *also* set in other environments? Just making sure we are affecting only Glassfish/Payara environments here :-)

**Comment by supersven** [comment]
`com.sun.aas.instanceRoot` seems to be Glassfish/Payara specific. I "googled" a bit around and found no usage by other application containers.

I've created a PR: https://github.com/jaegertracing/jaeger-client-java/pull/586
This combines both approaches: No shutdown hook for Glassfish/Payara and an additional flag in `JaegerTracer.Builder`.

**Comment by supersven** [comment]
Thanks a lot for discussing, reviewing and merging!

As the PR is merged, I'll close this ticket.
