### ISSUE TITLE
Spanid reserved extension interface to developers?

### ISSUE THREAD

**Issue by wuyupengwoaini** [jaegertracing/jaeger-client-java#588]
Now ,jaeger use Utils.java to generate unique id and there is no extension interface for developers to Customize their own spanid.

I want to customize spanid  Representing hierarchical relationships,such as 
1.Take Span with SpanID 1 as Root Span, indicating the starting point of a request.
2.When the order of the same level is called, the level of SpanID continues to grow, such as 1.1, 1.2, and 1.3.
3. When marking the calling relationship, you need to increase the level of SpanID, such as 1, 1.1, 1.1.1.

If doing so,we can achieve that 
1.Through spanid, you can know which spans are missing from the broken trace link.
2.Spanid is stored as a column in hbase

**Comment by yurishkuro** [comment]
IDs in Jaeger are random sequences of bytes. Even if we have extension mechanism to plug in your own generator, we still cannot represent hierarchical strings like 1.2.3.4

**Comment by wuyupengwoaini** [comment]
> we still cannot represent hierarchical strings like 1.2.3.4

The reason is that the spanid type is long?

**Comment by yurishkuro** [comment]
long is just internal representation, the real type is `byte[8]` for span id and `byte[16]` for trace id (which matches https://w3c.github.io/trace-context/)

**Comment by wuyupengwoaini** [comment]
Thanks,I've got it
