### ISSUE TITLE
IS there any way to collect trace data from any remote jaeger system in java pojo?

### ISSUE THREAD

**Issue by tutaidalal** [jaegertracing/jaeger-client-java#589]
IS there any way to collect trace data from any remote jaeger system in java pojo?

I am trying to collect Jagger traces remotely to validate some trace data in automation module.. What is the best way to collect the trace data in java object. HTTP Get provide the data in JSON format .. is there any other way ? any simple example will help a lot

**Comment by jpkrohling** [comment]
The data model is relatively simple, I don't see why you couldn't build your POJO's based on the fields from the JSON and use JAX-RS Client to make the requests to the Query component, storing the results in your POJOs, like:

https://docs.oracle.com/javaee/7/tutorial/jaxrs-client001.htm#BABBIHEJ .

Where you see `...get(String.class)`, you'd use your POJO (or a List of pojos). Once you get it working,I think it would make it for a nice blog post.

**Comment by yurishkuro** [comment]
We'll also have grpc endpoint in the query service soon, then you can retrieve spans as objects generated from protobuf.

**Comment by tutaidalal** [comment]
> 
> 
> The data model is relatively simple, I don't see why you couldn't build your POJO's based on the fields from the JSON and use JAX-RS Client to make the requests to the Query component, storing the results in your POJOs, like:
> 
> https://docs.oracle.com/javaee/7/tutorial/jaxrs-client001.htm#BABBIHEJ .
> 
> Where you see `...get(String.class)`, you'd use your POJO (or a List of pojos). Once you get it working,I think it would make it for a nice blog post.

Thanks. I will continue using string validation.

**Comment by tutaidalal** [comment]
> 
> 
> We'll also have grpc endpoint in the query service soon, then you can retrieve spans as objects generated from protobuf.

thanks ..
