### ISSUE TITLE
RFC: inject/extract functionality for Configuration

### ISSUE THREAD

**Issue by t-8ch** [jaegertracing/jaeger-client-java#594]
## Requirement - what kind of business use case are you trying to solve?

I have a traced system spawning processes (build systems) that are also traced. The propagation of traces works fine.
Unfortunately the configuration of the tracer has to be performed on both the scheduler and for each spawned system. As the spawned system are not directly under my control I would like not to have configure each system explicitly.

If a configuration propagation mechanism would be available for the Jaeger configuration itself the scheduler could create a suitable configuration of the process and make it available in a standard location. (config file/environment variable, etc).

## Problem - what in Jaeger blocks you from solving the requirement?

The extraction is mostly implemented in `Configuration.fromEnv()`. Injection would be possible to implement with the current APIs.
`Configuration.fromEnv()` only reads from the system environment and properties however, which makes in inconvenient for unit testing.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I would like to propose to propagate the Jaeger configuration via arbitrary `TextMap`s (or other formats).
I am willing to perform the implementation.

## Any open questions to address

Currently a configuration always has to have a `serviceName` for propagation it would be better to be able to inject a configuration without a `serviceName`, as it would potentially be supplied by the extracting party.
The check could propably be deferred to `Configuration.getTracer()` (maybe even with an explicit overload: `Configuration.getTracer(String serviceName)`

**Comment by yurishkuro** [comment]
Aren't env variables already that serialization mechanism for configuration?

**Comment by t-8ch** [comment]
But only for reading. I would like to also write them.
(And at the same time it could be implemented for arbitrary `TextMaps`, allowing new usecases and making testing easier at the same time)

**Comment by yurishkuro** [comment]
> But only for reading. I would like to also write them.

But you're the one who writes/defines them for the main binary, are you not? Put those settings in a file and reuse it in spawned processes. Or write a script that loops through env vars that start with `JAEGER_` and pass them to the child processes.

It feels to me like a very-very edge case that already has a number of possible solutions without introducing "config serialization" in the Jaeger client.

**Comment by t-8ch** [comment]
I do control the main binary. (And the smaller ones to a limited extend)
The settings in the main application are stored in an application specific format, so I can't share them as is. (Also the spawned processes may need certain adaptions to their configuration as determined by the controlling process.)

Currently `Configuration.fromEnv()` can only ever be used with environment variables and system properties, not config files.
I can duplicate the logic from `Configuration.fromEnv()`, but would prefer to reuse the existing logic.
It would be fairly trivial to allow the extraction of the settings from an arbitrary `Map<String, String>`, but then in the same way it would also be easy to generalize the extraction over arbitrary `TextMap`s.

The serialization is fairly trivial (see below), but I would prefer to have it in Jaeger proper to make sure it stays up to date.

If you feel it does not fit into Jaeger proper I can live with that, too.
Feel free to close the ticket.

```java
    public static Map<String, String> serialize(Configuration config) {
        Map<String, String> env = new HashMap<>();
        injectInto(config, new TextMapInjectAdapter(env));
        return env;
    }

    public static void injectInto(Configuration config, TextMap target) {
        put(target, Configuration.JAEGER_SERVICE_NAME, config.getServiceName());
        // FIXME missing getter
        // put(target, Configuration.JAEGER_TRACEID_128BIT, null)

        SamplerConfiguration sampler = config.getSampler();
        put(target, Configuration.JAEGER_SAMPLER_TYPE, sampler.getType());
        put(target, Configuration.JAEGER_SAMPLER_PARAM, sampler.getParam());
        put(target, Configuration.JAEGER_SAMPLER_MANAGER_HOST_PORT, sampler.getManagerHostPort());

        ReporterConfiguration reporter = config.getReporter();
        put(target, Configuration.JAEGER_REPORTER_FLUSH_INTERVAL, reporter.getFlushIntervalMs());
        put(target, Configuration.JAEGER_REPORTER_LOG_SPANS, reporter.getLogSpans());
        put(target, Configuration.JAEGER_REPORTER_MAX_QUEUE_SIZE, reporter.getMaxQueueSize());

        SenderConfiguration sender = reporter.getSenderConfiguration();
        put(target, Configuration.JAEGER_AGENT_HOST, sender.getAgentHost());
        put(target, Configuration.JAEGER_AGENT_PORT, sender.getAgentPort());
        put(target, Configuration.JAEGER_AUTH_TOKEN, sender.getAuthToken());
        put(target, Configuration.JAEGER_USER, sender.getAuthUsername());
        put(target, Configuration.JAEGER_PASSWORD, sender.getAuthPassword());
        put(target, Configuration.JAEGER_ENDPOINT, sender.getEndpoint());

        CodecConfiguration codec = config.getCodec();
        // FIXME serialize
        // put(target, Configuration.JAEGER_PROPAGATION, ...)

        Map<String, String> tags = config.getTracerTags();
        if (tags != null) {
            put(target, Configuration.JAEGER_TAGS, formatTags(tags));
        }
    }

    private static void put(TextMap target, @Nullable String key, @Nullable Object value) {
        if (key == null || value == null) {
            return;
        }
        target.put(key, value.toString());
    }

    private static String formatTags(Map<String, String> tags) {
        StringBuilder result = new StringBuilder();

        tags.forEach((key, value) -> {
            result.append(key);
            result.append("=");
            result.append(value);
            result.append(",");
        });

        return result.toString();
    }
```
