### ISSUE TITLE
Context propagation from zipkin to jaeger through Kafka

### ISSUE THREAD

**Issue by NikitoZZZZZ** [jaegertracing/jaeger-client-java#598]
Hello everyone.
I have program that was instrumented with zipkin. This program is calling my program which is instrumented with jaeger. I am trying to propagate B3 zipkin's headers to jaeger. I used approach with **io.jaegertracing.internal.JaegerTracer.Builder#registerInjector** and **io.jaegertracing.internal.JaegerTracer.Builder#registerExtractor** methods. I am also using [kafka client instrumentation](https://github.com/opentracing-contrib/java-kafka-client). Zipkin's headers are propagating through kafka, I can see them on the other side but spans are creating in a way that they are separated (see attached screenshots).
Zipkin:
![github - zipkin](https://user-images.githubusercontent.com/26743858/53815330-86173400-3f72-11e9-9bf5-0c3d67eafbbc.PNG)
Jaeger:
![github - jaeger](https://user-images.githubusercontent.com/26743858/53815336-89122480-3f72-11e9-950a-37386636d0c9.PNG)
Is this defined behavior and spans should look like this, separated, OR they should be the same in jaeger UI and zipkin UI.
Thank you.

**Comment by yurishkuro** [comment]
why are the screenshots from different tracing backends? Regardless of which instrumentation / propagation format you're using, I'd think you would want to see the trace in the same backend.

If the trace is getting broken, then somewhere the context is not being recognized. We can't help more than that without a reproducible code example.

I have a working example that only uses Jaeger: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/tree/master/Chapter05

**Comment by NikitoZZZZZ** [comment]
> why are the screenshots from different tracing backends?

I need to instrument several microservice components. The entry point component, that starts all spans, is instrumented with zipkin. I'm instrumenting inferior, underlying components with jaeger. I need two things to happen:
- Entry point component should collect ALL spans that are creating under one call chain. I did this:
`tracer = new io.jaegertracing.Configuration(componentName)
                        .withSampler(...)
                        .getTracerBuilder()
                        .withReporter(new CompositeReporter(
                                new RemoteReporter.Builder()
                                .withSender(.../*sender for jaeger agent*/)
                                ...
                                .build(),
                                new ZipkinV2Reporter(AsyncReporter.create(
                                        URLConnectionSender.create(...)
                                ))))
                        .registerInjector(Format.Builtin.TEXT_MAP, b3Codec)
                        .registerExtractor(Format.Builtin.TEXT_MAP, b3Codec)
                        .build();`
Zipkin registers all calls.
- I wan to see the same chain calls on jaeger backend but I guess that's not possible (see screenshots above).

**Comment by yurishkuro** [comment]
even if one of the services is instrumented with Zipkin, you can still collect all spans in the Jaeger backend, because it can accept several Zipkin formats.

**Comment by NikitoZZZZZ** [comment]
I followed every instruction on https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-zipkin to do that but I still can't collect all spans in Jaeger backend and furthemore I'm getting an exception when I'm trying to send spans from jaeger to zipkin via ZipkinV2Reporter. Do you have an idea what might be the problem?

**Comment by NikitoZZZZZ** [comment]
I found what was the issue. When I started docker image of jaeger I didn't set environment variable for zipkin collector port and I didn't exposed port 9411. https://www.jaegertracing.io/docs/1.8/getting-started/#all-in-one

**Comment by yurishkuro** [comment]
🎉
