### ISSUE TITLE
Using Traceresolver to get a Tracer

### ISSUE THREAD

**Issue by fmhwong** [jaegertracing/jaeger-client-java#605]
## Requirement - what kind of business use case are you trying to solve?

Use a vendor neutral way to obtain a Tracer

## Problem - what in Jaeger blocks you from solving the requirement?

Assuming I have classpath setup, when I run 
```
Tracer tracer = TracerResolver.resolveTracer();
```
to get a JaegerTracer.  I got 
```
WARNING: Error getting tracer using io.jaegertracing.tracerresolver.internal.JaegerTracerFactory@1c20c684: Service name must not be null or empty
```
JaegerTracer requires to set the environment variables prior to creating a Tracer.  If I have multiple vendor implementations available, how do I know I will get a JaegerTracer and set the environment variables prior calling `TracerResolver.resolveTracer()`?

**Comment by yurishkuro** [comment]
Don't think this is a valid issue. Traceresolver already provides vendor-neutral way **for the code** to get a tracer. But someone responsible for deployment configuration must add the correct vendor jar to the classpath. The same person can provide env vars to configure said vendor jar. Configuration params are inherently vendor-specific.

**Comment by fmhwong** [comment]
When using with Traceresolver, is there a way to programmatically configure the Tracer?  For example, setting the service name.  It will be nice if we can pass in the service name as a parameter to `resolveTracer()` method.
```
Tracer tracer = TracerResolver.resolveTracer(serviceName);
```

In the server that I am working with, it allows multiple Tracer objects.  Setting the `JAEGER_SERVICE_NAME` from the environment doesn't work for me.

**Comment by yurishkuro** [comment]
That would be a change in the TracerResolver API, please open a ticket there. If the API changes, we can easily support it in Jaeger.
