### ISSUE TITLE
Add a MAINTAINERS/CODEOWNERS file

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#610]
See jaegertracing/jaeger#254

**Comment by VictoryWekwa** [comment]
Hello @jpkrohling , I am an outreachy applicant for this cohort, please can I work on this issue if it is still open?

**Comment by jpkrohling** [comment]
Sure. Are you able to get the base of this on your own, or would you need a complete list of who goes where?

**Comment by VictoryWekwa** [comment]
> Sure. Are you able to get the base of this on your own, or would you need a complete list of who goes where?

Yes please, I would need a complete list of who goes where.
Thank you

**Comment by jpkrohling** [comment]
For maintainers, it would be easy: the current Jaeger maintainers are also maintainers here, and nobody else:

![image](https://user-images.githubusercontent.com/13387/97219683-9d9bd400-17ca-11eb-8d83-bee19e2df7f7.png)

For codeowners, it would take a while to gather though. You can probably ping them (perhaps even here in this issue) and confirm whether they'd want to be included in the maintainers file for this repository here.

**Comment by VictoryWekwa** [comment]
Alright. Thanks. Will ping them then update my PR.

**Comment by VictoryWekwa** [comment]
Hi @jpkrohling please would you want to be included in the maintainer's file for this repository?

**Comment by jpkrohling** [comment]
Yes.

**Comment by objectiser** [comment]
Yes

**Comment by yurishkuro** [comment]
+1
