### ISSUE TITLE
Is there any way to get TraceId in java?

### ISSUE THREAD

**Issue by Elsehere** [jaegertracing/jaeger-client-java#611]
I want to use TraceId to log record in the different service chain, but I cannot get TraceId by this client. Could you please give me some suggestions on it?

**Comment by objectiser** [comment]
The recently released 0.32 version of the OpenTracing API added the ability to get the trace and span ids from the `SpanContext`. There is currently a [PR to update the Jaeger client](https://github.com/jaegertracing/jaeger-client-java/pull/567) to support this version of the OpenTracing API.

**Comment by Elsehere** [comment]
@objectiser Thanks for your help, but I occurred this error, I don't know what happened when I call `tracer.activeSpan().context().toTraceId()`.
![image](https://user-images.githubusercontent.com/19883190/55847917-dd19b580-5b7d-11e9-8edc-f3ca4698989d.png)

**Comment by Elsehere** [comment]
@objectiser Thanks.
