### ISSUE TITLE
Is there any way to get traceId in logback.xml by using Jaeger not Zipkin brave?

### ISSUE THREAD

**Issue by Elsehere** [jaegertracing/jaeger-client-java#612]

**Comment by yurishkuro** [comment]
Here's example https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/master/Chapter11/exercise1/lib/src/main/java/lib/MDCScopeManager.java

**Comment by Elsehere** [comment]
@yurishkuro Thanks, I did it and it works well.
