### ISSUE TITLE
Support of 'Defer' sampling state

### ISSUE THREAD

**Issue by krabaey** [jaegertracing/jaeger-client-java#624]
## Requirement - what kind of business use case are you trying to solve?

We would like to set http tracing headers (in our case B3 compatible headers) on a proxy, but defer the sampling decision to the actual servers it is proxying. The proxy however is not capable of doing reporting. 
In this way the b3 headers could be centrally generated & injected. 

Currently this does not seem not possible.

## Problem - what in Jaeger blocks you from solving the requirement?

According to [zipkin-b3-propagation](https://github.com/apache/incubator-zipkin-b3-propagation#sampling-state) sampling is a state with 4 possible values: Defer,Deny,Accept,Debug.

In JaegerSpanContext this is modeled into two booleans: sampled and debug.
The consequence is that the B3TextMapCodec cannot report the 'defer' sampling state.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Adapt the JaegerSpanContext & B3TextMapCodec to take into account the possible values of the sampling state so defering the sampling desision is supported.

## Any open questions to address

None

**Comment by yurishkuro** [comment]
> set http tracing headers (in our case B3 compatible headers) on a proxy

can you elaborate for what reason?

**Comment by krabaey** [comment]
> > set http tracing headers (in our case B3 compatible headers) on a proxy
> 
> can you elaborate for what reason?

All access to our services is via a proxy (ha-proxy in this case). As part of improving observability we use the trace id to correlate all logging of all services for a particular trace. As the proxy is part of the infrastructure, we want to include the trace id in the proxy access log. Since the proxy is our first component in the chain, this one will create the trace id (if none is present).  

An unintended side effect of injecting the X-B3-TraceId and X-B3-SpanId header is that no reporting of traces is done anymore by the other components, as Jaeger in this case interprets the absence of the X-B3-Sampled header as an instruction to not sample the trace.

The reason of not taking the decision to sample on the proxy is twofold:

- integration of the 'sampling decision' module would be challenging as I don't know of any existing integration. 
- we want the decision of sampling to be taken by the specific service as for some services we may take a different decision to sample or not per service (e.g. high load services, critical services, ...)

**Comment by yurishkuro** [comment]
I'm not opposed to it if you're interested to contribute the enhancement.
