### ISSUE TITLE
Unable to embed application traces from Istio service Mesh Trace

### ISSUE THREAD

**Issue by sherwoodzern** [jaegertracing/jaeger-client-java#628]
## Requirement - what kind of business use case are you trying to solve?

I'm trying to connect the tracer in my application code to the Tracer that is running by the Istio service mesh. I want to see the spans that I start in the application code.

## Problem - what in Jaeger blocks you from solving the requirement?

I'm using CDI.
@Inject Tracer tracer
GlobalTracer.registerIfAbsent(tracer);

I do GlobalTracer.get().scopeManager(), but this returns a NoopScopeManager.

I am unable to obtain the active span or the parent span, thus I cannot buildSpan as the child of the parent span.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Just provide a solution as to how I can embed the application traces within the Service Mesh traces.

**Comment by pavolloffay** [comment]
hi @sherwoodzern are you using any instrumentation in your application? Or could you please provide output from `mvn dependency:tree`? 


Your application has to be instrumented with OpenTracing library https://github.com/opentracing-contrib to be able to propagate tracing started by service mesh through your application.

**Comment by sherwoodzern** [comment]
Here's what is in the dependency tree:
szern-mac:generalHello szern$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< com.oracle.helidon:generalHello >-------------------
[INFO] Building generalHello 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.9:tree (default-cli) @ generalHello ---
[INFO] com.oracle.helidon:generalHello:jar:1.0-SNAPSHOT
[INFO] +- io.helidon.microprofile.bundles:helidon-microprofile-1.2:jar:0.10.5:compile
[INFO] |  +- io.helidon.microprofile.bundles:helidon-microprofile-1.1:jar:0.10.5:compile
[INFO] |  |  +- io.helidon.microprofile.server:helidon-microprofile-server:jar:0.10.5:compile
[INFO] |  |  |  +- org.jboss.weld.se:weld-se-core:jar:3.0.3.Final:compile
[INFO] |  |  |  |  +- org.jboss.weld.environment:weld-environment-common:jar:3.0.3.Final:compile
[INFO] |  |  |  |  |  \- org.jboss.weld:weld-core-impl:jar:3.0.3.Final:compile
[INFO] |  |  |  |  |     +- org.jboss.weld:weld-api:jar:3.0.SP2:compile
[INFO] |  |  |  |  |     +- org.jboss.weld:weld-spi:jar:3.0.SP2:compile
[INFO] |  |  |  |  |     +- org.jboss.spec.javax.el:jboss-el-api_3.0_spec:jar:1.0.7.Final:compile
[INFO] |  |  |  |  |     +- org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.2_spec:jar:1.0.0.Final:compile
[INFO] |  |  |  |  |     \- org.jboss.logging:jboss-logging:jar:3.2.1.Final:compile
[INFO] |  |  |  |  +- org.jboss.weld.probe:weld-probe-core:jar:3.0.3.Final:compile
[INFO] |  |  |  |  \- org.jboss.classfilewriter:jboss-classfilewriter:jar:1.2.1.Final:compile
[INFO] |  |  |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  |  |  +- org.slf4j:slf4j-jdk14:jar:1.7.25:compile
[INFO] |  |  |  +- io.helidon.webserver:helidon-webserver-netty:jar:0.10.5:compile
[INFO] |  |  |  |  +- io.helidon.common:helidon-common-reactive:jar:0.10.5:compile
[INFO] |  |  |  |  +- io.netty:netty-codec-http:jar:4.1.22.Final:compile
[INFO] |  |  |  |  |  \- io.netty:netty-codec:jar:4.1.22.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-handler:jar:4.1.22.Final:compile
[INFO] |  |  |  |  |  +- io.netty:netty-buffer:jar:4.1.22.Final:compile
[INFO] |  |  |  |  |  |  \- io.netty:netty-common:jar:4.1.22.Final:compile
[INFO] |  |  |  |  |  \- io.netty:netty-transport:jar:4.1.22.Final:compile
[INFO] |  |  |  |  |     \- io.netty:netty-resolver:jar:4.1.22.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-codec-http2:jar:4.1.22.Final:compile
[INFO] |  |  |  +- io.helidon.webserver:helidon-webserver-jersey:jar:0.10.5:compile
[INFO] |  |  |  |  +- org.glassfish.jersey.core:jersey-server:jar:2.26:compile
[INFO] |  |  |  |  |  +- org.glassfish.jersey.core:jersey-client:jar:2.26:compile
[INFO] |  |  |  |  |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  |  |  |  \- io.projectreactor:reactor-core:jar:3.1.5.RELEASE:compile
[INFO] |  |  |  |     \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |  |  |  +- org.glassfish.jersey.ext.cdi:jersey-weld2-se:jar:2.26:compile
[INFO] |  |  |  |  \- org.glassfish.jersey.ext.cdi:jersey-cdi1x:jar:2.26:compile
[INFO] |  |  |  +- org.glassfish.jersey.inject:jersey-hk2:jar:2.26:compile
[INFO] |  |  |  |  \- org.glassfish.hk2:hk2-locator:jar:2.5.0-b42:compile
[INFO] |  |  |  |     +- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b42:compile
[INFO] |  |  |  |     +- org.glassfish.hk2:hk2-api:jar:2.5.0-b42:compile
[INFO] |  |  |  |     +- org.glassfish.hk2:hk2-utils:jar:2.5.0-b42:compile
[INFO] |  |  |  |     \- org.javassist:javassist:jar:3.22.0-CR2:compile
[INFO] |  |  |  \- org.glassfish.jersey.media:jersey-media-json-processing:jar:2.26:compile
[INFO] |  |  |     \- org.glassfish:jsonp-jaxrs:jar:1.1.1:compile
[INFO] |  |  +- io.helidon.microprofile.config:helidon-microprofile-config:jar:0.10.5:compile
[INFO] |  |  |  +- io.helidon.config:helidon-config-bundle:jar:0.10.5:compile
[INFO] |  |  |  |  +- io.helidon.config:helidon-config:jar:0.10.5:compile
[INFO] |  |  |  |  +- io.helidon.config:helidon-config-hocon:jar:0.10.5:compile
[INFO] |  |  |  |  |  \- com.typesafe:config:jar:1.3.3:compile
[INFO] |  |  |  |  \- io.helidon.config:helidon-config-yaml:jar:0.10.5:compile
[INFO] |  |  |  |     \- org.yaml:snakeyaml:jar:1.19:compile
[INFO] |  |  |  \- io.helidon.security:helidon-security-tools-config:jar:0.10.5:compile
[INFO] |  |  |     +- io.helidon.common:helidon-common-key-util:jar:0.10.5:compile
[INFO] |  |  |     |  \- io.helidon.common:helidon-common-configurable:jar:0.10.5:compile
[INFO] |  |  |     \- javax.xml.bind:jaxb-api:jar:2.3.0:compile
[INFO] |  |  \- io.helidon.microprofile.config:helidon-microprofile-config-cdi:jar:0.10.5:compile
[INFO] |  +- io.helidon.microprofile.health:helidon-microprofile-health-core:jar:0.10.5:compile
[INFO] |  |  +- org.eclipse.microprofile.config:microprofile-config-api:jar:1.2.1:compile
[INFO] |  |  |  \- org.osgi:org.osgi.annotation.versioning:jar:1.0.0:compile
[INFO] |  |  \- org.eclipse.microprofile.health:microprofile-health-api:jar:1.0:compile
[INFO] |  |     \- javax.inject:javax.inject:jar:1:compile
[INFO] |  +- io.helidon.microprofile.health:helidon-microprofile-health-checks:jar:0.10.5:compile
[INFO] |  \- io.helidon.microprofile.metrics:helidon-microprofile-metrics-cdi:jar:0.10.5:compile
[INFO] |     +- javax.enterprise:cdi-api:jar:2.0:compile
[INFO] |     |  +- javax.el:javax.el-api:jar:3.0.0:compile
[INFO] |     |  \- javax.interceptor:javax.interceptor-api:jar:1.2:compile
[INFO] |     +- io.helidon.microprofile.metrics:helidon-microprofile-metrics:jar:0.10.5:compile
[INFO] |     \- io.helidon.microprofile.metrics:helidon-metrics-se:jar:0.10.5:compile
[INFO] |        +- org.eclipse.microprofile.metrics:microprofile-metrics-api:jar:1.1:compile
[INFO] |        +- io.helidon.common:helidon-common:jar:0.10.5:compile
[INFO] |        +- io.helidon.webserver:helidon-webserver:jar:0.10.5:compile
[INFO] |        |  \- io.helidon.common:helidon-common-http:jar:0.10.5:compile
[INFO] |        \- io.helidon.webserver:helidon-webserver-json:jar:0.10.5:compile
[INFO] +- org.glassfish.jersey.media:jersey-media-json-binding:jar:2.26:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-common:jar:2.26:compile
[INFO] |  |  +- javax.ws.rs:javax.ws.rs-api:jar:2.1:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.1:compile
[INFO] |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.5.0-b42:compile
[INFO] |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  +- org.glassfish:javax.json:jar:1.1.2:compile
[INFO] |  |  \- javax.json:javax.json-api:jar:1.1.2:compile
[INFO] |  +- org.eclipse:yasson:jar:1.0:compile
[INFO] |  \- javax.json.bind:javax.json.bind-api:jar:1.0:compile
[INFO] +- org.jboss:jandex:jar:2.0.4.Final:runtime
[INFO] +- javax.activation:javax.activation-api:jar:1.2.0:runtime
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.0.1:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.0.0:test
[INFO] |  \- org.junit.platform:junit-platform-commons:jar:1.0.1:test
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.0.1:test
[INFO] |  \- org.junit.platform:junit-platform-engine:jar:1.0.1:test
[INFO] +- com.oracle.helidon:EnvoyTrace:jar:1.1:compile
[INFO] +- io.opentracing:opentracing-api:jar:0.32.0:compile
[INFO] +- io.opentracing:opentracing-util:jar:0.32.0:compile
[INFO] |  \- io.opentracing:opentracing-noop:jar:0.31.0:compile
[INFO] +- io.opentracing.contrib:opentracing-cdi:jar:0.1.0:compile
[INFO] +- io.opentracing.contrib:opentracing-tracerresolver:jar:0.1.7:compile
[INFO] \- io.opentracing.contrib:opentracing-ejb:jar:0.0.8:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.416 s
[INFO] Finished at: 2019-05-09T15:11:53-04:00
[INFO] ------------------------------------------------------------------------

**Comment by objectiser** [comment]
@sherwoodzern You haven't included the Jaeger java client - this means as there is no tracer available it will return the `noop` implementations.

**Comment by pavolloffay** [comment]
It seems you are using  `io.helidon` and not jaeger at all. Perhaps the issue should be opened against helidon. 

If you decide to use Jaeger (assumig it works with helidon) and you run into the issues please reopen the ticket.

**Comment by sherwoodzern** [comment]
io.helidon has nothing to do with the tracing. io.helidon is the Oracle Java SE / MP for building microservices in Java. I've added the jaeger-client and now I'm getting the following ClassCastException.

java.lang.ClassCastException: io.opentracing.propagation.TextMapExtractAdapter cannot be cast to io.opentracing.propagation.TextMap
	at io.jaegertracing.internal.propagation.B3TextMapCodec.extract(B3TextMapCodec.java:50)
	at io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExtractorDecorator.extract(PropagationRegistry.java:57)
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:198)
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:61)
	at io.opentracing.util.GlobalTracer.extract(GlobalTracer.java:204)
Can somebody please let me know which versions of io.opentracing and io.jaegertracing should be used together?

**Comment by pavolloffay** [comment]
Well, you were using helidon Microprofile-OpenTracing implementation and 
```
[INFO] +- com.oracle.helidon:EnvoyTrace:jar:1.1:compile
```

Now you are using wrong Jaeger version. You have to use one with support for OpenTracing 0.31.0 ejg jaeger-client-java 0.34.0 or earlier versions.

**Comment by sherwoodzern** [comment]
The name of that jar file is misleading. It has nothing to do with tracing. It just captures the b3 headers. I attempted using the 0.34.0 release and I get a ClassCastException. I've also tried versions prior to 0.34.0 and still get the ClassCastException.

May 10, 2019 9:49:07 AM io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExtractorDecorator extract
WARNING: Error when extracting SpanContext from carrier. Handling gracefully.
java.lang.ClassCastException: io.opentracing.propagation.TextMapExtractAdapter cannot be cast to io.opentracing.propagation.TextMap
	at io.jaegertracing.internal.propagation.B3TextMapCodec.extract(B3TextMapCodec.java:50)
	at io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExtractorDecorator.extract(PropagationRegistry.java:57)
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:216)
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:61)
	at io.opentracing.util.GlobalTracer.extract(GlobalTracer.java:204)

I'm more than happy to have a conference call to discuss this. This really shouldn't be this difficult. I'm sure there is some secret sauce, but identifying that secret sauce in a trial and error approach is not productive.

**Comment by pavolloffay** [comment]
There is a mismatch on the classpath probably. Assure that OT APIs and implementations use the same version
```
[INFO] +- io.opentracing:opentracing-api:jar:0.32.0:compile
[INFO] +- io.opentracing:opentracing-util:jar:0.32.0:compile
[INFO] | - io.opentracing:opentracing-noop:jar:0.31.0:compile
[INFO] +- io.opentracing.contrib:opentracing-cdi:jar:0.1.0:compile
```

**Comment by sherwoodzern** [comment]
I explicitly specified the io.opentracing:opentracing-noop to 0.32.0. Previously, I was not specifying the noop library. Unfortunately, even explicitly specifying the 0.32.0 release made no difference. There are only 2 versions of opentracing-cdi; the 0.1.0 and the 0.0.2 release. The 0.0.2 release is 18 months old; therefore, I don't think it would be relevant.  

Here's my question. Should I remove all of the io.opentracing and just use Jaeger tracing libraries? If so, what are the recommended Jaeger versions to use. Obviously, I want to do everything with CDI; therefore, if I remove the opentracing will CDI still work?

**Comment by pavolloffay** [comment]
If the CDI is old then you have only one option - use OpenTracing 0.31.0 compatible version of your instrumentation libraries and jaeger client.

**Comment by sherwoodzern** [comment]
I really appreciate your time on this. What do you mean if the CDI is old then you have only one option? The CDI I'm using is the most recent version that is available.  I apologize for all of the questions, but isn't CDI the recommended approach for doing this? I'm pretty sure it even mentions in the documentation to use CDI; therefore, shouldn't the most recent version of CDI be compatible? I'm sure I am not the only one that has attempted to accomplish this use case; therefore, what was the recommended versions of the various libraries to accomplish this?

**Comment by pavolloffay** [comment]
I meant CDI instrumentation - `opentracing-cdi`. Just make sure all opentracing libraries use the same API version. You are getting exceptions because there were breaking changes in the API and you have different versions on classpath.

**Comment by sherwoodzern** [comment]
I'm using all of the same io.opentracing versions across all of the different artifact-ids. However, the io.opentracing-contrib all have different version numbers. There are not identical version numbers for the artifact-ids across the io.opentracing.contrib group.  Therefore, I'm not sure how one can make sure the versions are compatible.  Instead of using the io.opentracing group and artifacts should one use solely io.jaegertracing group and artifacts? Is there CDI group and artifacts for pure jaeger group and artifacts?

**Comment by pavolloffay** [comment]
>  However, the io.opentracing-contrib all have different version numbers. 

I suggest looking at the source code or using dependency tree to get the API version.

**Comment by sherwoodzern** [comment]
Correct me if I'm wrong, based upon your answer there is no one source of truth as to which versions work together. As a developer, I have to be lucky and stumble across the right combination.  Am I off base here? 
Are there CDI libraries for pure Jaeger CDI? In other words, instead of using the io.opentracing interfaces I would just completely rely upon the concrete classes of Jaeger.

**Comment by pavolloffay** [comment]
> there is no one source of truth as to which versions work together. 

In maven you can use `dependency:tree` to find out what libraries and versions are on your classpath. All the opentracing libraries are open sourced, one can have a look and see what versions are using what versions.

I think a bom with all instrumentations would help, however we do not have it.
