### ISSUE TITLE
Incorrect RELEASE description

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#632]
Currently, step 3 is `git tag release-0.20.0 && git push origin release-0.20.0`.

However, per earlier conversation, we recommend all maintainers to map `origin` to their own fork rather than the upstream repository, to avoid accidental creation of transient branches. E.g. this is the recommended setup:
```shell
$ git remote -v | grep -E '(origin|upstream)'
origin	git@github.com:yurishkuro/jaeger-client-java.git (fetch)
origin	git@github.com:yurishkuro/jaeger-client-java.git (push)
upstream	git@github.com:jaegertracing/jaeger-client-java.git (fetch)
upstream	git@github.com:jaegertracing/jaeger-client-java.git (push)
```

I think in this situation the proper release instruction would be to push the tag to `upstream`.

@pavolloffay thoughts?

**Comment by csantanapr** [comment]
I agree with this, it’s a standard practice and convention for the central repo

**Comment by pavolloffay** [comment]
+1. It's just a cosmetic change. Folks might use different names for upstream the point is to document that tag has to be pushed to this repo.
