### ISSUE TITLE
Spans are not connected after upgrading Java Jaeger Client

### ISSUE THREAD

**Issue by lubinson** [jaegertracing/jaeger-client-java#635]
Dear Community, 

Different services spans can not be connected after upgrade below old version
```
opentracing-spring-jaeger-starter:0.1.4
opentracing-spring-web-starter:0.3.3
```
to new version
```
opentracing-spring-jaeger-starter:2.0.0
opentracing-spring-web-starter:2.1.0
```

Before the upgrading, everything is ok. 

For example, Service A call B and C, we inject the tracing context to the HTTP header when calling Service B and C.  The sampler is ratelimiting 1. Span `Calling Service B` and `Calling Service C` are created in Service A and under the root span `Service A`.  Span `Service B` is recorded in service B. Span `Service C` is recorded in service C. 

Before upgrading, we got below three level tracing: one root span, two level 2 spans and two level 3 spans, 
```
Service A
  Calling Service B
    Service B
  Calling Service C
    Service C
```
Even we changed the sampler to any, above tracing is working as expected. 

After upgrading, we can only got 1 root span and two level 2 spans which all belong to service A:
```
Service A
  Calling Service B
  Calling Service C
```
But when we tried to change the sampler to const 1 in Service A. we got three individual tracing:
1: 
```
Service A
  Calling Service B
  Calling Service C
```

2:
```
GET
  Service B
```

3:
```
POST
  Service C
```

in tracing 2 and 3, there has two unknown span: `GET` and `POST`. When looked at the span detail. I found the field `Component` has the value `java-spring-webclient` which is also not seen in old version. I am guessing the Spring Webclient created a root span solely. I didn't look at the http packet to see what exactly the header are, but from the result, I think Service B and Service C treat the span as the root span. Is our injected span got overwritten? and also sometimes the results related to the sampler?

I am not sure this is the changes to new version or other changes resulted in the weird behavior. Thanks for your information and opinion.

**Comment by yurishkuro** [comment]
I do not believe it's an issue with Jaeger client, but with instrumentation. Please open a ticket in https://github.com/opentracing-contrib/java-spring-web

**Comment by lubinson** [comment]
@yurishkuro Thanks for your reminder.
