### ISSUE TITLE
try (Scope ...) { ... } pattern ill suited for catching errors

### ISSUE THREAD

**Issue by doctorpangloss** [jaegertracing/jaeger-client-java#636]
## Requirement - what kind of business use case are you trying to solve?

This is tracing used to diagnose issues in a complex, real-time video game server. Exception tracing is very valuable here.

## Problem

Here is actual code from a Java-based game engine server that I've begun to instrument using the most contemporary pattern.

```
Tracer tracer = GlobalTracer.get();
Span span = tracer.buildSpan("ServerGameContext/resume")
		.asChildOf(getSpanContext())
		.start();
try (Scope s = tracer.activateSpan(span)) {
	if (!isRunning()) {
		endGame();
	}
	while (!updateAndGetGameOver()) {
		span.log(ImmutableMap.of("turn", getTurn(), "activePlayerId", getActivePlayerId()));
		if (!isRunning()) {
			break;
		}
		startTurn(getActivePlayerId());
		while (takeActionInTurn()) {
			span.log(ImmutableMap.of("turn", getTurn(), "activePlayerId", getActivePlayerId(), "actionsThisTurn", getActionsThisTurn()));
			if (!isRunning()) {
				break;
			}
		}
		if (getTurn() > GameLogic.TURN_LIMIT) {
			break;
		}
	}
	endGame();
} catch (Throwable t) {
	// TODO: Log the error
	throw t;
} finally {
	span.finish();
}
```

Observe `// TODO: Log the error`. At this line of code, the scope has actually been closed, due to the semantics of **try-with-resources**, which is undesired. This is an example of an implementation that will fail, a common pattern:

```
Span span = GlobalTracer.get().scopeManager().activeSpan();
if (span == null) {
	return;
}
Tags.ERROR.set(span, true);
span.log(ImmutableMap.of(Fields.EVENT, "error", Fields.ERROR_OBJECT, throwable, Fields.MESSAGE, throwable.getMessage()));
```

Naturally, passing the `span` that was defined already won't work, because it's closed.

## Proposal

Author a pattern on your `README` for how people should actually use this, because I keep running into deprecated code!

## Workaround

Do not use **try-with-resources**.

**Comment by yurishkuro** [comment]
a) the code you showed is the recommended usage pattern. There's no issue with Scope being closed, because the span is still not finished. Scope just controls which span is active on the stack.

b) which README are you referring to? The usage patterns are documented in opentracing-java repo, not in the Jaeger client.

**Comment by doctorpangloss** [comment]
The active span is null when retrieved from the global tracer inside the try block. Is that the intended behavior?

**Comment by yurishkuro** [comment]
it may or may not be, depending on the call pattern, but there is no need to retrieve active span since it's accessible via local variable defined on L2.
