### ISSUE TITLE
Broken  Javadoc links

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#637]
- https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/README.md
- https://github.com/jaegertracing/jaeger-client-java/blob/master/README.md

**Comment by jpkrohling** [comment]
Both links are working for me right now (Firefox and Chrome). @objectiser mentioned that it's also working for him.

**Comment by yurishkuro** [comment]
they  work for me too now. closing.
