### ISSUE TITLE
Getting two traces on jaeger UI when I set a custom tag like customerID. Expecting a single trace. Is this possible ?

### ISSUE THREAD

**Issue by TarunGosain** [jaegertracing/jaeger-client-java#638]

**Comment by TarunGosain** [comment]
I am beginner using opentracing with Jaeger in Java. I need to set custom tags in the span like customerId, which I am doing this way:

Span span =tracer.buildSpan("hello service").start();
span.setTag("customerId", customerId);
span.finish();
With this approach I get two traces on the Jaeger UI: One with my custom tag and the standard other without custom tag. My expectation is only to get single trace with a span having standard and custom tag.

**Comment by objectiser** [comment]
When you say "standard" tags, can you give us an example of what you mean? Possibly include a screenshot of the spans.

It sounds like your app has some instrumentation already installed, that is creating one of the spans implicitly, but then you are also creating a second span explicitly.

**Comment by TarunGosain** [comment]
By standard tags I meant _http.status_code=200, span.kind=server,http.url, http_metho_d.....
<img width="698" alt="traces" src="https://user-images.githubusercontent.com/14215540/61778764-fee13480-ae1c-11e9-8391-bf0ee0d57625.PNG">
These 2 trace are generated for a single service call. First trace in the image is  because to have my custom tag customerId I am using the following code and the second one is implicit from Jaeger
[Span span =tracer.buildSpan("hello service").start();
span.setTag("customerId", customerId);
span.finish();](url)
If I don't use this code i just get expected one trace for one call but without my custom tag customerId. So the question is what is the best way to have a custom tag so that this scenario of 2 traces for a single call does not happen.

**Comment by objectiser** [comment]
Have a look at this [tutorial section](https://github.com/yurishkuro/opentracing-tutorial/tree/master/java/src/main/java/lesson02#propagate-the-in-process-context) which shows how to make your "hello service" span a child of the span created for your REST endpoint.

This will create a single trace with two spans - so your custom tag would still be associated with the "hello service" span.

If you want to add your custom tag to the "GET" span, then you can use the tracer to get access to the active span, e.g. `tracer.activeSpan()`.
