### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-client-java#639]
## Requirement - what kind of business use case are you trying to solve?

Release 1.0.0 of Jaeger java client.

## Problem - what in Jaeger blocks you from solving the requirement?

Has been 0.x release for a long time, and is now stable. The go and python clients are > 2.x.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Release the current master (0.35.5) as 1.0.0.

**Comment by yurishkuro** [comment]
sgtm, but are there any PRs we want to merge first?

Bump OpenTracing to 0.33.0 #623 looks  like a strong candidate
