### ISSUE TITLE
Exception in thread "jaeger.RemoteReporter-QueueProcessor" java.lang.NoSuchMethodError: io.jaegertracing.agent.thrift.Agent$Client.sendBaseOneway

### ISSUE THREAD

**Issue by Nikesht** [jaegertracing/jaeger-client-java#644]
## Requirement - what kind of business use case are you trying to solve?

I am trying to integrate Jaeger java client to trace my application flow. I am running jaeger client on my windows machine.
## Problem - what in Jaeger blocks you from solving the requirement?
I am trying to create a simple trace to check how traces of my application will look like. I am following https://github.com/yurishkuro/opentracing-tutorial.  I can see tracer and span object to be created in my debugger screen but i am not seeing any span in UI. Other sample application(from Yuri Shkuro's OpenTracing tutorials) is sending span properly. 
I can see following exception in my application :

Exception in thread "jaeger.RemoteReporter-QueueProcessor" 
java.lang.NoSuchMethodError: io.jaegertracing.agent.thrift.Agent$Client.sendBaseOneway
(Ljava/lang/String;Lorg/apache/thrift/TBase;)V
        at io.jaegertracing.agent.thrift.Agent$Client.send_emitBatch(Agent.java:70)
        at io.jaegertracing.agent.thrift.Agent$Client.emitBatch(Agent.java:63)
        at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:64)
        at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:110)
        at io.jaegertracing.internal.reporters.RemoteReporter$FlushCommand.execute(RemoteReporter.java:154)
        at io.jaegertracing.internal.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:173)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jpkrohling** [comment]
Can you give more details? Which lesson is failing for you? How does your `pom.xml` look like? Are you able to create a repository somewhere with the full project code?

This seems like a version mismatch somewhere. I tried to run Yuri's solution for lesson03, and it did work as expected to me:

![image](https://user-images.githubusercontent.com/13387/62463502-79e60b80-b78a-11e9-8ddd-0c31542c86b1.png)


```console
$ ./run.sh lesson03.solution.Formatter server
...
INFO  [2019-08-05 12:06:05,327] org.eclipse.jetty.server.Server: Started @3850ms

$ ./run.sh lesson03.solution.Publisher server
...
INFO  [2019-08-05 12:06:07,420] org.eclipse.jetty.server.Server: Started @1952ms

$ $ ./run.sh lesson03.solution.Hello Bryan
14:07:25.871 [main] DEBUG io.jaegertracing.thrift.internal.senders.ThriftSenderFactory - Using the UDP Sender to send spans to the agent.
14:07:25.897 [main] DEBUG io.jaegertracing.internal.senders.SenderResolver - Using sender UdpSender()
14:07:25.918 [main] INFO io.jaegertracing.Configuration - Initialized tracer=JaegerTracer(version=Java-0.32.0, serviceName=hello-world, reporter=CompositeReporter(reporters=[RemoteReporter(sender=UdpSender(), closeEnqueueTimeout=1000), LoggingReporter(logger=Logger[io.jaegertracing.internal.reporters.LoggingReporter])]), sampler=ConstSampler(decision=true, tags={sampler.type=const, sampler.param=true}), tags={hostname=caju, jaeger.version=Java-0.32.0, ip=192.168.0.17}, zipkinSharedRpcSpan=false, expandExceptionLogs=false, useTraceId128Bit=false)
14:07:26.151 [main] INFO io.jaegertracing.internal.reporters.LoggingReporter - Span reported: db4f639b3832db3c:8096de99fecdda28:db4f639b3832db3c:1 - formatString
14:07:26.161 [main] INFO io.jaegertracing.internal.reporters.LoggingReporter - Span reported: db4f639b3832db3c:f913bfde692d2cb6:db4f639b3832db3c:1 - printHello
14:07:26.161 [main] INFO io.jaegertracing.internal.reporters.LoggingReporter - Span reported: db4f639b3832db3c:db4f639b3832db3c:0:1 - say-hello
```

**Comment by Nikesht** [comment]
Hi,
I am able to run the application form yuri's example but when i am trying to integrate it with my application i am getting above mentioned exception. 
 public final String getSystemState() throws Exception
    {
      Span span = tracer.buildSpan("OpticsSystemState-getSystemState()").start();
        .................................................................................................................................................................
        ................................................................................................................................................................
.            other related code
        .................................................................................................................................................................
        .................................................................................................................................................................
            span.finish();
            return ossClient;
        //}
    }

I can see in debugger screen that span has been created and attached with tracer. Am i missing some jars or other dependencies ?
As this is legacy code built on Ant build, i have downloaded required jars instead of using pom.xml

![image](https://user-images.githubusercontent.com/8111019/62469592-30131a80-b7b6-11e9-85b7-e086167b0fbf.png)

**Comment by jpkrohling** [comment]
Your Jaeger Thrift module is at 1.0.0, while the other Jaeger dependencies are at 0.32.0. Try using the same version number for all `jaeger-*` dependencies.

**Comment by Nikesht** [comment]
I was using thrift module 0.32.0 earlier, after this issue i tried with 1.0.0. It is throwing same exceptions in both cases.

**Comment by yurishkuro** [comment]
> java.lang.NoSuchMethodError: io.jaegertracing.agent.thrift.Agent$Client.sendBaseOneway

this looks like a mismatch between Thrift version used to compile Jaeger classes and Thrift lib you are linking against. I believe we have a version of Jaeger lib with shaded Thrift, you may want to try that.

**Comment by Nikesht** [comment]
can you please point me to that ? or should i look for thrift jars from lower versions than 0.32.0 ?
I downloaded these jars in single package from official jaeger repo.

**Comment by yurishkuro** [comment]
It's described in the readme: 
https://github.com/jaegertracing/jaeger-client-java#thrift-version-conflicts

**Comment by Nikesht** [comment]
![image](https://user-images.githubusercontent.com/8111019/62538979-b5a7d080-b871-11e9-9b69-3f80e2331200.png)
I modified my pom.xml to 
<groupId>io.jaegertracing</groupId>
            <artifactId>jaeger-client</artifactId>
            <classifier>shadow</classifier>
            <version>0.32.0</version>
and then ran :
mvn install dependency:copy-dependencies
but it seems that shadow version is not available on maven repo anymore.

**Comment by objectiser** [comment]
If you want to remain compatible with opentracing 0.31, you could download the 0.34 version of the jaeger artifacts - which does have a shadow jar for jaeger-thrift: https://repo1.maven.org/maven2/io/jaegertracing/jaeger-thrift/0.34.0/

**Comment by yurishkuro** [comment]
#645 to investigate missing shadow artifact
