### ISSUE TITLE
[jaeger-thrift] Shadow artifact went missing

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#645]
http://central.maven.org/maven2/io/jaegertracing/jaeger-thrift/0.34.0/ contains `jaeger-thrift-0.34.0-shadow.jar`, but http://central.maven.org/maven2/io/jaegertracing/jaeger-thrift/0.35.0/ no longer does. There are no relevant changes mentioned in the changelog.

cc @pavolloffay @jpkrohling

**Comment by jpkrohling** [comment]
@pavolloffay did some changes to the build between those versions. The commit af38f1b6ec70c7f1b252a17ce1079588a647e011 looks suspicious, as it bumps the plugin `com.github.johnrengelman.shadow` from `2.0.4` to `5.0.0`. Perhaps there's a new way to specify shadow jars?

**Comment by jn1z73** [comment]
@pavolloffay -- it looks like Shadow version 5.0.0 requires Java 7+. But jaeger-client-java targets Java 6+. Wouldn't this cause the issue?

From https://github.com/johnrengelman/shadow:
```NOTE: Shadow v5.+ is compatible with Gradle 5.0+ and Java 7+ only.```
