### ISSUE TITLE
Graceful reporting degradation for large spans

### ISSUE THREAD

**Issue by epkugelmass** [jaegertracing/jaeger-client-java#646]
## Requirement - what kind of business use case are you trying to solve?

jaeger-client-java drops spans when they exceed some (wire-encoded) size. By default this is ThriftUdpTransport#MAX_PACKET_SIZE, slightly less than the maximum size of a UDP datagram. In my experience, this is most commonly an issue when logs are aggressively attached to a particular span.

Instead of dropping the entire span, I suggest jaeger-client-java prune elements until the encoded span is below the configured maximum size. This way, the span will still be observable in the UI and backing datastore. This is a better user experience than having the span disappear entirely.

## Problem - what in Jaeger blocks you from solving the requirement?

Any implementation would need to modify or access internal Jaeger classes.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Strip the following and retry when this condition is hit: https://github.com/jaegertracing/jaeger-client-java/blob/f1a7ca91af05206b3c47573689331a1fafec16de/jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/senders/ThriftSender.java#L57
1) Strip all logs and set a tag "internal.dropped.logs = true"
2) If condition still fails, strip all tags and set a tag "internal.dropped.tags = true"

## Any open questions to address

Should this be an opt-in feature?

**Comment by jpkrohling** [comment]
I think this is a really cool idea. I'd even consider enabling it by default.

**Comment by yurishkuro** [comment]
Yeah, we discussed various truncation approaches in the past (I think Node.js client repo has a similar ticket). One problem is that there are many different ways of doing truncation, a default implementation might not be suitable to everyone.

**Comment by wuyupengwoaini** [comment]
Firstly,I think jaeger-ui should support dropped span, and then  jaeger client  provided a interface and a default implementation

**Comment by epkugelmass** [comment]
I want to make sure I understand @wuyupengwoaini 's suggestion clearly.

> jaeger-ui should support dropped span

I believe jaeger-ui should warn about dropped span data/truncated spans (not dropped spans -- Jaeger cannot know about a span that is truly gone) just as it currently warns about other anomalies. See https://github.com/jaegertracing/jaeger-ui/blob/126f42c2c7ad192d51876de4e293af55405ca655/packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/SpanDetail/index.tsx#L119

> jaeger client provided a interface and a default implementation

@yurishkuro suggested the same. I believe it would be inappropriate to expose details of the serialization implementation ("how many bytes would I save by ditching tags"). I see a few remaining options. First, allow a generic interface that accepts a span and returns a new one. This has quite a few problems. It presents the temptation for a generic "rewrite your span" facility, which this is very much not. It doesn't easily represent tiered degradation (first drop logs, then drop tags). And it doesn't tightly associate adjustments to the span with specific, informative "internal" tags as I suggested in the issue description.

I think a stronger option involves an Enum of drop-able components. There's no interface. Instead we offer both programmatic (Enum[]) and environment variable based configuration. Components are dropped in the order given until the span can be sent. If the list is exhausted without making the span fit to send, the span is dropped.

> And also dropped tags can be configured in jaeger-ui.

I'm not entirely sure what this means. If you are suggesting that the tags-to-be-dropped be configured via the UI, I don't think that's a good idea. Jaeger today does not communicate information "backward" from the UI to the collectors, agents, or client libraries. And not every client library would necessarily support this behavior. I am only suggesting it for the Java client (as that's the one I care about most).
