### ISSUE TITLE
could jaeger add span lifecycle extensions?

### ISSUE THREAD

**Issue by wuyupengwoaini** [jaegertracing/jaeger-client-java#647]
## Requirement - what kind of business use case are you trying to solve?
Whether it is a synchronous scene or an asynchronous scene, I want to record the traceid in the log. MDC is currently used to solve the problem of printing traceid in the log. But you need to manually put the traceid in the MDC. In different scenarios, you need to use MDC to put traceid in different components. For example, http services need to put traceid in filter, which is similar in netty. But no matter which method is more troublesome

## Problem - what in Jaeger blocks you from solving the requirement?
Jaeger lacks extension for the span lifecycle.If provided,we can put traceId in MDC when the span started and 
there is no need to process different component

## Proposal - what do you suggest to solve the problem or improve the existing situation?

like [sofa-tracer](https://github.com/sofastack/sofa-tracer/blob/master/tracer-extensions/src/main/java/com/alipay/common/tracer/extensions/log/MDCSpanExtension.java),jaeger provides span lifecycle extensions

**Comment by objectiser** [comment]
You could take a look at https://github.com/opentracing-contrib/java-api-extensions - it is used by the https://github.com/opentracing-contrib/java-metrics project to create metrics related to spans, so uses the span lifecycle.

**Comment by wuyupengwoaini** [comment]
@objectiser  Thanks

**Comment by yurishkuro** [comment]
also, specifically for logging trace IDs, this worked for me: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/master/Chapter11/exercise1/lib/src/main/java/lib/MDCScopeManager.java

**Comment by wuyupengwoaini** [comment]
@yurishkuro Thanks! It's a good way.But It is ok when in asynchronous scene? Or When I instrument application only using span  instead of scope,Does it work well?

**Comment by yurishkuro** [comment]
it works if you use ScopeManager mechanism to pass context within your app (whether it's sync or async doesn't matter).
