### ISSUE TITLE
Augment environment variables/system properties to use hierarchical named properties 

### ISSUE THREAD

**Issue by rlubke** [jaegertracing/jaeger-client-java#671]
## Requirement - what kind of business use case are you trying to solve?

It is currently difficult to give very specific security configuration for JAEGER_* environment variables/system properties within the security.properties file.

## Problem - what in Jaeger blocks you from solving the requirement?

Property or environment permissions have the following restriction:

>  Also, an asterisk may appear at the end of the name, following a ".", or by itself, to signify a 
> wildcard match. For example: "java.*" and "*" signify a wildcard match, while "*java" and 
> "a*b" do not.

Currently, Jaeger defines all environment variables/system properties as **JAEGER_*** which makes it impossible to define a permission for those properties only, and I'm forced to use "*" for the permission grant, which is too wide a scope.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

In addition to supporting the existing environment variables/system properties, create a set of hierarchical named properties.  For example, JAEGER_SERVICE_NAME, would have an associated hierarchical name of jaeger.service.name.

With the above change, we would be able to add permissions along the lines of

    `permission java.lang.RuntimePermission "getenv.jaeger.*";`

and/or

    `permission java.util.PropertyPermission "jaeger.*", "read";`

**Comment by pavolloffay** [comment]
Instead of using wildcard could be the full names used e.g. `permission java.lang.RuntimePermission "getenv.jaegerservice";`?
