### ISSUE TITLE
Memory leak in JaegerTracer

### ISSUE THREAD

**Issue by TomasHofman** [jaegertracing/jaeger-client-java#677]
## Requirement - what kind of business use case are you trying to solve?

Basic usage, just registering a JaegerTracer in an application.

## Problem - what in Jaeger blocks you from solving the requirement?

Each JaegerTracer which is created registers a shutdown hook, which purpose is to close the tracer on application exit. This shutdown hook is however not unregistered when the tracer is closed programmatically. This hook holds references to the tracer, so it can't be garbage collected.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Unregister the shutdown hook when the tracer is closed.

## Any open questions to address

Not aware.

**Comment by yurishkuro** [comment]
> Unregister the shutdown hook when the tracer is closed.

Sounds reasonable, would you like to create a PR?

However, overall the tracer is designed to work as a singleton, you're not supposed to keep creating new instances and closing them.

**Comment by TomasHofman** [comment]
Yes, I can create a PR.

This issue is being observed in JBoss EAP application server. The application server creates tracer instances for deployments, or redeployment of the same... So it's a bit different angle.

**Comment by yurishkuro** [comment]
+1

**Comment by TomasHofman** [comment]
Master branch PR: https://github.com/jaegertracing/jaeger-client-java/pull/679
0.34 branch PR: https://github.com/jaegertracing/jaeger-client-java/pull/678
