### ISSUE TITLE
HTTP Client Swallows Span if Size is Greater than Max Payload

### ISSUE THREAD

**Issue by motobeats** [jaegertracing/jaeger-client-java#680]
## Requirement - what kind of business use case are you trying to solve?

Client logging "Span reported" but then not sending to Collector is confusing. If due to over Payload limit the span is being swallowed this message should not appear or a different message about not sending.

> INFO  i.j.i.reporters.LoggingReporter - Span reported: 5eb0e9d742babead:5eb0e9d742babead:0:1 - GET

## Problem - what in Jaeger blocks you from solving the requirement?

No problem per se, just improve transparency of the tracing activity.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

1. If a span is not going to be sent for any reason, log it with the reason.
OR
2. Don't log this message if span isn't going to be sent.

## Any open questions to address

Observed on
Spring Boot 2.1.4 
io.opentracing.contrib.opentracing-spring-jaeger-cloud-starter 1.0.3
io.jaegertracing.jaeger-client 0.33.1

To test, create a span with lots of logs to get over the http-sender.max-payload default of 65K. For my setup, when I get to spans with greater than ~950 log messages I hit this issue. Spans reporting in log but not actually sent. Verified at the Collector and via Wireshark packet capture.

``` groovy
// Span payload size testing
def logCount = 0
1000.times {
     Span span = GlobalTracer.get().buildSpan("payload_size_test").start()
     def messageCount = 1
     logCount.times {
          span.log("adding log number ${messageCount}")
	  messageCount ++
     }
     span.finish()
     logCount ++
}
```

**Comment by yurishkuro** [comment]
We can change the wording to "span finished".

**Comment by motobeats** [comment]
If a span cannot be sent for some reason I would find the logging as such helpful. Rather than having to remember the difference between reported/finished. 

That said, from looking at [HttpSender.java](https://github.com/jaegertracing/jaeger-client-java/blob/f07f1ba92d2b6019c5915330893747be5151ea0f/jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/senders/HttpSender.java) I can't figure out where the size would cause the client not to send.

Maybe java-spring-jaeger's [JaegerAutoConfiguration.java](https://github.com/opentracing-contrib/java-spring-jaeger/blob/f8f921b26b52555ec19da1cd2e0194b151c10d81/opentracing-spring-jaeger-starter/src/main/java/io/opentracing/contrib/java/spring/jaeger/starter/JaegerAutoConfiguration.java) is setting max payload in an unexpected way on L125?

**Comment by hacking-the-system** [comment]
Same problem here, I was losing spans without knowing what was happening until I found this.
