### ISSUE TITLE
Shaded jaeger-thrift is reported missing

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#691]
## Requirement - what kind of business use case are you trying to solve?

Many users prefer to use shaded thrift to avoid version conflicts.

## Problem - what in Jaeger blocks you from solving the requirement?

The README states that a shaded jar is provided via a classifier. However, users from Hadoop ecosystem report that:
(1) IntelliJ doesn't support classifier
(2)  the shaded jar doesn't seem to be published to Maven repository. https://repo1.maven.org/maven2/io/jaegertracing/jaeger-thrift/1.1.0/. Looks like starting from 0.34.1 the shaded jar is no longer available.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Investigate if the publishing is still working. Expand on the instructions on how to use the shaded jar. Perhaps publish a jar without classifier, but with a different artifact name.

**Comment by jojochuang** [comment]
Thanks Yuri for starting this issue!
For information, we are shading Jaeger in Hadoop: https://github.com/apache/hadoop-thirdparty/pull/5
and shading Jaeger in HBase: https://github.com/apache/hbase-thirdparty/pull/13

**Comment by yurishkuro** [comment]
Duplicate of #645
