### ISSUE TITLE
Opentracing with Jaeger in Spring legacy App (xml-based and non spring-boot)

### ISSUE THREAD

**Issue by milankamboya** [jaegertracing/jaeger-client-java#697]
**Need Help**

I am trying opentracing with jaeger.

I have done implementation in spring boot based application. It is working.

But,

I am trying implementation in spring legacy application (xml-based & non spring-boot). In that, it is not working.

I have check this link and try to implement the same but it's not working. 
https://stackoverflow.com/questions/55256948/configuring-jaeger-in-spring-application 

**Are there any good example for spring legacy application which I can refer?
 Also need implementation for RestTemplate in same above legacy application.**

(In my case, fronnt-end will call rest api in spring legacy application and from legacy app, it will call another rest api of spring-boot app through resttemplate.)

I have posted this on gitter group and stackoverflow but no luck.
https://stackoverflow.com/questions/60750487/opentracing-with-jaeger-in-spring-legacy-app-xml-based-and-non-spring-boot

**Comment by pavolloffay** [comment]
This test artifact shows how Spring MVC can be instrumented with open tracing artifacts https://github.com/opentracing-contrib/java-spring-web/tree/master/opentracing-spring-web-itest/mvc

With that instrumentation any OpenTracing client can be used including Jaeger.

As this is not Jaeger java client issue I am closing this.
