### ISSUE TITLE
Supports "jaeger-debug-id" in W3C TraceContextCodec

### ISSUE THREAD

**Issue by quaff** [jaegertracing/jaeger-client-java#699]
## Requirement - what kind of business use case are you trying to solve?
Replace `TextMapCodec` with `TraceContextCodec`

## Problem - what in Jaeger blocks you from solving the requirement?
`jaeger-debug-id` is not extracted in `TraceContextCodec`

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Align `TraceContextCodec` with `TextMapCodec`

**Comment by pavolloffay** [comment]
@quaff would you like to submit a PR?
