### ISSUE TITLE
log Span in JaegerSpan.finishWithDuration

### ISSUE THREAD

**Issue by huehnerlady** [jaegertracing/jaeger-client-java#703]
Hi,

We use Jaeger together with spring rabbit.
We run into the error, that we have thousands of children under the node `<trace-without-root-span>`.

Now we would like to get to the roots of that problem. Unfortunately the JaegerSpan log is semi-helpful.
We just see `Span has already been finished; will not be reported again.` [Source](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerSpan.java#L188)

We would need something similar to [this](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/reporters/LoggingReporter.java#L43):
`Span has already been finished; will not be reported again: 27e8f61cfa256819:9af1f9b3e5631aaf:af13538800afab00:1`

I wanted to do a pull request for changing this, but I am not able to run the test locally and I do not want to submit anything without testing.

Could someone please do the simple adaption to make the warn log useful to us and hopefully others?

**Comment by yurishkuro** [comment]
While adding span IDs to the log is a good call, I am not sure it will be very helpful in your situation. A stacktrace might be more helpful (off by default & configurable).

The problem sounds related to context propagation, like not closing the scope somewhere and always falling back to the same span.

**Comment by huehnerlady** [comment]
Hi,

Many thanks for your answer. I did not mean it to be a help in this case, more that we ran into this while we tried to find the bug and we couldn't see which span that was. 

So for future problems on our side - and for other users - I thought it might make sense to enhance this logging with some more information :)

**Comment by calohmn** [comment]
> While adding span IDs to the log is a good call, I am not sure it will be very helpful in your situation. A stacktrace might be more helpful (off by default & configurable).

IMHO, adding just span **name** and **ID** to the `Span has already been finished; will not be reported again.` log message would already help a lot in many situations!

Right now, when you see random log messages like this, all you can do is look at log timestamps and surrounding log messages to  even get to know which span this is about.
