### ISSUE TITLE
Spans with multiple references have no parent when converted to Thrift

### ISSUE THREAD

**Issue by william-tran** [jaegertracing/jaeger-client-java#705]
## Requirement - what kind of business use case are you trying to solve?

I'm trying to send Jaeger traces through the opentelementry-collector via Thrift HTTP, and out to multiple backends. Some of my traces have spans with multiple parents. Jaeger's UI is tolerant of this situation, but others like Honeycomb expect a parent span for all spans other than the root. See https://github.com/honeycombio/opentelemetry-exporter-go/issues/69

## Problem - what in Jaeger blocks you from solving the requirement?
If there are multiple references, [JaegerThriftSpanConverter](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/reporters/protocols/JaegerThriftSpanConverter.java#L50) sets the parentId to 0. 

However, there's [other parts of Jaeger](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java#L410-L421) that infer the parent to be the first ChildOf reference:

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Maybe this should be clarified in the [otel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/bdf39cb935a6f48badc687daeb78a66dc352761f/specification/overview.md#links-between-spans), that when converting from a list of OpenTracing Span references, if there exists only one child_of reference from the same trace, use that as the parent, otherwise the span will have no parent. Then apply this consistently to any formats that use span.parentId.

**Comment by william-tran** [comment]
Looking at the opentracing shim for otel, the first reference is used as the parent regardless of the reference type: 
https://github.com/open-telemetry/opentelemetry-java/blob/master/opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java

**Comment by pavolloffay** [comment]
Just to clarify are you using maven artifact `jaeger-client-java` to create and send traces to Jaeger?

**Comment by william-tran** [comment]
Yes, this project reproduces the issue: https://github.com/william-tran/tracing-tests
