### ISSUE TITLE
OkHttp dependency causing unintended behavior in Spring Boot applications

### ISSUE THREAD

**Issue by brianrodecap** [jaegertracing/jaeger-client-java#706]
## Requirement

Introducing Jaeger client dependency should not change default Spring Boot behavior

## Problem

Spring components, specifically RestTemplate, appear to leverage the OkHttp library when included as a transitive dependency of jaeger-client, resulting in the auto-injection of the OkHttp3ClientHttpRequestFactory instead of the default SimpleClientHttpRequestFactory.  Unintended behavior changes include 10 second connection and read timeouts, instead of infinite (-1).

### Code
`	@Bean
	public RestTemplate restTemplate(RestTemplateBuilder builder) {
		return builder.build();
	}`

### Before
![default](https://user-images.githubusercontent.com/25912171/80141667-e6eb3c80-8577-11ea-9e2e-c8915ea36e17.PNG)

### After
![okhttp](https://user-images.githubusercontent.com/25912171/80141682-ef437780-8577-11ea-852a-68468bb65634.PNG)

## Proposal

Refactor to remove the dependency, if possible.  See #516

**Comment by yurishkuro** [comment]
One option is to shade okhttp similar to how we shade thrift dependency.

**Comment by yurishkuro** [comment]
Having said that, a couple of comments to the OP:
  * knowing how flexible Spring it, there's probably a mechanism to override which http client it uses instead of relying on auto-discovery
  * it is a good practice to set the timeouts explicitly in your application, instead of relying on defaults (infinite timeout is hardly ever appropriate for a production service).

**Comment by brianrodecap** [comment]
Thank you so much!

You are correct, Spring absolutely provides for explicitly injecting a specific factory.

Regarding timeouts: agreed, but I do have a legit use case for an arbitrarily long-running async request.  Debugging the unexpected behavior change was the impetus for submitting this issue.  Also, I did not take this further to try to determine other behavioral changes beyond RestTemplate, but I strongly suspect there are more impacts in Spring Boot applications.

FYI, my temporary workaround/hack is to exclude the OkHttp dependency.  The following works, and I am still getting traces, indicating that the dependency may already be optional:

`
		<dependency>
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
			<version>2.0.3</version>
			<exclusions>
				<exclusion>
					<groupId>com.squareup.okhttp3</groupId>
					<artifactId>okhttp</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
`
