### ISSUE TITLE
How to configure ipv6 for JAEGER_AGENT_HOST and JAEGER_SAMPLER_MANAGER_HOST_PORT

### ISSUE THREAD

**Issue by prashanthga** [jaegertracing/jaeger-client-java#709]
## Requirement - what kind of business use case are you trying to solve?

Using jaeger all-in-one image for our tracing our java based micro services

## Problem - what in Jaeger blocks you from solving the requirement?
While ipv4 addresses work, we dint see any spans being reported in the Jaeger UI when ipv6 addresses are used for JAEGER_AGENT_HOST and JAEGER_SAMPLER_MANAGER_HOST_PORT.

we need support for ipv6 as a requirement.

**Comment by prashanthga** [comment]
Closing this issue as it worked with correct configuration.

**Comment by yurishkuro** [comment]
Can you elaborate what was incorrect in your first attempt? in case other people run into it.

**Comment by prashanthga** [comment]
Earlier we were using the UDP Sender and we missed configuring the Ipv6 properly for the sampler manager host port , hence this issue was coming. But later UDP Sender works well with Ipv6 address.

However, we have to re-open the issue for the HTTP Sender. When we give the Ipv6 address for the Jaeger end point, the connection is not made to the port 14268 at all. Also we dont see any clude/ logs on the LoggingReporter .

If the HTTP Sender is synchronous, why there are no exceptions thrown to the client ?

**Comment by objectiser** [comment]
@prashanthga The HTTP Sender still uses a queue within the tracer to buffer spans before they are sent to the collector in a batch.

**Comment by prashanthga** [comment]
Okay. So we can view the issues only through the metrics?

Coming to the issue, we observed that Http sender is able to resolve the ipv6 address but throws a socket timeout exception.

We realised we are using link local ipv6 address. Should we replace with global ipv6? Any idea

**Comment by prashanthga** [comment]
Found the root cause:
when we configure the JAEGER_END_POINT with the linked local ipv6 address, this issue happens. This was resolved by configuring the global ipv6 address
