### ISSUE TITLE
Weird reported span duration

### ISSUE THREAD

**Issue by sheinbergon** [jaegertracing/jaeger-client-java#710]
Hello. 

We are trying to evaluate jaeger-tracing for tracing our various applications.
We are managing spans our selves (via a self-assigned ID), and both starting it and logging events using a self-deduced timestamps in micros-seconds, which seem to be valid.

However, reported span duration is literally off the charts.

Here's a sample span json:

```{
  "data": [
    {
      "traceID": "3f86c53578807ac2",
      "spans": [
        {
          "traceID": "3f86c53578807ac2",
          "spanID": "3f86c53578807ac2",
          "flags": 1,
          "operationName": "market-message-consumption",
          "references": [
            
          ],
          "startTime": 1588586480766066,
          "duration": 18446744073709551550,
          "tags": [
            {
              "key": "span-id",
              "type": "string",
              "value": "369746"
            },
            {
              "key": "sampler.type",
              "type": "string",
              "value": "ratelimiting"
            },
            {
              "key": "sampler.param",
              "type": "float64",
              "value": 1000
            },
            {
              "key": "internal.span.format",
              "type": "string",
              "value": "jaeger"
            }
          ],
          "logs": [
            {
              "timestamp": 1588586480766080,
              "fields": [
                {
                  "key": "event-id",
                  "type": "string",
                  "value": "message-encoded"
                }
              ]
            },
            {
              "timestamp": 1588586480766111,
              "fields": [
                {
                  "key": "event-id",
                  "type": "string",
                  "value": "message-dequeued"
                }
              ]
            },
            {
              "timestamp": 1588586480766191,
              "fields": [
                {
                  "key": "event-id",
                  "type": "string",
                  "value": "message-produced"
                }
              ]
            }
          ],
          "processID": "p1",
          "warnings": null
        }
      ],
      "processes": {
        "p1": {
          "serviceName": "sivron-feed-test",
          "tags": [
            {
              "key": "hostname",
              "type": "string",
              "value": "crl8-devel-desktop"
            },
            {
              "key": "ip",
              "type": "string",
              "value": "127.0.1.1"
            },
            {
              "key": "jaeger.version",
              "type": "string",
              "value": "Java-1.2.0"
            }
          ]
        }
      },
      "warnings": null
    }
  ],
  "total": 0,
  "limit": 0,
  "offset": 0,
  "errors": null
}```

Any idea what might be causing the span duration to look like this?

10x in advance

**Comment by yurishkuro** [comment]
Transferring to Java client. I suspect the use case with externally provided timestamps has not been extensively tested, so you're running into some edge case. You may want to create a PR with a few unit tests that will probably reveal the issue.

**Comment by ilylia** [comment]
maybe `tracer.clock().currentTimeMicros()` got a earlier time than the start time you provide ?

**Comment by sheinbergon** [comment]
@ilylia  yes, you are right, I just solved it a few hours ago.
This is happening because your `SystemClock` implementation does assumes microseconds resolution is not supported. While I'm providing a start time in microseconds, if the span finishes within the same milliseconds, we'll be getting a negtive timestamp, which the jaeger server in turn represents as `unsigned long`. Thus we're getting what seems like an overflow behavior.

I solved by creating a microseconds accuracy `Clock` implementation and passed it to the `JaegerTracer.Builder`

The JVM has been supporting microseconds resolution for absolute timestamp ever since JDK 9. 
@yurishkuro I can create a PR to fix the System Clock to support both cases ( up to JDK 9 and JDK 9 and above), should you want to.

**Comment by ilylia** [comment]
> I solved it by creating a microseconds accuracy `Clock` implementation and passing it to the `JaegerTracer.Builder`

can you share it?
I can't get current microseconds in jdk8.

> The JVM has been supporting microseconds resolution for absolute timestamp ever since JDK 9.
> @yurishkuro I can create a PR to fix the System Clock to support both cases ( up to JDK 9 and JDK 9 and above), should you want to.

Do you mean `Instant`?

**Comment by sheinbergon** [comment]
I meant I can fix the `SystemClock` to differentiate when running on top of JDK 8 and JDK 11.
however you are running with source compatibility targeting jdk 1.6, which might make this trickier (still doable though).

I'm getting microseconds timestamp by calling `ChronoUnit.MICROS.between(Instant.EPOCH, Instant.now())`

**Comment by ilylia** [comment]
but `Instant.now()` in jdk8 return just milliseconds, not microseconds, as blow:
(I found this in jdk8 on mac)
```
    public static Instant now() {
        return Clock.systemUTC().instant();
    }

    public static Clock systemUTC() {
        return new SystemClock(ZoneOffset.UTC);
    }

    static final class SystemClock extends Clock implements Serializable {
        @Override
        public long millis() {
            return System.currentTimeMillis();
        }
        @Override
        public Instant instant() {
            return Instant.ofEpochMilli(millis());
        }
    }
```
Is it impossible to get microseconds on jdk8?

**Comment by sheinbergon** [comment]
> The JVM has been supporting microseconds resolution for absolute timestamp ever since JDK 9.
> @yurishkuro I can create a PR to fix the System Clock to support both cases ( up to JDK 9 and JDK 9 and above), should you want to.

As I wrote in my original reply, **JDK 9** and above support microseconds (**NOT** JDK8, which you are referring to). Thus, if your code is being used in a JDK 9 or above environment (we are using it in JDK11), it can return microseconds instead of milliseconds, It just needs to differentiate between these scenarios. My offer was to contribute a piece of code to do exactly that :)

Let me know.

**Comment by ilylia** [comment]
thx~

**Comment by sheinbergon** [comment]
Soooo @ilylia, would you be willing to recieve a smart(er) clock contribution?

**Comment by ilylia** [comment]
Yes! And wait for your pr!

**Comment by sheinbergon** [comment]
@ilylia I've opened the a [PR](https://github.com/jaegertracing/jaeger-client-java/pull/712)
I formatted according to your own checkstyle ruleset, so things should be OK.

Regarding tests (and aside from of course verifying behavior on my own machine with 2 different JDKs), I'm not sure anything here is testable because you don't run your code on multiple JVM versions (or am I missing something?)

Let me know.

**Comment by sheinbergon** [comment]
@ilylia any response would be much appreciated

**Comment by ilylia** [comment]
sorry for a long time waiting. and wait for the merge.

**Comment by sheinbergon** [comment]
@ilylia sorry for taking the time to address the issues in the PR.  I'm ready to proceed with the merge process

**Comment by sheinbergon** [comment]
@ilylia  any news about finalizing this contribution?
