### ISSUE TITLE
LoggingReporter to verbose

### ISSUE THREAD

**Issue by maunzCache** [jaegertracing/jaeger-client-java#713]
#  Requirement - what kind of business use case are you trying to solve?

I want to read the logs of my application which utilizes the jaeger-client.

## Problem - what in Jaeger blocks you from solving the requirement?

When reading the logs the jaeger-client software overlaps entries with a verbose INFO logging which is reported by the LoggingReporter Class. The log is full of reported spans (every 2 to 10 seconds) which make reading and even indexing error messages a pain.
The jaeger-client was implemented by a co-worker and i am not 100% certain how we use the tool in our project. But as a developer for the main software i do not want to be disrupted by 3rd party software.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

A current workaround is to disable the INFO output of the namespace/class. However, the LoggingReporter is an internal class (at least the namespace says so) and may not use the INFO severity to log. It suggest to move the output to either DEBUG or TRACE level.

**Comment by pavolloffay** [comment]
hi @getjack, are you using logs from `LoggingReporter`? if no, then it's best to disable the logging reporter and just use remote reporter that sends spans to Jaeger backend.

**Comment by getjack** [comment]
Thanks for the response @pavolloffay . I will ask my colleague for that as the logging infrastructure is rather complex. As far as i am aware the logs are persisted in an Elastic cluster and i don't think we have any other jaeger backend.
