### ISSUE TITLE
Unable to configure mTLS when Jaeger production helm charts are installed.

### ISSUE THREAD

**Issue by prashanthga** [jaegertracing/jaeger-client-java#714]
## Requirement - what kind of business use case are you trying to solve?
We have installed the Jaeger production components using the helm charts. Our next goal is to configure transport security to the Jaeger components using mTLS of Istio service mesh.

We have created a namespace called "jaeger" where all the jaeger components are placed. The mTLS policy and destination rule are properly configured. The native TLS for cassandra is not used. 

## Problem - what in Jaeger blocks you from solving the requirement?

The Jaeger collector fails to deploy with the issue:
{"level":"info","ts":1590589758.0303512,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
2020/05/27 14:29:19 gocql: unable to dial control conn 10.32.0.21: EOF
{"level":"fatal","ts":1590589759.044615,"caller":"collector/main.go:91","msg":"Failed to init storage factory","error":"gocql: unable to create session: control: unable to connect to initial hosts: EOF"

kubectl get pods -n jaeger
NAME                              READY   STATUS             RESTARTS   AGE
jaeger-agent-5cmt2                2/2     Running            0          14m
jaeger-agent-8ltcj                2/2     Running            0          14m
jaeger-cassandra-0                2/2     Running            0          14m
jaeger-cassandra-1                1/2     Running            6          13m
jaeger-collector-6965df75-qlrjg   1/2     CrashLoopBackOff   7          14m
jaeger-query-5bbcb9cb84-jwcn7     2/3     CrashLoopBackOff   7          14m

No security is achieved for Jaeger components.

**Comment by yurishkuro** [comment]
This is not the relevant repository for this issue. Consider opening a ticket against the Help chart repo. It's also possible that the problem is with your networking setup where Jaeger backend cannot reach Cassandra, or the mTLS tunnel gets in the way somehow.
