### ISSUE TITLE
Jaeger trace/span shipper

### ISSUE THREAD

**Issue by gamefundas** [jaegertracing/jaeger-client-java#730]
## Requirement - what kind of business use case are you trying to solve?

I am working on a Low Latency Java application that generates custom traces in log files. The design limits us from using any agents or connecting to external collectors mainly for the purposes of speed and simplicity. Currently the logs are in custom format and we don't have a good way to visualize them. The idea is to move to Jaeger. 

Now we would like to retain the current tracing pipeline of publishing the traces to logs and then have some sort of "Trace Shipper" push them to Jaeger collector via HTTP.  This can be achieved using AWS Cloudwatch that can parse the trace log streams using Lambda which in turn can push to the collector.

I imagine each entry in the trace logs can be published to Jaeger collector (/api/traces endpoint) using some sort of HTTP API. Is this possible to reconstruct the traces from trace logs and publish them to the collector outside of the application? If yes are there any java examples that can help understand how to push data to the collector.

**Comment by pavolloffay** [comment]
> Is this possible to reconstruct the traces from trace logs and publish them to the collector outside of the application?

This should be doable but, the logging reporter does not log full spans. Try to play with to see what data it logs. We could however extend it to log all span fields.

>  If yes are there any java examples that can help understand how to push data to the collector.

Jaeger collector exposes two native Jaeger endpoints (and Zipkin) that can be used to push trace data to the storage see https://www.jaegertracing.io/docs/1.18/deployment/#collectors. I would recommend using gRPC endpoint, here is a blog post that documents how gRPC services can be generated https://medium.com/jaegertracing/generating-jaeger-grpc-services-and-using-jaeger-in-junit-with-testcontainers-ac08a6e4e1c. For java there is also a published artifact.
