### ISSUE TITLE
Does the JAEGER_PROPAGATION env var support the w3c setting?

### ISSUE THREAD

**Issue by chgl** [jaegertracing/jaeger-client-java#733]
## Requirement - what kind of business use case are you trying to solve?

The README currently states that "Valid values are jaeger and b3" for the JAEGER_PROPAGATION env var. From briefly checking the code it looks like `w3c` should be supported as well. Is this correct?

## Problem - what in Jaeger blocks you from solving the requirement?

The documentation does not clarify if I can use `w3c` as a possible value to enable W3C compatible tracing.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The documentation should be updated if applicable. I'll gladly create a PR for this :)

**Comment by objectiser** [comment]
@chgl Yes it is supported - would you be interested in submitting a PR to fix the docs?
