### ISSUE TITLE
Add default MDCScopeManager support in JaegerTracerResolver

### ISSUE THREAD

**Issue by lichenglin** [jaegertracing/jaeger-client-java#734]
We need add a default MDCScopeManager in class JaegerTracerResolver、JaegerTracerFactory  

in order to add traceid and spanpid in slf4j's mdc context.

It's very useful to 3rd packages when using opentracing api to create jaegertracer.

such as java-specialagent.

**Comment by yonidavidson** [comment]
Hi, is there any plan to implement this?
