### ISSUE TITLE
Ignores some tags when you create a span with forced sampling

### ISSUE THREAD

**Issue by IndicatorFluid** [jaegertracing/jaeger-client-java#738]
## Requirement - what kind of business use case are you trying to solve?

We have an application which we generally do not want tracing enabled, but we have certain user triggered workflows
where we'd like to enable tracing for.

The way we achieve this is for user initiated actions we build a new span (hence context) with 
`Tags.SAMPLING_PRIORITY` set to `1`, together with other tags specific to the users request.

## Problem - what in Jaeger blocks you from solving the requirement?

There is no specific order in which the tags get processed and added to the context/span, as it's an iteration over a map:

https://github.com/jaegertracing/jaeger-client-java/blob/f1a7ca91af05206b3c47573689331a1fafec16de/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerSpan.java#L69-L71

This causes a problem, because tags are only set if the context is sampled

https://github.com/jaegertracing/jaeger-client-java/blob/f1a7ca91af05206b3c47573689331a1fafec16de/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerSpan.java#L234-L236

But the decision whether it's sampled or not comes from one of the tags, which can arrive later (due to iteration over a map)
Hence all tags prior to the sampling tag are dropped on the floor and ignored.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I think it should set the tags on the context unconditionally, or explicitly check for the sampling tag and do context adjustments 
before setting the rest of the tags.

## Sad workaround

Create a noop root span with sampling enabled, create a child span with actual user specific tags

**Comment by yurishkuro** [comment]
This has been already solved in Go and Node.js Jaeger clients via [delayed sampling][1]. It can be implemented in Java as well, of someone has the time.

[1]: https://github.com/jaegertracing/jaeger-client-go#delayed-sampling

**Comment by AudriusButkevicius** [comment]
Sure, yet that's more effort than just fixing this bug.

Would you guys be happy with a PR fixing this specific issue? If yes, which way you guys prefer it to be solved (always put tags in context, check sampling tag before hand)?

**Comment by yurishkuro** [comment]
Are you saying that you're supplying SAMPLING_PRIORITY at span creation, but it's still ignoring other tags due to map iteration order? If so, then yes, it sounds like a bug, this specific tag should be processed first.
