### ISSUE TITLE
Document release process credentials

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#740]
@pavolloffay could you add a couple paragraphs to RELEASE.md explaining what kind of credentials are encrypted in the .travis.yml, e.g. GH_TOKEN, SIGNING_KEY_ID, etc. - what are their origins?  I see that the release commits come up under your name.

**Comment by yurishkuro** [comment]
Actually, Pavol's name only comes up in Travis, git and github show `jaegertracingci` bot

![image](https://user-images.githubusercontent.com/3523016/92416486-bf160300-f12b-11ea-9cde-0605ee1d07d1.png)

**Comment by pavolloffay** [comment]
Singing key and password are already documented https://github.com/jaegertracing/jaeger-client-java/blob/028597a3e89eb786f75380d30d1cd0268fb4974e/RELEASE.md#L35 it was done by @jpkrohling.

I can add docs for github token to the travis yaml.
