### ISSUE TITLE
initialize a tracer with noopreporter & retrieve subspans from rootspan.

### ISSUE THREAD

**Issue by Saewo0** [jaegertracing/jaeger-client-java#741]
## Requirement

We don't want to store spans in memory or in remote storage because this may cause some resource overheads. I think I should use NoopReporter to avoid involving sender, agent, and other services.

## Problem
In the document, it says get tracer from configuration is the best way to instantiate a tracer. However, by looking into the source code I found getting tracer by configuration always returns a tracer with RemoteReporter. What's the disadvantage of using JaegerTracer.builder()?

## Requirement
Based on the previous use cases, we won't store any spans anywhere, so we need to print all spans' information right after rootspan.finish().

## Problem 
is there any way to retrieve all sub spans of the root span after rootspan.finish().

Thanks for supporting this amazing project.

**Comment by yurishkuro** [comment]
You can implement your own reporter that will accumulate spans in memory and print them once the entry span is finished. This would obviously only work if all your work on a request is done by a single process without remote/distributed calls. If you're dealing with a distributed system, you do need to export the spans into a central location.

**Comment by Saewo0** [comment]
Thanks, Yuri! User-defined reporters solved my problem. I will close this issue.
