### ISSUE TITLE
Remotely changing the service sampling rate while per operation exists, does nothing

### ISSUE THREAD

**Issue by ofir-popowski** [jaegertracing/jaeger-client-java#742]
## Requirement - what kind of business use case are you trying to solve?

We would like to use the `RemoteControlledSampler` to change the service sampling rate, while also having `perOperation` strategy.

## Problem - what in Jaeger blocks you from solving the requirement?

At my work we've recently started applying traces with Jaeger, and I have implemented a custom `SamplingManager`, because we keep that configuration outside of the collector to support dynamically changing the sampling rates (which the collector currently does not support, atleast without restarting it).

The problem is, that if operations strategies exist, the `RemoteControlledSampler` skips the strategy for the service.

Lets consider the following `strategies.json`:
```json
{
  "service_strategies": [
    {
      "service": "foo",
      "type": "probabilistic",
      "param": 0.8,
      "operation_strategies": [
        {
          "operation": "op1",
          "type": "probabilistic",
          "param": 0.2
        },
        {
          "operation": "op2",
          "type": "probabilistic",
          "param": 0.4
        }
      ]
    }
  ]
}
```

If I were to change the rate for `foo` from 0.8 to say 1.0, because operation strategies exist, it will not be updated in the sampler because of this part
```java
    if (response.getOperationSampling() != null) {
      updatePerOperationSampler(response.getOperationSampling());
    } else {
      updateRateLimitingOrProbabilisticSampler(response);
    }
```

We get true in the `if` clause, because per operation has already been defined, but wasn't updated, then it skips the `updateRateLimitingOrProbabilisticSampler`

## Proposal - what do you suggest to solve the problem or improve the existing situation?

This part of the code should be changed to allow using the service rate as a fallback if no operation specific rate has been defined. Possibly removing the `else` would be enough, that way `updateRateLimitingOrProbabilisticSampler` can be run regardless of per operation configuration or not

**Comment by yurishkuro** [comment]
The part `if (response.getOperationSampling() != null) {` checks the _response_, not the current state in memory. Not sure if this is an issue, but consider creating a PR with a unit test that illustrates the problem.

**Comment by ofir-popowski** [comment]
Yes I was talking about the response. It uses the manager to fetch the sampling strategy, which is almost identical except the rate for `foo` has changed, which it doesn't check because the response also contains the `perOperationSampling`

**Comment by ofir-popowski** [comment]
@yurishkuro I have opened a PR that adds a unit test that demonstrates what I meant, and fixes the issue. I'm not sure the test is okay, as it just checks for equality, but I think it's clear what I tried to do, and what I propose as a fix

**Comment by ofir-popowski** [comment]
I'm closing this issue, as I found out the mistake was on my end.

When the collector returns a response when the sampler gets updated, the JSON that returns gets modified
This is how my `sampling_strategies.json` looks like:
```json
{
  "service_strategies": [
    {
      "service": "demo-service",
      "type": "probabilistic",
      "param": 0.0,
      "operation_strategies": [
        {
          "operation": "op1",
          "type": "probabilistic",
          "param": 0.0
        }
      ]
    }
  ]
}
```

Yet the JSON that returns from the collector looks like this:
```json
{
  "strategyType": 0,
  "probabilisticSampling": {
    "samplingRate": 0
  },
  "operationSampling": {
    "defaultSamplingProbability": 0,
    "defaultLowerBoundTracesPerSecond": 0,
    "perOperationStrategies": [
      {
        "operation": "op1",
        "probabilisticSampling": {
          "samplingRate": 0
        }
      }
    ],
    "defaultUpperBoundTracesPerSecond": 0
  }
}
```

The part that gets added is the following, and we end up with the `probabilisticSampling` rate being "ignored", and the `operationSampling.defaultSamplingProbability` gets used
```json
  "operationSampling": {
    "defaultSamplingProbability": 0,
```

Which my custom sampling manager configuration was lacking
