### ISSUE TITLE
How to send jaeger tracing data from the client to multiple agents/collectors

### ISSUE THREAD

**Issue by morarucostel** [jaegertracing/jaeger-client-java#747]
## Requirement - what kind of business use case are you trying to solve?

In a kubernetes environment we want for the microservice (the client) traces to be captured by two different agents that in return will connect to two different collectors so that we can store the tracing data in two different data stores. 

The reason this this specific use-case: We have one Jaeger instance running in the kluster, instance that serves as an operational tracing tool. Some of the services (pods) deployed are necessary to be traced into another Jaeger instance for some business related activities. As you can imagine the two Jaeger instances have different non-functional requirements considering: data retention, sampling rate and type, different topologies on the persistence repository. 

So, the question is, how do we augument the client code to send the traces to two different agents/collectors?

## Problem - what in Jaeger blocks you from solving the requirement?

As a solution, when we create the JaegerTracer we use the CompositeReporter in order to encapsulate multiple Reporters, each of them having configured a different sender, thus the tracing is being sent to different agents/collectors which is what we want. However, we can not configure the sampler param and type per reporter since this is set up on the Tracer object. Thus we can not have the service (the client) send traces to different agents (with configurable sampling parameters). 

We also tried to use the Collector Sampling Configuration, but then we come again to the same problem, the Sampler being configured at the Tracer level, it means that all the Reporters will use the same remote host sampling host, thus all the Reporters will pick-up the same configuration. Lets say we have the `service_strategies` configured for service foo like below:
```
      "service": "foo",
      "type": "probabilistic",
      "param": 1,
```
That means that the Tracer will send, using all the reporters, with a probability of 1 to the agents/controllers. Thus we can still not configure the sampling rate per agent.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Is there a way to have multiple JaegerTracer instances running in the same time in one single client?
Or is there any known solution to the problem described above?

**Comment by jpkrohling** [comment]
This isn't possible at the client level, but you can accomplish that in two ways:

1. by having a single collector that uses the `kafka` storage mechanism. From there, you can read the spans from multiple ingesters, persisting them in multiple places.
1. by using the OpenTelemetry Collector, configured with a Jaeger receiver and multiple exporters.

**Comment by morarucostel** [comment]
@jpkrohling thank you for the response and for confirming me that it can't be achieved at the client level. 

With regards to the option:
1/ Yes, `kafka` topology will do it - we wanted to solve our use-case without bringing an additional framework into picture,
2/ I'll have too dig deeper into this direction and and check what it can support.

However, from the look of it, it seems that there is no way in configuring the sampling strategy in such a way that the client won't send the data to the agent -> collector (we are trying to avoid additional network traffic inside the kubernetes cluster). Every option I see, it pushes the data to the collector (through the agent or not), which then either based on a) the `strategies.json` from the Collector Sampling Configuration or based on b) the option 2 described above, will sent it to persistence storage (and only here we can decrease the number of spans that are sent).

**Comment by jpkrohling** [comment]
If you decide to go with the OpenTelemetry way, you can deploy the collector as a sidecar, like we do at the Jaeger Operator with the Jaeger Agent. This sidecar would then multiplex data to the respective Jaeger backends.

**Comment by yurishkuro** [comment]
Technically, you could implement so-called tee-tracer that encapsulates two independent traces, but you'd also need to configure one of them to use a different wire propagation format if your intention is to have two different sampling strategies simultaneously (because sampling decision must be propagated). I agree with @jpkrohling that it's better to sample the data with a single tracer with higher of the two rates, collect data only once, and figure out how to route it in the backend, with possible additional down-sampling to the lower rate for one of the destinations.
