### ISSUE TITLE
JaegerSpans not reported unless a 1s Sleep is added after tracer is initialized

### ISSUE THREAD

**Issue by craigtmoore** [jaegertracing/jaeger-client-java#751]
## Requirement

I am trying to monitor the performance of the Jenkins regression tests that my company runs each day. Every time someone commits a change, our Jenkins project runs and during the job run, I want Jaeger to report how long the test takes to run with child spans for each individual step of the build. 

## Problem

The problem is that if I don't include a `Thread.sleep(1000)` after the Jaeger tracer is initialized, then Jaeger does not report any spans. I assume that it is because Jaeger needs time to spin up the tracer before it is used to create, start and finish spans. The tests (being monitored by Jaeger) take around 40-60 minutes to execute, and without the sleep no traces are reported the Jaeger server.

### Setup

I setup a jaeger server with an elastic/kibanna backend, as described here:
* https://logz.io/blog/jaeger-and-the-elk-stack/

I created the following `JaegerClient` wrapper class (written in groovy): 
```
import io.jaegertracing.Configuration
import io.opentracing.Span
import io.opentracing.Tracer

class JaegerClient {

    Tracer tracer

    private JaegerClient() {
        def jaegerHost = System.getProperty(Configuration.JAEGER_AGENT_HOST)
        def jaegerPort = System.getProperty(Configuration.JAEGER_AGENT_PORT, "14268")

        System.setProperty(Configuration.JAEGER_SERVICE_NAME, "JaegerClient")
        System.setProperty(Configuration.JAEGER_SAMPLER_MANAGER_HOST_PORT, "$jaegerHost:5778")
        System.setProperty(Configuration.JAEGER_REPORTER_LOG_SPANS, "true")
        System.setProperty(Configuration.JAEGER_ENDPOINT, "http://$jaegerHost:$jaegerPort/api/traces")

        this.tracer = Configuration.fromEnv().getTracer()
        Thread.sleep(1000)  // <- This is what keeps it reporting spans
    }

    private static class Singleton { private static final JaegerClient INSTANCE = new JaegerClient() }

    static JaegerClient getInstance() { return Singleton.INSTANCE; }

    static Span startSpan(String operation) {
        def spanBuilder = getInstance().tracer.buildSpan(operation)
        def span = spanBuilder.start()
        getInstance().tracer.activateSpan(span)
        return span
    }

    static <T> T startSpan(Span parentSpan, String operation, Closure<T> closure) {
        def spanBuilder = getInstance().tracer.buildSpan(operation)
        if (parentSpan != null) {
            spanBuilder.asChildOf(parentSpan.context())
        }
        def span = spanBuilder.start()
        getInstance().tracer.activateSpan(span)
        println "Starting span ${span.context()} for operation '$operation' ..."
        try {
            closure()
        } finally {
            println "Finishing span ${span.context()} for operation '$operation'"
            span.finish()
        }
    }
}
```

I wrote a small unit-test to try it out before using it in production. During the unit test, I found that it would only report the spans, if I added break points to the code. 

```
package jaeger

class JaegerClientTest extends GroovyTestCase {

    void testStartSpan() {
        def parentSpan = JaegerClient.startSpan("testStartSpan")
        for (i in 0..<3) {
            JaegerClient.startSpan(parentSpan, "test_$i") {
                Thread.sleep(1000)
            }
        }
        parentSpan.finish()
    }
}
```

I am not sure if there is another way to do this? Is there a liveliness check that can be performed on the tracer to verify that its ready to process traces? Like
```
while (!tracer.isReady()) {
   Thread.sleep(100)
}
```

**Comment by jpkrohling** [comment]
I think the tracer is (or should) be ready to be used once you build it. What I think that might be happening is that spans aren't being flushed out before the test/JVM stops. In your test, could you make sure you have a call to `this.tracer.close()` in the tear down phase?

**Comment by craigtmoore** [comment]
I removed the `Thread.sleep(1000)` and added to the end of my test `JaegerClient.instance.tracer.close()` but it still did not report the spans.

**Comment by jpkrohling** [comment]
If you add the sleep to the end of your test, does it work?

**Comment by craigtmoore** [comment]
No, it does not work in that case either (note there were are sleeps in each of the child spans)

**Comment by jpkrohling** [comment]
That does sound like a bug then. I'll leave it open with the hacktoberfest tag, to see if someone wants to debug it and figure out what's going on.
