### ISSUE TITLE
Tags set in JAEGAR_TAGS environment variable is not available in Jaeger trace data 

### ISSUE THREAD

**Issue by priyamaplelabs** [jaegertracing/jaeger-client-java#752]
We set the JAEGER_TAGS env variable as below
export JAEGER_TAGS="_tag_appName=java-app,_tag_projectName=sftrace"

We then start the Java application where we have also created a span as below
`Span span= ManagerApplication.tracer.buildSpan("create_task").start();
 span.finish();`
Once we send a http request, we are able to see the span in Jaeger UI.
But the tags that we added through the env variable is not available in the span data.

Is there any other configuration that needs to be done for this to work.

Thanks,
Priya

**Comment by objectiser** [comment]
@priyamaplelabs Moving this issue to the jaeger java client repo.

Could you provide information about the jaeger client version you are using?

**Comment by priyamaplelabs** [comment]
Hello,
The jaeger client version is 1.4.0
Thanks,
Priya

**Comment by objectiser** [comment]
Are there any errors reported regarding parsing the tags?

Could you try printing the output from `io.jaegertracing.Configuration.fromEnv().getTracerTags()` to see what tags it has loaded from the environment?

**Comment by priyamaplelabs** [comment]
There are no errors
io.jaegertracing.Configuration.fromEnv().getTracerTags() returns 
{_tag_projectName=sftrace, _tag_appName=hot_ROD}

But cannot see the tags in Jaeger UI.

**Comment by objectiser** [comment]
@priyamaplelabs I wasn't able to reproduce using Jaeger Java client 1.4.0 with all-in-one 1.20.

What backend storage are you using? Could you try with all-in-one/memory to see whether the problem occurs still?

**Comment by yurishkuro** [comment]
also, in case you didn't look there, these tags will be under Span/Process/Tags, not Span/Tags.

**Comment by priyamaplelabs** [comment]
Hello,
I started Jaeger as below
docker run --rm -it --link=elasticsearch --name=jaeger -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://elasticsearch:9200 -e ES_TAGS_AS_FIELDS_ALL=true -p 16686:16686 -p 14268:14268 -p 5778:5778 -p 14250:14250 jaegertracing/all-in-one:1.12

At the java application side, set the tag in bashrc as below and sourced it.
export JAEGER_TAGS="_tag_appName=hot_ROD,_tag_projectName=sftrace"

Java app and jaeger service are running in 2 different vms.

With the above setup, unable to see the set tags in Jaeger UI in both Span/Process/Tags and Span/Tags
http://<ip where jaeger services are running>:16686/

Thanks,
Priya

**Comment by objectiser** [comment]
@priyamaplelabs Could you try two things separately - doing a test after each, to see if we can narrow down where the issue may be:
1) The version of the backend being used is quite old, can you try `1.20` instead of `1.12`
2) Change `SPAN_STORAGE_TYPE` from `elasticsearch` to `memory`

**Comment by objectiser** [comment]
@priyamaplelabs Can you show the code you are using to configure the tracer?

**Comment by priyamaplelabs** [comment]
Hello,
This is how we configure trace in the Java app
`public static JaegerTracer init(String service) {
    SamplerConfiguration samplerConfig = SamplerConfiguration.fromEnv().withType("const").withParam(1);
    ReporterConfiguration reporterConfig = ReporterConfiguration.fromEnv().withLogSpans(true);
    Configuration config = new Configuration(service).withSampler(samplerConfig).withReporter(reporterConfig);
    return config.getTracer();
}
`
Thanks,
Priya

**Comment by objectiser** [comment]
@priyamaplelabs You need to either explicitly passed in the tracer tags, using the `withTracerTags(map)` method, or make a change to the following line:
```
Configuration config = new Configuration.fromEnv(service).withSampler(samplerConfig).withReporter(reporterConfig);
```
which will build the configuration from the environment variables first, and then override the sampler and reporter.

**Comment by priyamaplelabs** [comment]
Hello,
With the change you have suggested, we are able to see the tags in Jaeger UI.
Thanks for the support.
