### ISSUE TITLE
When can we expect a new releasee?

### ISSUE THREAD

**Issue by delebedev** [jaegertracing/jaeger-client-java#760]
Hey, not an issue per-se, just wanted to check when we can have https://github.com/jaegertracing/jaeger-client-java/commit/640fa3523390a2f2782dcfbf7f995f1b5fec758a available in maven?

**Comment by objectiser** [comment]
New version 1.5.0 has been released: https://search.maven.org/artifact/io.jaegertracing/jaeger-client/1.5.0/jar
