### ISSUE TITLE
Support of https sender - Jaeger client to collector

### ISSUE THREAD

**Issue by Asisranjan** [jaegertracing/jaeger-client-java#771]
Hi

In our project, we have placed envoy load balancer in front of Jaeger collector. With this we have exposed https port for communication.

We need to use directly Jaeger collector from client to send traces over it. Do Jaeger java client support https sender, please confirm.

I see https://github.com/jaegertracing/jaeger-client-java/pull/602 but do not see in latest version (1.5.0). Do you have plan to release next version and when (including https sender) ?

Anyone have the sample code for https sender, please share. It will be helpful. Thanks in advance.

/Asis

**Comment by Asisranjan** [comment]
@jpkrohling & @yurishkuro 
Could you please comment.

**Comment by jpkrohling** [comment]
As long as the keystore used by your JVM contains the certificate/CA, it should just work. That PR is for allowing the client to use its own TLS configuration, from what I remember. If you have reasons to believe this isn't working, please reopen the issue.
