### ISSUE TITLE
RemoteReporter should be able to 'ignore' sender exception as in old behaviour

### ISSUE THREAD

**Issue by ehsavoie** [jaegertracing/jaeger-client-java#778]
## Requirement - what kind of business use case are you trying to solve?

RemoteReporter now logs SenderException with a WARN message, while this wasn't the case before. We need some way to provide the old behaviour by tracing in debug if there are such errors.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Add a new ignoreSenderErrors configuration parameter to the ReporterConfiguration to provide the old behaviour.

**Comment by ehsavoie** [comment]
Because it creates https://issues.redhat.com/browse/WFLY-14625 with the same configuration and i can't do anything about this from the 'outside'.

**Comment by ehsavoie** [comment]
also the trace only once is 'broken' as the flush command will succeed if no span is to be sent thus those traces comes in a 'loop' if there is no enough activity.

**Comment by yurishkuro** [comment]
You could suppress the logging from remote reporter if you're not interested in it.

**Comment by ehsavoie** [comment]
That would mean creating specific logger rules for jaeger client. This is a workaround that we dismissed because it means to embedded specific logging rules in our configuration
