### ISSUE TITLE
OpenTracing standard Formats TEXT_MAP_INJECT, TEXT_MAP_EXTRACT are not supported

### ISSUE THREAD

**Issue by Spikhalskiy** [jaegertracing/jaeger-client-java#789]
Currently getting 

```
Caused by: io.jaegertracing.internal.exceptions.UnsupportedFormatException: Builtin.TEXT_MAP_EXTRACT
``` 

trying to use JaggerTracer with TEXT_MAP_INJECT, TEXT_MAP_EXTRACT standard OpenTracing formats using a trivial configuration:

```
reporter = new InMemoryReporter();
sampler = new ConstSampler(true);
tracer = new JaegerTracer.Builder("temporal-test")
        .withReporter(reporter)
        .withSampler(sampler)
        .build();

GlobalTracer.registerIfAbsent(tracer);
```

and running

```
  private static Map<String, String> spanContextToMap(SpanContext spanContext, Tracer tracer) {
    Map<String, String> serialized = new HashMap<>();
    tracer.inject(spanContext, Format.Builtin.TEXT_MAP_INJECT, new TextMapInjectAdapter(serialized));
    return serialized;
  }
```

`JaegerTracer` implementation registers codecs for TEXT_MAP, HTTP_HEADERS, and BINARY: https://github.com/jaegertracing/jaeger-client-java/blob/7544006e1aaf42c35d1e9dbc086608f6f6964e56/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java#L576
But it doesn't register anything for TEXT_MAP_INJECT and TEXT_MAP_EXTRACT.

**Comment by Spikhalskiy** [comment]
I probably can take care of providing a PR and a fix for this issue but needs confirmation that it's not like that "by design".

**Comment by william-tran** [comment]
@Spikhalskiy Try using `io.opentracing.propagation.TextMapAdapter` instead. It seems Jaeger is designed to only accept adapters that go both ways, rather than inject and extract separately.
