### ISSUE TITLE
Does Jaeger Java client support JDK 17?

### ISSUE THREAD

**Issue by pjgg** [jaegertracing/jaeger-client-java#796]
### Questions

Java 17 (LTS) will be released [soon](https://openjdk.java.net/projects/jdk/17/), do you know if Jaeger "java client" is supported under this JDK version.

**Comment by pjgg** [comment]
Any news about this topic?

**Comment by yurishkuro** [comment]
We have no plans for testing the SDK with Java 17 since this library is scheduled to be decommissioned (see README).
