### ISSUE TITLE
Document migration path to OpenTelemetry SDK

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#810]
In the last maintainers meeting @jpkrohling agreed to test & write a migration guide for OpenTracing/Jaeger users to OpenTelemetry SDK, as the first step towards retiring this Java client.

**Comment by jpkrohling** [comment]
I have a draft ready and shared in Slack channel for Jaeger maintainers. If it looks like a good start, I'll send it to our Medium publication.
