### ISSUE TITLE
Is an additional release planned?

### ISSUE THREAD

**Issue by amirhadadi** [jaegertracing/jaeger-client-java#820]
This library last release was on Apr 7 2021.
Since then master progressed and in the meantime the library was deprecated.
Is there going to be an additional release with all the changes made before the library was deprecated?

**Comment by yurishkuro** [comment]
@albertteoh could you try to do a release (changelog PR #805)? It looks like you did the manual step the last time.

**Comment by albertteoh** [comment]
Yup, sure, I can give it a go; it was actually @jpkrohling who did it, but I'll try to follow the steps he outlined to me [in an earlier slack thread](https://cloud-native.slack.com/archives/CGG7NFUJ3/p1617804632171900?thread_ts=1615881074.000400&cid=CGG7NFUJ3).

**Comment by albertteoh** [comment]
@amirhadadi jaeger-client-java 1.7.0 is released: [ [maven](https://search.maven.org/search?q=g:io.jaegertracing) | [github](https://github.com/jaegertracing/jaeger-client-java/releases/tag/v1.7.0) ]

Please let me know if you encounter any problems with the release, and we can reopen this issue to address them.

@yurishkuro, please advise if there are other forums where we should advertise this release besides the [#jaeger slack channel](https://cloud-native.slack.com/archives/CGG7NFUJ3/p1640561362032800).

**Comment by yurishkuro** [comment]
Personally I rarely advertise new releases, since people can subscribe on GitHub just for release notifications.

**Comment by yurishkuro** [comment]
Thanks, Albert.

**Comment by yurishkuro** [comment]
Btw if you did any extra steps not explained in the RELEASES doc, can you update it please?

**Comment by amirhadadi** [comment]
@albertteoh following [this](https://github.com/jaegertracing/jaeger-client-java/issues/823) fix, can you release a new version?

**Comment by albertteoh** [comment]
> can you release a new version?

@amirhadadi sure thing, I'll make a final release given that fix was merged prior to the [deprecation notice](https://github.com/jaegertracing/jaeger-client-java/commit/8ba71a6157bd6a4b503f1f2e2536935bbe1aa490).

**Comment by albertteoh** [comment]
@amirhadadi v1.8.0 released: [ [maven](https://search.maven.org/artifact/io.jaegertracing/jaeger-core/1.8.0/jar) | [github](https://github.com/jaegertracing/jaeger-client-java/releases/tag/v1.8.0) ]
