### ISSUE TITLE
Consider using manual thrift payload generation

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#84]
@adriancole did this in Zipkin by implementing thrift-like serialization manually. However, if we do this, I'd only do it along with upgrading to the new data model.
- [ ] manual thrift serializer
- [ ] unit tests validating that regular Thrift serializer can read the manually generated bytes payload

**Comment by vprithvi** [comment]
I like this. It will prevent end users from having to muck around with thrift in the first place. 

Can't we simply reuse what zipkin [does](https://github.com/openzipkin/zipkin/blob/433ecf92f9f5c523e109c61e1e978a60cf593d4a/zipkin/src/main/java/zipkin/internal/ThriftCodec.java) ? Jaeger converts everything to the [zipkin model](https://github.com/uber/jaeger-client-java/blob/78086a0a0205f973e5e50a641ff75ba4328af3d8/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java#L42), no?

**Comment by yurishkuro** [comment]
Well, we can borrow that code provided that we add unit tests that proves that thrift can read back the encoded data. Specifically, I would keep TestTServer using thriftlib to parse the data.

If this is a simple enough change, then it's probably preferable to the shadow jar.

**Comment by vprithvi** [comment]
The zipkin repo already has [interoperability tests](https://github.com/openzipkin/zipkin/blob/433ecf92f9f5c523e109c61e1e978a60cf593d4a/benchmarks/src/test/java/zipkin/internal/ThriftCodecInteropTest.java) and [unit tests](https://github.com/openzipkin/zipkin/blob/433ecf92f9f5c523e109c61e1e978a60cf593d4a/zipkin/src/test/java/zipkin/internal/ThriftCodecTest.java) for it.  
It's published under `io.zipkin.java:zipkin`, so we should be able to use it without doing anything complex.

**Comment by yurishkuro** [comment]
doesn't that jar also include storage/collector https://github.com/openzipkin/zipkin/tree/433ecf92f9f5c523e109c61e1e978a60cf593d4a/zipkin/src/main/java/zipkin

**Comment by vprithvi** [comment]
It does; an alternative is to simply copy and paste the code that we require, or perhaps convince the zipkin maintainers to publish `zipkin-internal` as a separate jar

**Comment by yurishkuro** [comment]
I don't really want to drag in dependency on zipkin into jaeger-core. That's why I said at the beginning - I would rather do this work against the new data model. And we can also avoid the intermediate classes and use the core Span directly.

**Comment by adriancole** [comment]
@vprithvi looks like you have your answer!

**Comment by adriancole** [comment]
@vprithvi fwiw if I were you and need to avoid a dep, I'd use shade
and repackage the 2 or 3 classes needed, and not expose them
externally. Then it is only a build dep, which should be harmless.

**Comment by adriancole** [comment]
ex,
https://repo1.maven.org/maven2/io/zipkin/java/zipkin/1.14.0/ <- 155K
https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.3/ <- 234K

not much point in splitting the jar considering this

**Comment by adriancole** [comment]
>
> doesn't that jar also include storage/collector
> https://github.com/openzipkin/zipkin/tree/433ecf92f9f5c523e109c61e1e978a
> 60cf593d4a/zipkin/src/main/java/zipkin
>
interfaces and base classes. it is still much smaller than the dep tree of
libthrift

**Comment by adriancole** [comment]
benchmarks, too :)
https://github.com/openzipkin/zipkin/blob/master/benchmarks/src/main/java/zipkin/benchmarks/CodecBenchmarks.java

**Comment by vprithvi** [comment]
@adriancole If I understand you right, you are suggesting that I depend on `io.zipkin:zipkin` but shade and filter dependencies, so that the only dependencies that I'm including are the classes I need (ThriftCodec, and anything that it depends on).

I like this approach much better than what we have right now. Especially considering the fact that one of the failure modes for a `libthrift` version conflict is to silently drop spans at the `UDPSender`

It also means that jaeger's end users no longer need to care about which thrift version they are using, or remember to configure the correct shaded jar. 

@yurishkuro What do you think?

**Comment by yurishkuro** [comment]
+1

**Comment by vprithvi** [comment]
Looks like I spoke too soon; the jaeger-client-java also uses thrift to communicate with the jaeger-collector to get sampling strategies. 
We'd have to write thrift classes and serializers/deserializers for them as well to get rid of the libthrift dependency regardless of which data model we are using.

**Comment by yurishkuro** [comment]
sampling strategies come in JSON

**Comment by adriancole** [comment]
>
> @adriancole <https://github.com/adriancole> If I understand you right,
> you are suggesting that I depend on io.zipkin:zipkin but shade and filter
> dependencies, so that the only dependencies that I'm including are the
> classes I need (ThriftCodec, and anything that it depends on).
>
yep exactly. If you look at zipkin's pom, you'll notice we cherry-pick a
couple classes from gson this way

**Comment by vprithvi** [comment]
@yurishkuro Excellent. I was thrown off by looking at the [thrift code](https://javalibs.com/artifact/com.uber.jaeger/jaeger-thrift?className=com.uber.jaeger.thrift.sampling_manager.SamplingManager.AsyncClient) for a sampling client. 

We'd still have to write classes for the java json data model for `RateLimitingSamplingStrategy`,  `ProbabilisticSamplingStrategy` and `SamplingStrategyResponse` which is pretty straightforward.

**Comment by yurishkuro** [comment]
We can refactor https://github.com/uber/jaeger-client-java/blob/master/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java, right now it has to do manual decoding of incoming JSON into thrift-generated classes. If we define our own classes, then we can annotate them so that JSON encoding can be done automatically.

**Comment by vprithvi** [comment]
Sounds good. 

The following need to be done
- [ ] Move crossdock thrift dependencies into the crossdock package (They currently live in the core thrift package for no good reason)
- [ ] Refactor HTTPSamplingManager, add json model classes for sampling
- [ ] Cherrypick the zipkin classes required for thrift generation, and remove libthrift dependency from jaeger-core

**Comment by jpkrohling** [comment]
Is this still relevant?

**Comment by jpkrohling** [comment]
I'm starting to scratch something around this.

@yurishkuro, @vprithvi, I know you have given some thought to it in the past, so, just wanted to see if you have anything in mind before I start. I think the problem with the sampling strategies has been solved, right? I don't see anything related to thrift around it anymore.

**Comment by vprithvi** [comment]
@jpkrohling The problem with sampling strategies was that thrift changed the serialization of enums from ordinals to strings or vice versa, causing problems when deserialized with older versions of thrift, I think.

Another consideration is whether this manual deserialization needs to be thrift, or whether we can use protobuf instead, relying on a a lighter weight code generator similar to https://github.com/square/wire  
The `wire` jar is around 55Kb and depends on `okio` which is 164Kb. 

Even otherwise, I feel that we could consider manual generation in protobuf seeing that using protobuf is the long term goal of the project - At some point in the distant future, this will set us up for removing the thrift dependency in the collectors.

**Comment by jpkrohling** [comment]
Wire was discussed very briefly here: https://github.com/opentracing/opentracing-java/issues/296#issuecomment-413457408

Looks like creating a new sender module encoding it with protobuf is the way to go, then. I'm a bit outdated regarding the protobuf tasks, so, I have to ask: have we implemented this in the server already? I think @isaachier was doing something about this in the past, but not sure it got merged already.

**Comment by yurishkuro** [comment]
No work was done for receiving spans from the clients in protobuf. We need to decide on the transport. For example, I am no longer convinced that UDP is the most efficient transport if we eventually want to do tail-based sampling, a persistent connection might be more efficient. If we choose HTTP, then we need to decide if we want to go with gRPC.

**Comment by isaachier** [comment]
I don't mind UDP because (at least at Uber) the agent resides on the same host as the tracing client. If anything, a pipe could solve the problem better than a network transport. But if you'd like to keep the networking, we should benchmark various transports with load to see which performs best. Preferably, we should test both the case where they reside on the same host and where they reside on separate hosts.

**Comment by isaachier** [comment]
That was what I would recommend.

**Comment by jpkrohling** [comment]
Are we still interested in doing this?

**Comment by jpkrohling** [comment]
I'm removing myself from this issue, as I don't expect to work on this anytime soon.
