### ISSUE TITLE
Log traffic with debug header

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger-client-java#87]
In all of the http filters, log when a request is received with jaeger-debug-header set

**Comment by yurishkuro** [comment]
I don't think this should be done in filters, but rather in the extractor.

**Comment by magnusp** [comment]
Is this still valid? And if so, could we have a few pointers where to look, related tests etc?

**Comment by yurishkuro** [comment]
This is the place where logging should happen: 

https://github.com/jaegertracing/jaeger-client-java/blob/d444df27c8f802a6938a0520f795c84e5dde44f6/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java#L349-L353

The debug header is being tested here:

https://github.com/jaegertracing/jaeger-client-java/blob/0b2d27c8105da8f98121063ea68e09dd2272a49f/jaeger-core/src/test/java/io/jaegertracing/internal/AdhocHeadersTest.java#L50

**Comment by gana2244** [comment]
Can you please confirm in which version this feature is available? I used the latest 1.5.0 and following this documentation - https://github.com/jaegertracing/jaeger-client-java#via-http-headers but could see it working. Am I missing some configuration somewhere?
